### ISSUE TITLE
Issue with building docker file

### ISSUE THREAD

**Issue by mar005** [tsightler/ring-mqtt#1]
Currently trying to build this on an unRAID box and I am getting this issue. Not sure how to overcome this. :(
![IMG_0041](https://user-images.githubusercontent.com/24581058/65007551-22c87000-d8cc-11e9-8a9f-15ec5858ad81.jpeg)

**Comment by tsightler** [comment]
Not much to go on in this screenshot, but the log might actually have some clues.  I haven't tested the Dockerfile because this form is mostly just for my use and I don't use Docker for this.  The Dockerfile is just a copy of what was in ring-alarm-mqtt and I know it worked there, but could be some bug here for all I know.

I don't really have much time to support this code right now so my responses will likely be slow, but I can try if you post the log.

**Comment by mar005** [comment]
It was just an issue with nodejs I think and a combination with dns issue. I have this working on my unRAID box.
