### ISSUE TITLE
Connection to ring broken for 4 hours after 5 minute internet outage

### ISSUE THREAD

**Issue by AdrianGarside** [tsightler/ring-mqtt#104]
I have automation set to set my alarm to home mode at midnight if we are both home and disarm it at 6am if either of us is home. Last night my ring alarm went to cell mode for 5 minutes at 3.10am. Home assistant logs lost ring alarm as unavailable until 7.16am. Which meant the 6am disarm didn't happen and we got a surprise when my daughter opened the patio door! 

Are there any other logs that would help understand the apparent 4 hour disconnect to the ring alarm after only a 5 minute internet outage?

**Comment by tsightler** [comment]
The script monitors the status of the websocket connection to Ring via capabilities provided by the ring-client-api and logs when this socket is connected or disconnected, so you can see when the script thought the connection resumed.  That's likely the only log data available from the script itself since it's unlikely you were running in full debug mode at the time.

I've tested the websocket monitoring capability and re-connectivity quite extensively and I've never seen it take more than 60 seconds or so once internet connectivity was re-established, assuming everything else was correct network wise and Ring servers and the location were properly online.  Regardless, the script itself doesn't have much control over this, it just monitors the status of the websocket as reported to it, it's up to the underlying API code to maintain and report the connection so I'm not really sure there's much I can do there..

However, I do wonder if it maybe has something to do with the switch of the base station to cell mode as I feel like I've seen this behavior previously when this happened and the script took a very long time to reconnect.  Perhaps we could test this scenario more extensively by blocking the base station from reaching the internet and forcing it to switch to cell for 5 minutes, then putting it back.  Most of the scenarios I've tested previously involved disconnecting the server running ring-mqtt, not the base station switching modes.

If you have the ability to test this yourself, I'd be interested in the results.

**Comment by AdrianGarside** [comment]
I can easily test that but I've not yet been able to reproduce all the ring devices going to the unavailable state and its been 20 minutes on cell so far. I also see there was a 4 second transition to unavailable around 8am this morning without any notification from the alarm that it had gone into cell mode.

Maybe I need to block internet for the whole house to match what I assume was the real trigger.

What do I do to view the script logs?

**Comment by tsightler** [comment]
> What do I do to view the script logs?

How are you using the script?  Via the addon on using docker/standard install?  In the addon the logs are visible in the "logs" screen or you can get full logs from the current session using the command line using "docker logs" command.  For other install methods it depends on how you started the script and if you enabled debug logs or not (by default the script produces no output at all).

Just to be clear on the operation, for alarm devices the script monitors the websocket connection to the Ring services which is maintained by the underlying ring-client-api code.  If the websocket is up then the devices will not go offline.  Simply firewalling the base station will not trigger the websocket to go offline, you would need to also firewall at least your server running the ring-mqtt script as well.

Firewalling the base station should make the base station switch to cell backup, usually in about 5 minutes, but, at that point, the script will still show devices online, because the websocket is still fine, but individual sensors will not receive updates (this is true in the Ring App as well).  I'm not currently monitoring for this situation, i.e. the base station being on cell backup while the device running this script will be online, because a) for most people, it's the same internet connection for both and b) I've only very recently added support for the base station at all, and that's the only way to know if the device is on cell backup or not (as far as I can tell, when the device is on cell backup you basically get one final update for all devices just after it switches and that's pretty much the end of state updates unless it goes into active alarm state).

Is there any chance that you had a longer outage and that the Ring alarm simply switched over to cell service for that time?  That should be clearly logged in the Ring app.  Also, do you happen to have any Ring cameras?  They use a completely different method of determining if the device is online or not, the script actively polls each camera for it's health state every 60 seconds, so it would be interesting to see how their state displayed during this time.

**Comment by tsightler** [comment]
Since I haven't heard anything from you on this in almost 3 weeks and the code for monitoring the websocket connection has been in place since almost the start and I have no other reports of this issue, I can't reproduce it, and I don't believe this issue would be in ring-mqtt anyway as the connection monitoring itself is done in the underlying ring-client-api code, I'm going to close this issue for now.  If your testing does manage to reproduce a scenario where the ring-mqtt portion of the script does not behave correctly, I'm happy to re-open and investigate further.
