### ISSUE TITLE
Unable to start addon after upgrading to 4.0.0

### ISSUE THREAD

**Issue by jeffgardnerdev** [tsightler/ring-mqtt#105]
I had my addon set to auto-update and it randomly stopped working--all of my devices became unavailable. I noticed it had updated to 4.0.0 and I suspect this is the issue. The addon is in a stopped state and when I try to start the addon it gives an error "Failed to start addon; Unknown error, see logs". The addon logs are empty and I don't see anything remarkable in the HA logs.

**Comment by jeffgardnerdev** [comment]
Found this in the supervisor logs:
`20-09-06 16:36:40 ERROR (SyncWorker_1) [supervisor.docker] Can't create container from addon_a98c085d_ring_mqtt: 404 Client Error: Not Found ("No such image: tsightler/ring-mqtt-ha-addon:4.0.0")`

However I do see an image in Portainer with this tag `a98c085d/armv7-addon-ring_mqtt:4.0.0`.

**Comment by tsightler** [comment]
As noted when you open an issue, if you are having a problem with the addon you should be reporting the issue on the addon project page, not here.  This issue is already open there so I'm closing this.

I do appreciate the added info however, as seeing the image helps me at least understand a little what might be happening.  Regardless, the easy fix is to simply remove and reinstall the addon.
