### ISSUE TITLE
4.1.0 Docker image failing

### ISSUE THREAD

**Issue by formerghostlyform** [tsightler/ring-mqtt#114]
** Describe the bug **
4.1.0 Docker image won't start. I have one of my instances automatically updating and it started failing this morning after updating to the 4.1.0 docker image. I also notice that 4.1 and 4.0.4 are about 30mb different in size.

**Debug Logs**
Error: Cannot find module '/ring-mqtt/ring-mqtt.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by tsightler** [comment]
I don't really understand what is happening above.  It looks like it's trying to use the entrypoint for the 4.0.4 image to start 4.1.0, which definitely won't work as 4.1.0 now uses the same Docker image as the main ring-mqtt project so that I don't have to maintain separate images.  The size difference is expected as I now remove the npm cache as part of the build process to save that space in the image.

But I have no idea why or how Docker would decide to use an old entrypoint with a new image.  I've tested the upgrade on the dev platforms I have access to and it works every time.  As noted in the changelog, there was an issue with the 4.0.x releases where upgrades didn't clean up the old releases due to a missing version label in the Dockerfile.  I've fixed this in 4.1.0, but it won't help for the old images, perhaps somehow that's causing an issue.  I'd suggest manually removing the old images using "docker system prune".

**Comment by tsightler** [comment]
Have you been able to do any investigation?  It's quite clear that the generic image itself is not the problem as I would have dozens of users reporting the issue (as happened with the 4.0.0 release within hours) and so far this is the only report of this problem in 4 days.  I did have another user report getting 404 error messages from Docker hub when he was trying to install the addon and that would have been roughly the same time that your system may have attempted the auto-upgrade.  I wonder if the problem is somehow related, perhaps the image was somehow only partially updated.  I would try removing the addon and installing from scratch in that case but without more data/log from the supervisor during the upgrade attempts there's not much I can go on.

**Comment by formerghostlyform** [comment]
You were absolutely right.  docker image prune and a restart with the latest image fixed the issue.  Weird stuff, but hey... thanks for getting back with me so quickly even though I was a slouch and didn't respond very quickly at all.
