### ISSUE TITLE
Unable to start Docker instance - invalid refresh token

### ISSUE THREAD

**Issue by johnall203** [tsightler/ring-mqtt#118]
Hello,  I feel like the instructions are straight forward for Docker deployment and execution of ring-mqtt.  I have tried re-generating the RingToken several times. The tokens generate each time without issue.  However, every time I try to run docker command it keeps saying token is invalid.  Am I missing something ?  My eventual goal is to get this working with my Home Assistant which is in a docker container also. Thank you for any help you can provide.   

-------------------------------------------------------
| Ring Devices via MQTT                               |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt              |
-------------------------------------------------------
ring-mqtt.js version: 4.1.1
-------------------------------------------------------
Running ring-mqtt...
2020-09-24T01:47:41.260Z ring-mqtt Using configuration file: /data/config.json
2020-09-24T01:47:41.265Z ring-mqtt Configuration file not found, attempting to use environment variables for configuration.
2020-09-24T01:47:41.271Z ring-mqtt File /data/ring-state.json not found. No saved state data available.
2020-09-24T01:47:41.469Z ring-mqtt Attempting connection to Ring API using RINGTOKEN environment variable.
2020-09-24T01:47:41.852Z ring-mqtt Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
2020-09-24T01:47:41.853Z ring-mqtt Could not create the API instance. This could be because the Ring servers are down/unreachable
2020-09-24T01:47:41.854Z ring-mqtt or maybe all available refresh tokens are invalid.
2020-09-24T01:47:41.854Z ring-mqtt Please check the configuration and network settings, or generate a new refresh token, and try again.
2020-09-24T01:47:41.855Z ring-mqtt Exit code: 2

**Comment by tsightler** [comment]
Based on the fact that it says:

`2020-09-24T01:47:41.271Z ring-mqtt File /data/ring-state.json not found. No saved state data available.`

Then it seems you are not providing the container a persistent volume on which to save the refresh token so you will pretty much need a new one every time you run it.  See the Docker section in the readme for an example of providing a volume and, if you still have issues, please post your docker run command here.

**Comment by johnall203** [comment]
Hello Sir, thank you for the quick reply.  I tried last night to setup using with a volume and had the same result and decided to fall back to the stripped down version just to see if it would correctly established.  My docker command is copied directly from gihub page and modified in a notepad to adjust the variables.  I will try again with the volume setup.  Thank you ! John

**Comment by tsightler** [comment]
Any updates?  I've removed the bug label for now since there's no evidence that this issue is a bug as, if this really didn't work I'd have dozens of people reporting it.  However, I can't rule out the possibility that there is some environment related issue that is triggering this specific case.  Happy to work with you to figure it out.

**Comment by danielsmith89** [comment]
I'm having the same thing, was working perfectly up until the latest update

UPDATE: Reverted back to 4.1.1 and it works perfectly again with exactly the same config. Seems to be a bug in 4.2.0

**Comment by tsightler** [comment]
Hmm...the issue above was opened before 4.2.0 was released, so it's not likely your problem and this issue are related.

The 4.2.0 release was a very minor update overall, it only got the minor version bump since one new device was added.  There were exactly zero changes to any of the code that handles authentication in 4.2.0 and there were precious few changes at all to ring-mqtt.js (where all Ring auth/refresh token handling is, except the web interface itself), a couple of lines for the Z-wave range extender support and 2-3 lines to monitor the legacy hass/status MQTT availability topic where literally the only changes.  These both don't even come into play until after the authentication process so, while I can't rule out an existing bug, it's very difficult for me to see this as being related to 4.2.0 specifically.

Now, there was a minor change to the web based token generation, so if you're saying that you can get a token to work with that I suppose some bug could have possibly slipped in there, but that would be unrelated to the issue reported here and you should open another issue and post details.

**Comment by johnall203** [comment]
I have updated to the 4.2.0 update in Docker and tried running this again and I still fail. Can you help ?

I am using the example command in the bottom of your github page to execute: (only slightly modified to protect my info)

sudo docker run -it --rm --mount type=bind,source=/etc/ring-mqtt,target=/data -e "MQTTHOST=<192.168.13.110>" -e "MQTTUSER=<mqttuser1>" -e "MQTTPASSWORD=<mqttpassword>" -e "RINGTOKEN=<"refreshToken": "eyJhbGciOiJIUzUxMiIsImprdCHANGEDXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDE0MjUxNzgsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MTI0NTUxMzgsInJuZCI6IlRIeWpQU0RBWWJIbTlnIiwic2Vzc2lvbl9pZCI6Ijg4ZDA1YzNkLTlhOGEtNDE5Zi05OTllLWRkZmQ0YjFlYWJmNiIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.leluEX_taWf_TO_PROTECTWbhXWrAiHEXCUTk4ZBrvf2Ey92seNxwlHgXiU8eF4MY-ACCOUNT1ExIuLxKEz4oJpQsQ">" -e "DEBUG=ring-mqtt" tsightler/ring-mqtt

-------------------------------------------------------
| Ring Devices via MQTT                               |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt              |
-------------------------------------------------------
ring-mqtt.js version: 4.2.0
-------------------------------------------------------
Running ring-mqtt...
  ring-mqtt Using configuration file: /data/config.json +0ms
  ring-mqtt Configuration file not found, attempting to use environment variables for configuration. +6ms
  ring-mqtt File /data/ring-state.json not found. No saved state data available. +5ms
  ring-mqtt Attempting connection to Ring API using RINGTOKEN environment variable. +190ms
  ring-mqtt Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens +377ms
  ring-mqtt Could not create the API instance. This could be because the Ring servers are down/unreachable +1ms
  ring-mqtt or maybe all available refresh tokens are invalid. +1ms
  ring-mqtt Please check the configuration and network settings, or generate a new refresh token, and try again. +0ms
  ring-mqtt Exit code: 2 +2ms

**Comment by johnall203** [comment]
I also tried variations of ring token without " " as well.  I regenerated token each time trying the token variations in the ring-mqtt docker command.  I also added --network host to docker command just to see if that helped. Same result each time.

**Comment by tsightler** [comment]
You need to get rid of all the brackets and other things in your command line.  The brackets are simply there to indicate that you should put your info there, so, for example MQTTHOST=<ip_address> would mean to use MQTTHOST=127.0.0.1 (as an example).  No brackets or anything, they are just standard environment variables.  And you can just drop any options that you are leaving blank.

Also, for the token you appear to have copied not just the token itself, but the entire JSON result, that's certainly not going to work.  You only need the token.

Something like this should bring you much better success:

```
sudo docker run -it --rm --mount type=bind,source=/etc/ring-mqtt,target=/data -e "MQTTHOST=192.168.13.110" -e "RINGTOKEN=eyJhbGciOiJIUzUxMiIsImprdCHANGEDXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDE0MjUxNzgsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MTI0NTUxMzgsInJuZCI6IlRIeWpQU0RBWWJIbTlnIiwic2Vzc2lvbl9pZCI6Ijg4ZDA1YzNkLTlhOGEtNDE5Zi05OTllLWRkZmQ0YjFlYWJmNiIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.leluEX_taWf_TO_PROTECTWbhXWrAiHEXCUTk4ZBrvf2Ey92seNxwlHgXiU8eF4MY-ACCOUNT1ExIuLxKEz4oJpQsQ" -e "DEBUG=ring-mqtt" tsightler/ring-mqtt
```

**Comment by johnall203** [comment]
That did it, Thank you so much!  Thank you for the clarification ! I guess I was just being stupid.  The carrots had me all messed up.  I tried googling an example of someone's running command line and I came up empty.   I have been doing my ring alarm integrations the long way around using Alexa routines to node red and then to MQTT to update my devices and ESP8266's...  

this is my working:
sudo docker run -it --rm --mount type=bind,source=/etc/ring-mqtt,target=/data -e "MQTTHOST=192.168.13.110" -e "MQTTUSER=mqttuser" -e "MQTTPASSWORD=mqttpassword" -e "RINGTOKEN=eyJhbGciOiJCHANGEDYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDE0MzA4NDEsInJlZnJlc2hfY2lkIjoicmluZ19vZTObF9hbmRyb2lkIiwicmVmcmPROTECTMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MTI0NTUxMzgsInJuZCI6IjZlR3pXNHJMYTWVBIiwic2Vzc2lvbl9pZCI6ImJjNjMzYzJkLWNjZDgtNGY1MS1iZjExLTM5NDkxOWU1NDFkOSIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.8_fljzZdLbzqkz_ILOQLnACCOUNTKrJE1SuW2iOQ1ZE-UBY0kMMtr_bNO_GOODPMBIbGlu-18KkSYw" -e "DEBUG=ring-mqtt" tsightler/ring-mqtt

Do you have a command handy that turns this into a permanent running container that recovers on power power failure and docker startup ?

**Comment by tsightler** [comment]
It's docker so the standard docker restart features are available.  For example you are using "-it --rm" which means to run interactive, attach the terminal, and automatically remove the container when the program exits.  Good for testing, not so much for running as a service.  I usually run with "-d --restart unless-stopped"  which is almost the exact opposite, that means detach from the terminal and run in the background and also restart automatically unless it has been explicitly stopped via "docker stop" command.

There's plenty of tutorials on Docker around, so I didn't try to reproduce the Docker manual in the readme.

Also, since you've run it successfully once, you should really be able to dump the massive long "RINGTOKEN" line now.  You should see a token file in /etc/ring-mqtt which it will read on startup and keep updated when they refresh every hour.

**Comment by johnall203** [comment]
Thank you for the help ! I can see all the messages making it into my MQTT broker. I'm a Network guy by trade.  I'm a NOOB to Docker but see it's appeal. I literally just started migrating my apps to it from running several raspberry pi's or VM's. Seems like I can get more out of my toys without accidently messing anything up in another container.    Now on  to do the integration with HASS.    Thanks again !  John

**Comment by johnall203** [comment]
oh...  last side note...  I had to add the directory /etc/ring-mqtt  and chmod the directory so it could be written to when docker runs.  Just in case any other noobs come along and run into same thing as me.
