### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wpc3001** [tsightler/ring-mqtt#127]
i cant seem to get past this error in the logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec /run.sh: Exec format error
[cmd] /run.sh exited 126
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by tsightler** [comment]
Usually this indicates a failure of the addon to install, typically due to space constraints or other issues.  The above logs are from HA, not from the addon, but it couldn't even run the startup script in the container so that would indicate issues with the installation.  I don't really know how to help you beyond that.

**Comment by tsightler** [comment]
I'm going to close this for now since I don't believe this is an issue with this project as there are far too many existing installs with not issues.  If you continue to have issues you are welcome to comment here and we can re-open the issue to attempt to troubleshoot further.

**Comment by ThomasWeiss** [comment]
@wpc3001 did you manage to work around this issue? I'm running into the exact same error
