### ISSUE TITLE
Dockerfile ENV options should support secrets

### ISSUE THREAD

**Issue by pixeldrew** [tsightler/ring-mqtt#132]
I'm using ring-mqtt in a docker container. Docker ENV properties are generally considered insecure because anyone who has access to the docker service can see the env properties of the container. A common pattern in containerized applications is to include _FILE env variables that could be considered secret, you then inject the secrets using docker secrets and they're available as mounted files on the containers filesystem. For more information see: https://docs.docker.com/engine/swarm/secrets/

For instance RINGTOKEN, MQTTUSER and MQTTPASSWORD would be good candidates to swap out to RINGTOKEN_FILE MQTTUSER_FILE and MQTTPASSWORD_FILE respectively (i'd keep the originals properties in place and only overwrite them if the _FILE variable existed)

The only issue I see with RINGTOKEN_FILE is that during the refresh cycle you write back the value and as far as the secrets documentation is concerned it looks like these are never persisted back to disk and only loaded in memory

**Comment by tsightler** [comment]
While I generally agree with you I'm not really sure this is a significant issue for this project.  This project is used mostly by home users and they are typically the only admins and are the only person with access to the Docker service, I make it as clear as possible that protecting access to the host is critical to the security of the environment.

In an enterprise container environment, with many containers running across all types of hosts and lots of users with access to the Docker process, then sure, the concerns of credentials in environment variables are significant, but can you help me understand how this is a concern for this project?

For the common Docker/addon use case, RINGTOKEN should only used the very first time, after the very first connection a new token is generated and persisted in a file and this token is refreshed every hour and updated and is always used first on restart.  As long as the token in the file remains valid you never have to pass RINGTOKEN again and, technically, you can just manually put the token in the file the first time if you want.

Also, for the most common use case of ring-mqtt (using the Ring Home Assistant addon), the MQTTUSER/PASSWORD variables are not even used because the default behavior of the addon is to automatically detect the MQTT username/password using the Home Assistant services API, and, even if they are manually defined, they are read from options.json file, not passed via environment variables.

**Comment by MrTechGadget** [comment]
I agree, this is really not an issue, but if @pixeldrew wanted to submit these options as a non-breaking PR it would be a nice option for those few that would like a more secure method of integration with something that can disarm alarm systems.

**Comment by tsightler** [comment]
I say this half jokingly, but I'm not really sure that people that are willing to download code written by a random guy on the internet that can completely control their alarm and get full access to their Ring account, half of which use anonymous connections to their MQTT broker, are really people that are super concerned about security.  :)

One thing I could do very easily, since the code already supports it with the Home Assistant addon feature, is to introduce an environment options like CONFIGPATH for the Docker use case which defines the path to the config file and just reads the options from there, instead of using environment variables to pass parameters.  The environment variable approach was mostly used because, in the past, it wasn't required to have persistent storage but now, with the tokens expiring, I can't imagine people run this in Docker without persistent storage available so we can just put the file there.

This would be easy because all the code is already there as that's how the Home Assistant addon already works.  Rather than passing environment variables it makes the config available mounted to /data/options.json in the container.  Currently this support is triggered only when the environment variable HASSADDON=true is set, and you can use it now with the Docker install by renaming your config.json to options.json, providing a persistent mount to /data and setting this environment variable, so, effectively, I feel like this request is about 99% covered with this.

So, effectively, you can already pass all options via a file even now just by setting this (I do it all the time for testing the addon code without having to actually test on Home Assistant).

What do you think about simply implementing this in a generic way that works for both Docker and the Home Assistant addon?  That would actually simplify the code, so I can get on board with this if it addresses the concern.

**Comment by tsightler** [comment]
Closing this for now as I don't believe it's critical and I don't have time to work on and test this.  If I ever release a 5.0 version in the future I'll probably just do away with the environment variable based configuration completely.
