### ISSUE TITLE
Sorry Newb Command not found npm

### ISSUE THREAD

**Issue by Grey-Lancaster** [tsightler/ring-mqtt#14]
HASSIO
Get works,
cd ring...
npm fails
Node red installed as well as mosquitoe mqtt
wandered around google just can't find it
Thanks,
Grey

**Comment by xrolfex** [comment]
what version of node are you running? 
node --version

**Comment by Grey-Lancaster** [comment]
I say node is installed but what is installed is node red
https://nodered.org/
This is on a Pi3 with hass.io
node as well as npm are bad commands
I have tried installing just node.js but there just do not seem to be enough commands variable in the hassio shell

Thanks
Grey

**Comment by tsightler** [comment]
The code as here does not support hass.io because it needs to run in a docker container.  If you look at the thread on the forum there are some users that have forked hass.io modules of the script, you should follow those instructions.  I don't currently have plans to support hass.io in my tree.

**Comment by Grey-Lancaster** [comment]
Thanks, got it.  How about the new smart lighting or works with ring like the GE outdoor switch :)
The smart lighting does not work with ring.  It does not even show on ring.com devices.  So sad.

FWIW, I actually did not understand or realize your code simply works with ring.com.  I did not need my z-wave stick LOL

**Comment by tsightler** [comment]
Yeah, I haven't found any way to do local control of Ring alarm, so the ring.com API is all that was really available easily.

Regarding the smart lighting, I've not jumped on the Ring smart lighting as I'm just not happy with a battery powered solution and the integration looks weak at best (reinforced by your comment).  I have been researching but I'm not sure I really need "smart" lights outside for this.  If they come on at dusk and charge via solar, that seems good enough to me.

I'm going to close this issue for now since it's not really related to the code.  I'm still considering the possibility of adding/integrating HASS.io support into this tree since several people have submitted pull request, but there are a few other things that need to be handled and I just haven't had time to work on it and I don't use HASS.io because I don't see the value personally, but I know it is popular.

**Comment by Grey-Lancaster** [comment]
>  I don't use HASS.io because I don't see the value personally
:)
I now zero.  I had a pi, hassio was easy to load.  I have been spending too much time on it.  I got ring, a thermostat and some lights, even weather

But there are some things I just can't seem to get on Hassio, so I thought I would just load it on windows. to get the "full" version.  I managed to get home assist loaded and up with python wheels and virtualevn somehow but there is not a config.yaml to be found lol

so HASSIO is better for dummies YMMV

**Comment by tsightler** [comment]
Oh, I understand, that's why I said I don't see the value personally, but I know there is value to others.  I'm a 20 year Linux user so installing Raspbian and standing up a virtualenv for Python is easy, but I know that's not most people.

On the other hand, it exactly that HASS.io tries to hide everything complex that's the problem.  It effectively shifts the burden of knowing stuff from the end user to the person providing the solution.  This is completely reasonable for a product people pay for, but is asking a lot for a project like this that I maintain only in my limited spare time, especially when I wrote it for my own personal use, and it works just fine for me, but then just decided to share in case others found it useful.

Supporting HASS.io opens the floodgates to an entirely different group of people, some of who will, based on my experience to this point, expect me to help them with every problem they have even if 95% of those issues are due to their own lack of knowledge.  Unfortunately, I just don't have the time to commit to that today so I've made the conscious choice to not support it for now, but others have stepped up and created plugins for HASS.io anyway.

I have a couple of pull request right now to merge HASS.io support, and I haven't ruled out doing it, but I'm just concerned about the support burden and whether I can realistically help the number of people who will struggle with it, or that I can deal with the demanding people that come along with it.  It's that latter group that I just don't have patience for and even though they are a very small portion, they've soured my opinion so much already, it's difficult for me to get over the hump.  But users like you help, so that why I continue to consider it.
