### ISSUE TITLE
Ring Doorbell stopped responding

### ISSUE THREAD

**Issue by seanmccabe** [tsightler/ring-mqtt#153]
For some reason overnight, doorbell stopped responding to commands via this integration, found this in the logs:

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'last_ding' of undefined
    at Camera.publishDingState (/app/ring-mqtt-docker/devices/camera.js:272:38)
    at SafeSubscriber._next (/app/ring-mqtt-docker/devices/camera.js:149:22)
    at SafeSubscriber.__tryOrUnsub (/app/ring-mqtt-docker/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/app/ring-mqtt-docker/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/app/ring-mqtt-docker/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/app/ring-mqtt-docker/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/app/ring-mqtt-docker/node_modules/rxjs/internal/Subject.js:60:25)
    at RingCamera.processActiveDing (/app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/ring-camera.js:250:24)
    at /app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/api.js:109:28
    at Array.forEach (<anonymous>)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)
```

Restarting the container got everything back on track, reporting incase of issue that is possible to resolve to prevent further issues.

**Comment by tsightler** [comment]
That specific issue is already fixed in the dev branch which I hope to push to master in a few days.

**Comment by seanmccabe** [comment]
Will keep an eye on the release

**Comment by tsightler** [comment]
If you'd like you can test the dev branch by using the BRANCH=dev environment variable when you start the container.  This will cause the container to pull the latest dev code instead of using the code included in the image.  It won't fix the hang on network interruption, but it should at least take care of the issue above and it has a number of other fixes and minor enhancements as well (person detection for example, although it's not in it's final state yet so don't get dependent on it).  I'm expecting to push 4.5.0 sometime this week, maybe as soon as tomorrow, but more likely Thursday.

**Comment by seanmccabe** [comment]
Might run on the dev branch for a bit, will set it up this weekend.
Happy to do some testing etc, so if you need me to check anything, do let me know.

**Comment by tsightler** [comment]
Just beware that the dev branch is, well, dev!  It's currently in a high state of flux as I try to squeeze in the last few features/fixes for the 4.5.0 release which should happen this weekend (or sooner).  Because "BRANCH=dev" pulls down the latest code each time the container is run, you might get a different version if you restart the container.  I think it's starting to stabilize pretty well, and there are a few different users running it testing various features, so it's probably OK, but it has more changes than normal, especially around snapshot support for battery based cameras.

**Comment by seanmccabe** [comment]
No worries at all, I'm a dev so I get it.
I run lots of beta software, so more than happy with a few bugs around and happy to help with testing and checking fixes when they come along.
So far the only time I've restarted this container is with the issue above, otherwise they just run unless I do my monthly updates, or I am doing testing on a specific container.

**Comment by tsightler** [comment]
I've pushed 4.5.0 which includes a fix the above issue so closing this for now.
