### ISSUE TITLE
Ring Alarm keeps restarting (not responding)

### ISSUE THREAD

**Issue by SarcasmRules** [tsightler/ring-mqtt#154]
`Installing node module dependencies, please wait...

Running ring-mqtt...

(node:1) UnhandledPromiseRejectionWarning: SyntaxError: /data/ring-state.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at main (/app/ring-mqtt-dev/ring-mqtt.js:418:25)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Updating ring-mqtt to the development version...
Cloning into 'ring-mqtt-dev'...`

This started happening after removing all docker images and restarting the server (and docker).
I've tried a previous branch and the dev branch with the same results

**Comment by tsightler** [comment]
The error indicates that ring-state.json file is likely corrupt.  You'll need to remove it completely and generate a new refresh token or, if you are passing a still valid token in the environment variable, it will just regenerate a new state file after you delete it.

This is likely caused by a known condition during startup that can cause the file to be overwritten with null data.  It generally only happens if the script shuts down nearly immediately after connection.  I need to add some protection to the state update function to avoid this but I haven't had time to do so and it's not been high priority since it seems to happen very rarely (this is the first report to me even though I've been aware of this bugs existence for well over a year).

It's on my backlog of maintenance tasks to address, but that list is pretty long at this point and, unfortunately, my time is limited.  I do have a little time set aside in a few weeks that I'm going to try to address a few of these old things.

**Comment by SarcasmRules** [comment]
Yep, it was an empty file. After deleting the file and first few attempts of restarting the container it no longer had the error but kept still restarting. As you suggested I got a new token and voila, all is good now
THANKS!

**Comment by tsightler** [comment]
Closing this for now since you're issues is corrected and I know it's something that needs to be addressed better in the future.

**Comment by eliezerlp** [comment]
This happened to me after running out of disk space. Wanted to add that in case it might be helpful for others in the future!
