### ISSUE TITLE
Third party sensor

### ISSUE THREAD

**Issue by Colgaton** [tsightler/ring-mqtt#16]
I added a third party door contact sensor to my ring, it shows up just fine in the app but doesn't show up in HA. Any idea how to fix it?

**Comment by tsightler** [comment]
The current readme specifically list the devices are supported by the script and third party sensors are not listed so are not supported, that's why it doesn't work.  The "fix" would be to update the script to support such devices but I don't have any such devices and have no plans to acquire any, and, even if I did, I'd probably just integrate them directly into HA vs using Ring as I prefer local control.

However, if you have some coding skill, feel free to add support yourself and I would consider integrating it.

**Comment by Colgaton** [comment]
I see what you mean and I agree that having local control is better, I just don't have a z-wave stick for my ha, and ring is already there and it connects to it just fine.

Unfortunately I don't have experience with NodeJs nor the integration with HA, but if you change your mind in the future I can help you getting any info you need from my device.

**Comment by Colgaton** [comment]
Well after playing with it a bit I was able to make ring-alarm-mqtt to id the device as a adapter.zwave and the debug actually spits all the info i need, including the status change, deviceName, roomName, etc.

Problem is, zwave.adapter is really generic and it can mean a lot of things (the one I'm using is a door sensor). But it is a good start, any idea where to go from here?

**Comment by tsightler** [comment]
That's great that you managed to get that far.  I didn't think it would be too difficult, but indeed the generic nature of the device is pretty difficult as I wouldn't be able to automatically define a class so it would just show as a generic sensor.  Perhaps that OK?  I had also thought that I could define a custom section in the config that lets people assign devices to classes to get more specific icons.  If your willing to share a little detail about the device we can try hacking up the script and see if we can make it work.  I was actually able to add lock support even though I don't have a lock, and a sensor should be far easier.

My email is the same username as this github account using gmail, so if you would be willing to send me the debug output I could take a quick stab at it.  Thanks for looking into it!

**Comment by Colgaton** [comment]
Sure I'll email you the debug log. Like you said, it would be great if we could let the user assign a generic sensor to a class, right know in my test I'm assigning the class 'door' to it because it is a door sensor but that does not escalate well if we have multiple generic devices.

btw I forked the project and my changes (a couple lines to be true) it is working just fine, let me know if you want me to do a pull request or something like that later on, thanks.

**Comment by tsightler** [comment]
Thanks!  I'll look at in hopefully in the next few days.  One thing I'm curious about, I looked at your forked code, and I see how it would make the adapter appear, but you didn't add any equivalent code to the subscribeDevice function so I don't see how state could possibly work?  Are you actually seeing proper state changes on the device?

**Comment by Colgaton** [comment]
You are right, it is not working. I was testing the subscribeDevice function, but deviceState never gets any value because data.faulted is undefined. And when opening and closing the sensor, it never triggers the subscribeDevice function anymore, just once when starting the script.

I wonder if I need to make any change to the @dgreif/ring-alarm code to handle this device.

**Comment by tsightler** [comment]
I don't think there would need to be any changes to the API.  Based on the output you sent me I think you may just need to add:
`case 'adapter.zwave':`

Directly under the line:
`case 'sensor.motion':`

In the subscribeDevice function.

Right now, if an event comes from an adapter.zwave device and calls the subscribeDevice function, there's no defined action for that device type within the function.  However, based on the output you sent, the faulted variable is the correct one to act on so adding adapter.zwave to trigger that logic for the device seems like it should be enough.

Admittedly just guessing, but it seems logical.

**Comment by Colgaton** [comment]
That was actually my first try, I added **case 'adapter.zwave':** right on top of **case 'sensor.motion':** and it didn't work.
As far as I understand, it never triggers this line:
                **var deviceState = data.faulted ? 'ON' : 'OFF'**
because data.faulted value is not 1 or 0, is undefined.

But I'll give it another try soon, maybe I missed something.

**Comment by tsightler** [comment]
But in the debug output you sent me it has this:

"device":{"v1":{"faulted":true}}

Which is the very same status that the official Ring contact/motion sensor provides, so I would think it should work just fine (true/false is evaluated properly by that line).  I don't understand why data.faulted would be undefined.

I'll consider purchasing a cheap Z-wave sensor to test it, I can probably find somewhere to use it.

**Comment by Colgaton** [comment]
Yep my bad, in the debug logs 'faulted' really changes from true to false when i open and close the sensor. But for some reason HA does not see the change, status is always OFF.

This is the info i get when starting the script (I added a few console.log to function subscribeDevice), you can see faulted is somehow 'undefined'.

data.deviceType: adapter.zwave
zid: c1f4f40c-5812-450d-9255-bfc8672fe8e6
name: Z-Wave Adapter
deviceType: adapter.zwave
batteryLevel: undefined
batteryStatus: none
batteryBackup: undefined
manufacturerName: undefined
serialNumber: undefined
tamperStatus: ok
faulted: undefined

Lines I've added to the function:

                console.log('zid: %s', data.zid)
                console.log('name: %s', data.name)
                console.log('deviceType: %s', data.deviceType)
                console.log('batteryLevel: %s', data.batteryLevel)
                console.log('batteryStatus: %s', data.batteryStatus)
                console.log('batteryBackup: %s', data.batteryBackup)
                console.log('manufacturerName: %s', data.manufacturerName)
                console.log('serialNumber: %s', data.serialNumber)
                console.log('tamperStatus: %s', data.tamperStatus)
                console.log('faulted: %s', data.faulted)

**Comment by Colgaton** [comment]
and   **publishMqttState(deviceTopic+'/state', deviceState)**

always spits "OFF" during the start, does not matter if the sensor is open or closed.

**Comment by tsightler** [comment]
I'll offer another suggestion, just add:

`console.log(data)`

So that it will list out all properties of the object being returned, then we can see if the faulted variable is in there at all.  The fact that you are seeing an event makes me think that perhaps the API is returning the raw data vs the flattened data.  That's just a guess honestly, I haven't looked at the API code in a while, but regardless, dumping the entire data structure should tell us fairly quickly.

**Comment by Colgaton** [comment]
This is what I got, no mention for faulted unfortunately.

{ adapterType: 'zwave',
  batteryStatus: 'none',
  categoryId: 29,
  commStatus: 'ok',
  commandTypes:
   { 'kitting.start': { requiresTrust: false },
     'make-device-forget-network.start': { requiresTrust: false },
     'make-device-forget-network.stop': { requiresTrust: false },
     'orphaned-nodes.clean': { requiresTrust: false },
     'provide-info.dsk': { requiresTrust: false },
     'recycle-device': { requiresTrust: false },
     'replace-failed.start': { requiresTrust: false },
     'replace-failed.stop': { requiresTrust: false },
     'reset-network': { requiresTrust: false },
     'update-node-neighbors.start': { requiresTrust: false } },
  deviceFoundTime: 1516376905990,
  deviceType: 'adapter.zwave',
  lastCommTime: 0,
  lastUpdate: 1560117358947,
  managerId: 'zwave',
  name: 'Z-Wave Adapter',
  pollInterval: 0,
  roomId: 1,
  setupByPluginStatus: 'complete',
  setupByUserStatus: 'unset',
  subCategoryId: 0,
  tags: [ 'unremovable', 'hidden' ],
  tamperStatus: 'ok',
  zid: 'c1f4f40c-5812-450d-9255-bfc8672fe8e6',
  network:
   { lastResetTimestamp: 1559708750071,
     nodes:
      { '6': [Object],
        '7': [Object],
        '8': [Object],
        '9': [Object],
        '10': [Object],
        '12': [Object],
        '13': [Object],
        '14': [Object],
        '15': [Object],
        '16': [Object] } },
  orphanedNodeIds: [],
  reportedGatewayStatuses: [] }

**Comment by tsightler** [comment]
Hmm, so after looking a little closer at the original debug output that you sent me, I see that it actually shows proper "faulted" status, however, in that output, the deviceType is actually just "sensor", not "adapter.zwave".  I'd try changing "adapter.zwave" in the code to just "sensor" in both the supportedDevice and subscribeDevice functions and see what happens.

I think the "adapter.zwave" is actually the physical Z-wave controller/adapter in the base station as the output above include the nodes for each connected Z-wave device so that's not the actual events you want.  That would explain why it has no status or other fields that would be expected for a sensor, because that device is not a sensor.

This is further confirmed by the fact that the original debug output you sent me has a different zid from the zwave adapter zid that you posted above and that the name says "Z-wave Adapter".  This is a dead giveaway as, even though I have no actual generic Z-wave sensors, I still have a device of type zwave.adapter in my setup and the output actually looks like the output I would expect from the Z-wave controller, not a sensor.

**Comment by Colgaton** [comment]
Yeah you nailed, after making the change it's working in my local machine, can't make it work in hassio though but that's probably something I'm doing wrong in the docker side. I've uploaded the fixed code to my fork if you want to give it a look.

**Comment by tsightler** [comment]
Too bad I missed that in my first glance, it seems so obvious now.

I've been working on updating the code to make it function properly with the recent changes in the ring-api which is based on locations vs alarms (because locations may have cameras/lights, but not alarms).  Currently it's just the minimal changes needed to keep the code working (use getLocation vs getAlarms, and then process only locations that have an alarm panel) plus a few bug fixes.

After I get that working and published I'll start thinking about how to integrate generic Z-wave sensors.  I think I'll probably have the code dump any found Z-wave devices to a file with name, zid, and a class of none, and then, users can edit this file with the specific class if they want.  That should be pretty simple and functional.  Thanks for the help!

**Comment by Colgaton** [comment]
That's cool, I'll be glad to test it. Thank you for the help it is working fine in hassio as well.

**Comment by Colgaton** [comment]
Sorry to bring this back up but this third party sensor stopped working with the new version of this app. I was trying to hack a way to add it back, I just added it to the getDevice function just on top of "case RingDeviceType.ContactSensor" and it shows up in the logs just fine:

  name: 'Z-Wave Adapter',
  unique_id: 'c1f4f40c-5812-450d-9255-bfc8672fe8e6',
  availability_topic: 'ring/b6249dbd-4779-4ffc-4d55-79b2bfcbf23d/alarm/binary_sensor/c1f4f40c-5812-450d-9255-bfc8672fe8e6/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  state_topic: 'ring/b6249dbd-4779-4ffc-4d55-79b2bfcbf23d/alarm/binary_sensor/c1f4f40c-5812-450d-9255-bfc8672fe8e6/contact_state',
  json_attributes_topic: 'ring/b6249dbd-4779-4ffc-4d55-79b2bfcbf23d/alarm/binary_sensor/c1f4f40c-5812-450d-9255-bfc8672fe8e6/attributes',
  device_class: 'door'

But state change is never recorded, it is always OFF because this.device.data.faulted is always 'undefined'. Any idea how to fix it? Thank you.

**Comment by tsightler** [comment]
Yeah, generic sensor support is still on my to-do list.  I guess I still need to purchase some generic Z-wave sensors and work that out, my guess is it would be quite easy to finish up.

Regarding your issue above, based on the fact that the name is "Z-Wave Adapter" I think you are catching the adapter device, not the sensor device (the same issue you had above the first time around).  As a super hack you could try adding something like this below the "lock" condition, but before the return null at the end of the function:
```
    if (/^sensor($|\.)/.test(device.deviceType)) {
        return new ContactSensor(device, mqttClient, ringTopic)
    }
```

That way, if it falls through the case statements, but it has the word "sensor" in the deviceType, it will return it as a contact sensor.  It's not a proper fix (it could pick other other unsupported sensors, like 3rd party water/temp sensors) but it might be good enough for your case.

**Comment by Colgaton** [comment]
Yep it works, thank you! Interesting that now it shows up with the right name on HA, before it was showing up as binary_sensor.zwave_adapter.

**Comment by tsightler** [comment]
That's actually good and not too surprising as the code has progressed quite a bit from those early versions.  It helps to show that all of the plumbing I've been working on is doing the right thing.  At this point I think it's mostly about writing the logic to detect the sensors correctly and that's about it, after that they should "just work".  I'm doing some major refactoring work with the 4.0.0 release (currently in beta in dev branch) and, once that's behind me (I still need to add support for the base station and panic buttons, and some "info" data for the cameras, other work is mostly done), I'll try to complete the work for generic 3rd party sensors.

**Comment by Colgaton** [comment]
That's great news, thank you so much for the time you spend on this project. After adding support to the base station, will there be a way to trigger a chirp tone from HA?

And is there a way for me to donate a third party sensor?

**Comment by tsightler** [comment]
I don't think it will be possible to trigger a chirp tone, at least, I don't see a way to do this from the API.  The general idea is, if you can do it from the app, you can do it from the API, otherwise, not so much.  I can't see any way to trigger a chirp tone from the Ring App and looking at the location and base station device object, I can see how you can see what tones are assigned to each device, and I can probably change them, but I don't see any way to force a tone to play on demand.

If you'd like to donate a sensor, you can send me message to my Gmail account (same username) and I can send you my mailing address.  I was just going to buy the cheapest 3rd party motion and contact sensor I could find.  I could probably find a use for the motion sensor anyway as I'm currently using an official "Ring" branded one for nothing but turning the backyard lights on when the dogs go outside at night!  A 3rd party one would be perfect for that.

But if you'd like to donate a contact sensor, I would not turn it away, just message me.  However, no pressure either, I'll buy one eventually.  The project had somewhat stagnated over the last 6 months as I just didn't have time to mess with it, but I'm trying to get it back on track.  With the 4.0.0 release I think it will be very maintainable going forward, at least, I hope so.

**Comment by Colgaton** [comment]
No worries, it's just a way to give something back, as I have been using this software for a while now. I will get in touch in private.
