### ISSUE TITLE
Support for Ring Lighting

### ISSUE THREAD

**Issue by rs1932** [tsightler/ring-mqtt#17]
Hi,
I noticed that @dgreif has added support for the Ring lighting hub and products. Any chance you could add support for that in this?
Thanks

**Comment by tsightler** [comment]
I don't have any plans to purchase Ring smart lighting as it feels overpriced for the functionality provided and they all seem to be battery powered, which just doesn't do it for me.

Looking at the API code, it shouldn't be too difficult to add, but I'd really want to refactor a little to split device code into separate files and make the entire code more maintainable.  That's not a ton of effort, but just not something I have time to do right now.  I also have a backlog of bugs/issues I need to fix in this code, although nothing that really impacts function really, but stuff that is just "ugly" and should be fixed.

I would consider merging a pull request if someone else was willing to code up support, and I'm not saying I would never do it, but I don't think it's something I can code up without having a device to test and I'm just not planning to purchase any Ring lighting at this time.

**Comment by rs1932** [comment]
Totally understand the lack of time. I can try to take a stab at adding support if you dont mind answering a couple of questions:
1.  I noticed that you use the getAlarm and it seems to come from the API, I cant seem to locate how where this function. I figure I will need to start by getting the equivalent for the light hub
2. It looks like the messages come on the same websocket so I should be able to listen and then add in the new device support, I think. New to JS!

thanks for the help

**Comment by tsightler** [comment]
Ha, well, that's understandable as I think that, while adding lighting support, dgreif has changed the function to getLocations rather than getAlarm, which makes sense because now you can technically have a location with just a lighting bridge but no alarm.  Unfortunately, I haven't had time to look at his changes in any significant detail but that's what seems to be the case at a quick glance.

You shouldn't have to mess with the websocket at all as that's handled by the API and completely abstracted from the upper level code that is this script.  You just getLocations (replace getAlarms with getLocations), and then as you enumerate devices you subscribe to events and send commands to devices.  The only thing I do in the code is monitor the websocket status so that I know if the connection is interrupted and needs to be reestablished,  but even this is handled by a function in the API as dgreif added that capability on my request.

**Comment by tsightler** [comment]
I'll try to take some time this weekend to at least make the updates so that existing functionality will work with the updated API.

**Comment by rs1932** [comment]
Thanks, I am relieved, I was questioning if I knew what I was doing! 
One other question if u dont mind, I was actually trying to write the whole think in Python and made progress in getting the OAUTH token, list of locations, and the hubs (alarm and light hub)> however when I try to get connected to the WSS socket get an error of 404. Any thoughts? Have reached out dgreif as well

thanks!

**Comment by tsightler** [comment]
Interesting that you are trying to make this work in Python.  I stuck with JS since that's what the API was in and dgreif homebridge code was well organized and I could use it to learn how to use the API.  Plus, I had a specific desire to learn to be dangerous in JS.  I'm a far less skilled Python coder, which is sad since I'm obviously not very good at either.

That being said, I specifically stayed away from messing with the underlying REST/websocket since the API already did that.  I looked at it a little when I was trying to figure out how to monitor the websocket since dgreif originally did not have a way to do that in his API, but once he added that, I pretty much ignored the lower level code that actually communicated with Ring.com, so I'm not going to be much help there.

That being said, I've been surprised someone hasn't taken his excellent work and created a Python based API for the alarm so nice to see the attempt to do this.  If I had more Python skill (and time) I'd try to help as it would give a potential path toward native integration with HA.

**Comment by dgreif** [comment]
@tsightler you are spot on with your assessment of my changes from `getAlarms` to `getLocations`.  Ring is adding more and more to their lineup and their api is now all based on `locations`.  I'm also currently working on adding cameras to the api 🙊.  @rs1932 good luck on the port to python.  Hopefully my code is straightforward enough to get you started.  Take a look at https://github.com/tchellomello/python-ring-doorbell/issues/104 as it may be easiest to just add ring alarm to that repo.

**Comment by dgreif** [comment]
Hey @tsightler, looks like you got updated to v2.  Unfortunately I had to rev to a v3 today.  I added camera support and it made the most sense to change the external api a bit.  I added [some info in the  readme](https://github.com/dgreif/ring-alarm#breaking-changes-from-v2-to-v3) and it shouldn't be hard to update.  Sorry for the extra work, but hopefully the cameras are helpful for you down the road.

**Comment by tsightler** [comment]
Thanks @dgreif.  Looks like it will be super easy to make that change so I'll push something this weekend.  I'm actually happy to see cameras in the API as I was hoping to add camera support to my code as part of the next development cycle, assuming I ever actually get any cycles to work on it.  Right now I'm in "just barely enough time to maintain it" mode, but hopefully in the fairly near future I can start work on the refactor and add cameras and maybe even smart lighting.

**Comment by dshokouhi** [comment]
So I am not sure how far along anyone else got here but so far I have the following working by adding a few lines of code:

- motion sensor from each light and the standalone motion sensor for smart lighting
- light status from each light

As of now they are represented by `binary_sensor` since I have not figure out how to turn the lights on/off/brightness and also how to separate light and motion sensor component topics.  Not sure if I should submit a PR or not because its kind of half baked but at least its working 😛 

![image](https://user-images.githubusercontent.com/1634145/64302098-a7170c80-cf36-11e9-8493-9cc9cdd6f6ca.png)

![image](https://user-images.githubusercontent.com/1634145/64302106-ada58400-cf36-11e9-907a-0f84218a41a6.png)

![image](https://user-images.githubusercontent.com/1634145/64302126-bc8c3680-cf36-11e9-8e8c-d86eb6241155.png)

Let me know if its something we can start from, I did not add a lot of code.

Here is the diff: https://github.com/dshokouhi/ring-alarm-mqtt/commit/865cc4c03134e804e09e48c6380526c7367d4090

**Comment by rs1932** [comment]
I took a stab at writing a custom component for the Ring alarm integration supporting both the lights and security devices. Here are the details:

https://community.home-assistant.io/t/ring-alarm-custom-component/136058


Hope this helps, keep in mind first time Python programmer and haven't programmed in a while !

**Comment by tsightler** [comment]
Now that I've finally had time to complete the long needed code refactor I'm interested in adding support for Ring smart lighting to this project.  However, there's one issue, I don't currently have any smart lighting products.  I'm looking for someone who is willing to help with this by sharing the output of the ring-device-dump tool and by testing pre-release code.  If you are willing to do this please let me know.  Thanks!

**Comment by mikesalerno** [comment]
> output

I have ring lighting and would be more than happy to help

**Comment by tsightler** [comment]
The primary thing I need is the device dump data.  The ring-client-api code includes a tool to do this which can be run like this:

node node_modules/ring-client-api/ring-device-data-cli.js

If you could run that and send me the output (gmail using same username as my github account) that's really all I need to get started.

**Comment by dgreif** [comment]
@tsightler you can take a look at the homebridge implementation in https://github.com/dgreif/ring/blob/master/homebridge/beam.ts.  That should give you a pretty good idea of what data fields you need to read from, and what methods to call to turn the lights on/off

**Comment by tsightler** [comment]
@dgreif Thanks.  I've definitely already scoured through it (your homebridge code has made it much easier for me to implement other functions previously, such as locks, which I also don't have).  But for some reason (probably my overall lack of coding skill and experience) it's easier to understand when I have the data that goes with it.  Looking at it overall, it seems pretty straightforward to implement, mostly motion sensors and multilevel lights/switches.

**Comment by mikesalerno** [comment]
@tsightler I will have the data dump for you tomorrow

**Comment by dgreif** [comment]
I had a little free time tonight so I decided to go ahead and grab the data dump.  Should be in your gmail inbox @tsightler.

**Comment by mikesalerno** [comment]
@tsightler sent my data dump this morning. Let me know if you need anything else.

**Comment by tsightler** [comment]
Thanks for the support guys!  Looking at the dumps and the homebridge code I think I have a decent idea of how to put this together.  There is some question regarding how to present light groups vs individual lights, but I guess I'll just expose them all and let people organize them in the Lovelace UI however they want.

**Comment by cjmaio** [comment]
I actually have the lights implemented in my own fork of this library, but it's the previous version, so I think I'd have to refactor it a bit for the newer library version.

**Comment by tsightler** [comment]
@cjmaio Thanks, I'll take a look at it.  Should be pretty easy to adapt to the new model.

**Comment by tsightler** [comment]
I've pushed my first attempt at this to the "dev" branch.  Since I have no Ring smart lighting myself, if someone interested in this feature could pull the dev branch and test it I would really appreciate it.  Overall it was pretty simple since they are just motion sensors and switches/multi-level switches, devices that are already supported, so it's mostly the same code, but of course I could have typos or other things that I didn't get right.
