### ISSUE TITLE
No detection of External Siren

### ISSUE THREAD

**Issue by neil2048** [tsightler/ring-mqtt#175]
Hi  

I have justed added a Ring External Siren to my alarm, after a reboot of the addon and HA, no additional devices are found,  there are also no additional devices reported into MQTT from the addon.

Should i see the Siren appear as another device in HA? As i want to monitor the battery status from HA

Thanks

Neil

**Comment by neil2048** [comment]
> does the siren appear in that list at all, even as an unsupported device? I think it should, even if ring-client-api has no explicit support for it.

Yes it does.

{"acStatus":"ok","adapterType":"zwave","batteryLevel":100,"batteryStatus":"full","categoryId":34,"commStatus":"ok","commandTypes":{"communication-poll":{"requiresTrust":false},"reconfigure.start":{"requiresTrust":false},"siren-backlight.disable":{"requiresTrust":false},"siren-backlight.enable":{"requiresTrust":false},"siren-test.start":{"requiresTrust":false},"siren-test.stop":{"requiresTrust":false},"siren.start":{"requiresTrust":false},"update-node-neighbors.start":{"requiresTrust":false}},"deviceFoundTime":1622034886833,"deviceType":"siren.outdoor-strobe","firmwareUpdate":{"eligibility":"eligible","state":"up-to-date"},"impulseTypes":{"comm.ping.received":{"trusted":false},"tampered":{"trusted":false},"tampered-cleared":{"trusted":false}},"lastCommTime":1623154198860,"lastUpdate":1623154199052,"linkQuality":"ok","managerId":"zwave","manufacturerName":"Ring","name":"Siren","pollInterval":43200,"roomId":11,"setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":0,"tags":["kitted","scanned"],"tamperStatus":"ok","zid":"aaaaaaaa-aaaa-uuid","auxBattery":{"level":0,"status":"none"},"backlightState":"disabled","brightness":0.75,"maxSirenDuration":3,"maxVolume":4,"sirenStatus":"inactive","volume":3}]}]}

**Comment by tsightler** [comment]
OK, so it should be possible to support it.  at least to show battery status and maybe some of the other values.  Might not be possible to control anything with it tough, but maybe that's OK.  Probably could just copy something like the extended and use that as a template.  I'm hoping to carve out a little time for this project in the next few weeks as I have a pretty good backlog of issues that need to be address, some of which is broken functionality due to changes in Home Assistant.  I'll keep this feature in mind since it should be fairly easy.

**Comment by neil2048** [comment]
That would be really good if you can, i mainly wanted to monitor, acStatus, batterylevel and auxBattery (if poss) and lastCommTime.  to be able to confirm its still alive really, anything else you can add would be greatly appreciated.

**Comment by tsightler** [comment]
I hope to support the outdoor siren in 4.6.0 which I expect to push in the next 1-2 weeks.  I've already pushed the changes for this into the dev branch if anyone with a siren would be willing to test and see if it works.  It should show both the siren state (off/on) and all key attributes should be available in the info sensor (battery, auxBattery, acStatus,, volume, etc).

While I'm pretty sure it will work since it's mostly just a copy of existing devices, if someone has a chance to test the dev version it would be really appreciated.

**Comment by neil2048** [comment]
Morning

Thanks for this, i have switched to the Dev branch, i can now see the Siren
and all its info and its looking good.

Will advise if i see any issues with it.

Regards

Neil

**Comment by tsightler** [comment]
Version 4.6.0 has been pushed which includes basic support for Ring siren.
