### ISSUE TITLE
URL for camera snapshots?

### ISSUE THREAD

**Issue by broyuken** [tsightler/ring-mqtt#179]
Is there a url I can use for the camera snapshots? I would like to feed it into something like Frigate to do object detection for my trash and recycling.

**Comment by tsightler** [comment]
As the name implies, this project uses MQTT, there's no URL, but you can use any MQTT client to receive the snapshot data on the topic (basically, it's just binary JPEG image sent via MQTT), for example, you could have a flow in Node Red to forward the images.

If you are talking about automating in Home Assistant, then this is really a Home Assistant question.  It's definitely possible to access the current camera image via an automation and have it sent as a JPG, but I haven't done it myself.  I believe you'll want to look at the camera.snapshot service, which lets you take a snapshot of the camera from an automation, save it as a file, and then you can do whatever you want with it.

**Comment by tsightler** [comment]
I just took a quick look at Frigate and I don't think something like that is going to work with a Ring camera.  Based on what I can see it wants to start a low framerate livestream directly to the camera as it's designed for working with local IP security cameras that can send an RTSP stream directly and it basically is just constantly analyzing the stream.

You can't start a RTSP stream directly to a Ring camera, you have to start a stream via Ring's servers by creating a SIP session and then the connection is proxied through their media server, which is what makes using video via the Ring app seamless and easy and allows them to record clips and process images in the cloud without requiring the user to have any local servers.  You could theoretically start the stream and send it to Frigate anyway, but since the stream is not local directly to the camera, but rather proxies through Ring servers, they only allow live streaming for so long before they force kill the session.  Basically, Ring cameras are not designed for 24/7 local streaming (remember, a lot of their devices are battery powered and live streaming won't take long to kill a battery.  

Frigate expects a standard IP security camera that is designed to record to a local NVR.  If you really want to do that I'd suggest purchasing one of those cameras instead.  They are cheap compared to Ring cameras.

**Comment by broyuken** [comment]
Yea I understand that you can't do live view but I was hoping there would be a url for the camera snapshot that I could feed in as a video feed that updates every 10 seconds. It wouldn't be real time but I would at least be able to do object recognition in semi-real time. If the snapshot isn't accessible like that no worries.

**Comment by tsightler** [comment]
Yeah, nothing today.  I've been considering the option of implementing live streaming on motion directly to the HA camera API instead of via MQTT, so that I could stream motion events in realtime, but that's really a change in direction for the project and not one I'm sure I have time for seeing I can barely maintain this project as it is at this point.

You could probably build something hackish just just forwarding the JPEG images to an ffmpeg process that recreates a stream.

**Comment by miguelarios** [comment]
I an automation that I pieced together by looking at the attribute of the image that ring passes. Basically I concatenated my nabu casa url like so:
`"https://[SOME RANDOM STRING].ui.nabu.casa{{ state_attr('camera.front_door_snapshot', 'entity_picture') }}"`

What I do is feed this in an automation to give me a notification with the image attached.

You could potentially try feeding this image to Frigate, _potentially_

**Comment by broyuken** [comment]
thats absolutely perfect! I didn't know there was the entity picture attribute on the camera image. I should be able to do what I want with this now.

I don't use Nabu Casa, but my url looks like this.
https://ha.mysecrethaurl.com/api/camera_proxy/camera.front_door_camera_snapshot?token=mysupersecrettoken
