### ISSUE TITLE
Cannot see z-wave thermostat in Home Assistant

### ISSUE THREAD

**Issue by 2carlos** [tsightler/ring-mqtt#186]
I recently added a zwave thermostat (GC-TBZ48) to my ring base station v2. After rebooting my Home Assistant host, I don't see the device. I expect to see a climate entity I can control in HA

logs reveal the device type is not supported. Can this be added?

```
2021-07-11T15:04:17.001Z ring-mqtt   Unsupported device of type: adapter.sidewalk
2021-07-11T15:04:17.001Z ring-mqtt   Unsupported device of type: adapter.zigbee
2021-07-11T15:04:17.002Z ring-mqtt   Unsupported device of type: access-code.vault
2021-07-11T15:04:17.002Z ring-mqtt   Unsupported device of type: access-code
2021-07-11T15:04:17.003Z ring-mqtt   Unsupported device of type: adapter.zwave
2021-07-11T15:04:17.003Z ring-mqtt   Unsupported device of type: access-code
2021-07-11T15:04:17.003Z ring-mqtt   Unsupported device of type: access-code
2021-07-11T15:04:17.003Z ring-mqtt   Unsupported device of type: temperature-control.thermostat
2021-07-11T15:04:17.003Z ring-mqtt   Unsupported device of type: thermostat-operating-status
2021-07-11T15:04:17.003Z ring-mqtt   Unsupported device of type: sensor.temperature
```

**Comment by tsightler** [comment]
The answer to the question "can it be added" is yes, but the answer to the question "will it be added" is probably no, at least not any time soon.  I don't have a Z-wave thermostat and, even if I did, I'd never gateway that through Ring alarm.  If someone else wants to code up support and submit a PR then I would consider it (BTW, the list of supported devices is available in the README so logs aren't required to know that this device isn't supported).

I don't have enough time to even keep up with all of the devices Ring keeps introducing, much less every type of Z-wave device out there that people might decide to connect, especially since there are many already great ways to connect Z-wave devices to Home Assistant without having to gateway via Ring.

**Comment by tsightler** [comment]
Closing this since there's no way this will happen in any reasonable timeframe.  If at some point in the future I have tons of time available I might consider revisiting this but for now, if you want Z-wave thermostats to work with Home Assistant, my suggesting is to use some supported Z-wave method vs attempting to gateway them via Ring.

**Comment by tsightler** [comment]
So, as luck would have it, I ended up with access to some Z-wave thermostats recently so I decided to give it a try.  I coded up some basic support for thermostats and it seems to work, although at this point it's only tested with Honeywell T6 Pro Series Z-wave thermostats.

So, if you REALLY want to use Ring for a Z-wave thermostat, the dev branch has code worth testing.  I personally still think my advice above is the best as I find they work way better integrated natively via ZwaveJS, but, at least using it via Ring is an option now, although you may lose some features as Ring's capabilities are pretty limited (for example, there's not ability to read the humidity or to set away mode on my thermostat via Ring, both that's that work perfectly with the native ZwaveJS integration).

I've also found a few bugs, such as the fact that sometimes, after a state change, Ring does not get an update and become out of sync with the thermostat.  At first I thought it was an issue with my code, but then I found that I could reproduce the issue even in the Ring app.  I've attempted a workaround that seems to mostly work, but I probably need to implement some type of retry logic to address it 100%.  Or maybe Ring will eventually address the issue since it is also impacting their app.

I was able to implement the other features that Ring supports in the app, and even one that they don't, Aux heat mode.
