### ISSUE TITLE
ring-auth-cli doesn't exist in latest docker image

### ISSUE THREAD

**Issue by idyedov** [tsightler/ring-mqtt#188]
** Describe the bug **
Following the instructions in README, attempting to run:
```
docker run -it --rm --entrypoint /app/ring-mqtt/node_modules/ring-client-api/ring-auth-cli.js tsightler/ring-mqtt
```
I get the following result:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: 
exec: "/app/ring-mqtt/node_modules/ring-client-api/ring-auth-cli.js": stat /app/ring-mqtt/node_modules/ring-client-api/ring-auth-cli.js: no such file or directory: unknown.
```
when using latest docker image

**Debug Logs**
To effectively troubleshoot the issue logs will generally be required.  Please run the script with DEBUG=ring-mqtt enabled and post any relevant output here.

**Comment by tsightler** [comment]
It's there, it's just in /app/ring-mqtt/node_modules/@tsightler/ring-client-api/ring-auth-cli.js

This is because I'm currently using a modified ring-client-api library to attempt to fix the ring camera issues with losing events.  Unfortunately the attempted fix didn't work, so I'll probably just revert in a few days unless I come up with another idea to try.
