### ISSUE TITLE
audio controls not discovered for 4.6.0

### ISSUE THREAD

**Issue by calisro** [tsightler/ring-mqtt#205]
### PLEASE READ THIS FIRST ###
If you are using the Ring Devices Addon for Home Assistant, and the issue you are reporting is related to installing, configuring or operating the script underneath that platform, you should probably not be opening an issue on this page, but rather on the Ring Devices Addon page:
https://github.com/tsightler/ring-mqtt-ha-addon

** Describe the bug **
After upgrading to 4.6.0, the audio controls for the ring alarm BASE is no longer working.  This is to be expected per the release notes. What I am having trouble with though is that the number.keypad_volume was discovered properly but I'm missing the base.  

**Debug Logs**
To effectively troubleshoot the issue logs will generally be required.  Please run the script with DEBUG=ring-mqtt enabled and post any relevant output here.asd

If this is required, can you please give me some direction how I enable that?  Happy to provide whatever is required and please let me know if I need to REDACT anything in that debug log?  Really appreciate it.

**Comment by tsightler** [comment]
I'm not clear what problem you are having.


Base station vs keypad has different access requirements.  Shared users can access the volume of a keypad, while only the primary account owner can access volume control of the base station.  This is true in the Ring app as well.

When you start the addon it attempts to detect automatically if the account has access to set the volume, this is done very early, just after initial device enumeration.  If you start the addon and go to the "Logs" screen you should be able to catch this information as there is a 5 second pause immediately after this step, you should see something like:

```
2021-07-20T21:45:35.481Z ring-mqtt Ring location/device data updated, sleeping for 5 seconds.
2021-07-20T21:45:36.454Z ring-mqtt Account has access to set volume on base station, enabling volume control

```
If the account is determined not to have access to volume control it will also say so here.  Note that nothing about this detection logic changed in this release, only how the volume controls are presented in Home Assistant was changed to use the number entity instead of brightness on a light (which was always a little goofy, but the only option available at the time).

**Comment by calisro** [comment]
ah!  Thank-you.  I just created a new account to separate the two when converting over to the new refresh tokens and since I did them at the same time, I missed that note.  I didn't catch that blurb about permissions and I didn't see that entry in the logs but now I do.  

btw, the number.xxxx is much better.  Thanks for the continuous improvements.
