### ISSUE TITLE
Possible to expose battery level for cameras?

### ISSUE THREAD

**Issue by mac-n-cheese-uk** [tsightler/ring-mqtt#216]
Hi,

Is it possible to expose the battery level of doorbell/camera devices through MQTT?  

It would be great be able to handle everything related to the Ring doorbell/cameras through the MQTT integration rather than needing to also run the official integration to fill in the gaps.

Thanks

John

**Comment by tsightler** [comment]
Battery level should already be available through the info sensor, as well as Wifi signal, last update, etc.  I don't have any battery cameras to test with but nobody else as ever reported that it is not there.  Do you not see battery attributes in the info sensor for the camera?

**Comment by mac-n-cheese-uk** [comment]
Looking at one of the Stick Up Cameras in Home Assistant I see the following entities pulling through:

![image](https://user-images.githubusercontent.com/41066371/127558404-3e31f80b-bb1c-41f3-bb36-448a300a5dc8.png)

**Comment by tsightler** [comment]
There's not a separate entity, it should be part of the info sensor.  What do you see if you click the info sensor entity?

**Comment by mac-n-cheese-uk** [comment]
Clicking the info entity gives me this:

![image](https://user-images.githubusercontent.com/41066371/127561448-bacb52b7-4490-4f1d-8646-0aa0541f3d2a.png)

**Comment by mac-n-cheese-uk** [comment]
Strike that, I found it nestling away under the slider control in the top right 

![image](https://user-images.githubusercontent.com/41066371/127561736-2c7fac34-0269-4980-8ad2-fb50c46d9199.png)

**Comment by tsightler** [comment]
Yep, it's just an attribute of the info sensor.  Basically, the info sensor is a generic sensor with a bunch of different attributes that vary based on the device, but it's only possible to choose one attribute to be the primary value (the one that is graphed) for any given sensor.  I selected the wifi because the vast majority of Ring cameras are connected via Wifi, while lots of camera are not battery (for example, I own 7 Ring cameras and 5 of them are on Wifi, but zero are battery powered).

However, you can always create a template sensor to display the battery, and entity cards allow displaying attributes easily and you can create rules to monitor them easily as well so you should be able to do what you want with it.

**Comment by tsightler** [comment]
Closing since the battery level is reported in the info sensor, but I may consider making the battery resource the tracked resource for battery cameras as that probably makes more sense.
