### ISSUE TITLE
Feedback?

### ISSUE THREAD

**Issue by Grey-Lancaster** [tsightler/ring-mqtt#217]
Thanks for the names in the log, but could it carry forward to the end?  As well, was the 3rd pic supposed to be a link?

Thanks again for all your work !!

Grey
![ring5](https://user-images.githubusercontent.com/20055899/127754665-52e1a841-ddd7-4040-8ce2-67121a87947a.PNG)
![ring6](https://user-images.githubusercontent.com/20055899/127754670-b411cf44-55f5-47c1-aa7e-bdd4e61539f1.PNG)
![ring7](https://user-images.githubusercontent.com/20055899/127754681-651828ca-309c-4d1a-97b4-49b536f9aeb0.JPG)

**Comment by tsightler** [comment]
I'm sorry, but I don't understand what you're requesting.  What do you mean by "carry forward to the end"?

Not supposed to be a link, it's probably just worded poorly. It's just trying to say that you are able use the camera support in this addon in addition to the one in Home Assistant.

**Comment by Grey-Lancaster** [comment]
Once it is started and you look at the log, you cannot tell what devices they are like when it first boots up.

**Comment by tsightler** [comment]
I'll admit that the debug logging is not really intended to be easy to read for users, but to show exactly what is being sent via MQTT, because that's what is important for me when people report bugs/issues.  I don't really care about what devices are named and, in many cases, users have devices with identical/nearly identical names.  Until very recently I didn't even enable debug logging by default, except for the addon case.

Perhaps you can help me understand what issue you are having as to why you need debug logs to be user friendly?  Determining device IDs is pretty easy and needing to do so should be rare.

**Comment by Grey-Lancaster** [comment]
Like the other day when my lights were not working I could not tell if they were on the page at all.  I tried to match those numbers with things in the ring app with no luck.  I thought it used to because I saw my camera was not sending snapshots a ways back.

**Comment by tsightler** [comment]
I agree the IDs aren't easy to find on the iPhone/Andriod apps, but the IDs are generally easy to see in the URLs if you login to the web app.  Admittedly, I don't know about smart lighting since I don't own any Ring smart lighting devices. 

I do appreciate the feedback, and I'll keep it in mind in the future, but I'm not sure if I will change it or not.  Closing this for now.

**Comment by Grey-Lancaster** [comment]
Thanks for listening :-)

**Comment by tsightler** [comment]
Just one more quick question (maybe I closed a little to quickly), would just adding something as simple as this would be enough:

```
2021-08-01T18:09:55.141Z ring-mqtt Shop Floor: ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/alarm/a302187d-1e82-4364-bade-425672c96466/motion/state ON
2021-08-01T18:09:55.142Z ring-mqtt Shop Floor: ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/alarm/a302187d-1e82-4364-bade-425672c96466/info/state {"batteryLevel":100,"batteryStatus":"full","commStatus":"ok","firmwareStatus":"up-to-date","lastCommTime":"2021-08-01T18:09:55Z","lastUpdate":"2021-08-01T18:09:55Z","linkQuality":"ok","serialNumber":"BHMS11814EL016600","tamperStatus":"ok"}
```

**Comment by Grey-Lancaster** [comment]
Any little bit helps :-) That does not actually show what it is though, like motion detector or switch.  But that is great. If I get confused I should do a better job of naming them.

**Comment by tsightler** [comment]
The topics should mostly give it away, for example, the above clearly has "motion/state" in the topic.  Honestly, I'm really torn on this because one of the reasons for the earlier approach was that every state line, is identical in length, at least for devices of the same parent type (alarm, camera, lighting) which makes it easier for my eyes to parse when I filter for state events and need to look across a bunch of different devices.  Also, really long lines are difficult as well.

Maybe I can add a line before the state data which I can easily filter out.  Thanks again for the feedback.
