### ISSUE TITLE
After switching from email to text 2FA I get the following error

### ISSUE THREAD

**Issue by jackgithome** [tsightler/ring-mqtt#221]
I switched from email 2FA, which was working for over a year, to text last night.  Now, no matter how many times I have tried it, I get the following error.  Maybe I'm doing something wrong, but was hoping you could help.

-------------------------------------------------------
| Ring Device Integration via MQTT                    |
| Addon for Hass.io                                   |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt-hassio-addon |
-------------------------------------------------------
Node version v12.15.0
NPM version 6.13.4
git version 2.24.1
-------------------------------------------------------
Running "npm audit fix" to update packages with any vulnerabilities...
added 3 packages from 4 contributors, removed 4 packages, updated 24 packages and moved 1 package in 15.701s
7 packages are looking for funding
  run `npm fund` for details
fixed 23 of 29 vulnerabilities in 388 scanned packages
  2 vulnerabilities required manual review and could not be updated
  2 package updates for 4 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
-------------------------------------------------------
Running ring-mqtt.js version 3.0.1...
2021-08-06T03:41:38.388Z ring-mqtt Configuration file read from: /data/options
2021-08-06T03:41:38.887Z ring-mqtt Error: Request failed with status code 404
    at createError (/ring-mqtt/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/ring-mqtt/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/ring-mqtt/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
2021-08-06T03:41:38.889Z ring-mqtt Couldn't create the API instance. This could be because the Ring servers are down/unreachable
2021-08-06T03:41:38.890Z ring-mqtt or maybe the refreshToken is invalid. Please check settings and try again.
2021-08-06T03:41:38.892Z ring-mqtt Exit code: 2

**Comment by tsightler** [comment]
**`Running ring-mqtt.js version 3.0.1...`**

This is most likely the issue as v3.0.1 is probably 18 months old and is sorely out of date and not even published anymore.  Current release is 4.6.3 and at least 4.6.2 is likely required at this point since Ring made changes to their API in the interim including one recently that completely broke all prior versions.  Please update to the current version and try again.

**Comment by jackgithome** [comment]
Thanks for your quick reply.  I didn't realize I was running an old version.  For the life of me I cannot figure out how to update the version.  I had auto update on but that clearly didn't work.  I looked all around supervisor and clicked reload on the add-on page but again, nothing.  Do you have any idea how I'm supposed to manually update this?

**Comment by tsightler** [comment]
You might just try removing the repository from the addon store and adding the new one with the updated URL.  The URL you are currently using is out of date, although it does still work, but perhaps HA doesn't like the alias for some reason.  I'd suggest removing the existing repository and adding the new URL https://github.com/tsightler/ring-mqtt-ha-addon and see if it shows an upgrade.  I honestly have no idea.  I've had a few people that, for some reason got stuck on an earlier 4.x version and weren't getting update notifications, but nothing back to the 3.x versions.

Unfortunately, 3.0.1 is so old that it might not be possible to upgrade directly to 4.6.3.  Over the years I've tried to make the upgrades as seemless as possible, but there have been LOTS of change between 3.0.1 and 4.6.3 and I've never tested any upgrades from versions that far apart.  

Are you running current versions of Home Assistant?  You best bet may be to remove the addon completely, and reinstall, after adding the new repository URL.  I've tried to keep device IDs consistent across all versions so that removing and readding should not break existing entities, however, 3.x was even before the code had support for the HA device registry, so I just don't know what the result might be.

**Comment by jackgithome** [comment]
Thank you.  I had to delete the add on and then re-add it.  The good thing is all the entities remained so nothing had to be changed.  Thanks again!

**Comment by tsightler** [comment]
Thanks for reporting back and glad you got it working.  It's good to hear that the entities didn't change, that's the way it is supposed to work, but you never really know on untested situations like that.  Hopefully HA will provide update notifications going forward.
