### ISSUE TITLE
Chime 1st Gen not supported

### ISSUE THREAD

**Issue by timota** [tsightler/ring-mqtt#231]
In release version 4.7.0 it stated that chime devices now supported. Unfortunately Chime 1st Gen not discovered by script. 
```
hassio: 2021.8.6
addon: 4.7.1
```

**Debug Logs**
Unfortunately dont know how to start addon in debug mode. 

Thank you.

**Comment by tsightler** [comment]
Chime v1 devices should be supported, there's nothing really special about them, and there's no check in the code for any specific model, only that the device reports that it is of type chime, but indeed I don't own one, so it's possible something could be an issue.  That being said, more likely is that chime support is not working due to one of the following reasons:

1) Chimes are tied to cameras, so you have to enable camera support in the config for them to show up (see configuration documentation)
2) Only the primary Ring account has access to Chimes so if you are using any other account, Chimes won't appear.

Debug logs are enabled by default in the addon.  Please [follow the instructions](https://github.com/tsightler/ring-mqtt-ha-addon/blob/master/GET-LOGS.md) to get the logs as, without them, there is absolutely nothing that I can do but randomly guess at the problem.  While those instructions use command line you could also use a tool like the Portainer addon if you prefer.

**Comment by timota** [comment]
Hi, 
1. definitely my chime are tied to Ring bell. - but i have camera enabled in config.
2. "Only the primary Ring account has access to Chimes" - what do you mean under this ? Does it mean that i have to use my personal account and not account that dedicated to `ring-mqtt` ?

Thanks

**Comment by tsightler** [comment]
Yes, if you go to Settings...Shared Access in the Ring app, which is where you can assign access to your Ring devices to other users, you will see that Chimes are not listed there.  Even if you login to the Ring app with the dedicated account, you will not see the Chime there either.

Unfortunately, Ring doesn't have a way to have a second account that has full access to all devices, so the only option is to use the primary account for some functions like Chimes, Light groups, and base station volume control.

**Comment by timota** [comment]
yup, i see what you mean. Thank you for your help. Issue can be closed. 

btw: probably it will be a good idea to add this explanation to `readme`. it will stop users like me to ask stupid questions. 

Anyway, thank you.

**Comment by tsightler** [comment]
It's already been added to the docs in the lastest 4.7.2 release, which should be making its way to the masses over the weekend.  Thanks!
