### ISSUE TITLE
4.7.3 fatal error in, line 0 unreachable code

### ISSUE THREAD

**Issue by trashhalo** [tsightler/ring-mqtt#237]
### PLEASE READ THIS FIRST ###
If you are using the Ring Devices Addon for Home Assistant, and the issue you are reporting is related to installing, configuring or operating the script underneath that platform, you should probably not be opening an issue on this page, but rather on the Ring Devices Addon page:
https://github.com/tsightler/ring-mqtt-ha-addon

** Describe the bug **
```
pi@raspberrypi:~ $ docker run -it --rm --entrypoint /app/ring-mqtt/node_modules/ring-client-api/ring-auth-cli.js tsightler/ring-mqtt


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7effd22c
```
Linux raspberrypi 5.10.52-v7+ #1441 SMP Tue Aug 3 18:10:09 BST 2021 armv7l GNU/Linux

Downgrading to 4.7.2 fixes everything.

**Debug Logs**
To effectively troubleshoot the issue logs will generally be required.  Please run the script with DEBUG=ring-mqtt enabled and post any relevant output here.

**Comment by trashhalo** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/7662#issuecomment-853776170

I believe this to be the fix. Seems to be an issue with alpine 3.13

Confirmed alpine 3.13+ got introduced in this version.
https://github.com/tsightler/ring-mqtt/commit/bcb5e4ad3e59e403361bfb9475c11c565219e184#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

**Comment by tsightler** [comment]
I'm assuming you are running 32-bit Raspbian/Raspberry Pi OS?  If so, the "fix" is for Raspbian to actually release an update to address this, or for users to apply the fix from backports as noted in that thread, which is what I had done on my Raspbian install before I finally decided to just dump Raspbian completely.  Raspbian has had 8 months to get a fix out for this, something that is super easy to address and well known, and it's not just an issue with Alpine, the latest Ubuntu docker images also have the same problem because it's actually a base OS issue.

I could revert the image to the prior Alpine version, but Alpine 3.12 only has ~8 months of support lifetime remaining, and I have no confidence that Raspbian will address this issue by then so, IMO, people should be putting pressure on Raspbian (and any other OS vendors) to provide an updated docker/libseccomp2 package, or just install the backport and be done with it.

**Comment by tsightler** [comment]
Closing this as I'm not currently planning to revert to Alpine 3.12.  IMO, users should do one of the following:

A) Press their OS vendor for updates

B) Install the backported updates for their OS

C) Use a 64-bit OS

BTW, here's the bug filed on this with Raspbian back in January (no action to date:

https://bugs.launchpad.net/raspbian/+bug/1912858

Admittedly, I don't think it's been addressed in upstream Debian either, probably because it's not an issue for 64-bit users and I'd guess most straight Debian users are 64-bit.  I believe that Ubuntu 20.04 and newer have updates to address it though, and installing the updated libseccomp2 from buster-backports is pretty easy, low risk, and doesn't break the future update to bullseye.

**Comment by tsightler** [comment]
For completeness, here are the instructions for installing the updated libseccomp2 from buster-backports:

```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
$ sudo apt update
$ sudo apt install libseccomp2 -t buster-backports
```

Also, I actually didn't bump to Alpine 3.14 just for the heck of it, rather it made my development easier for some work I'm planning for the next major release of this addon where I'm hoping to include some basic livestream support (yes, something I never thought I would do).  I'm currently experimenting with a few approaches and the best one I found so far had some dependencies that were more easily satisfied in Alpine 3.14 since they were built-in.  Yes, I could work around it with some additional manual steps, but really, IMO, these OS fixes need to get out into the real world anyway.

However, I've recently started testing another approach which does not have such strict dependencies, and works fine on Alpine 3.12 with no special workarounds, so perhaps I would be able to revert again for the time being if this is really a huge issue for people.  As this is, so far, the only report of the issue, my current lean is to stay with Alpine 3.14 for now, especially since these Docker fixes will have to get out there over the next 6 months or so regardless.

**Comment by AdrianGarside** [comment]
I had to follow instructions here to fix an error importing the public keys at the first step above: https://bbs.archlinux.org/viewtopic.php?id=252494

**Comment by JoshuaSeidel** [comment]
@tsightler i get this error in your docker container, shouldnt matter the main OS version. issue would be within the container itself

**Comment by tsightler** [comment]
@JoshuaSeidel You can say the issue is not with the main OS version all you want, that doesn't make it true.  The issue is clearly with the OS as, if you update to the newer components, the container will work.  The issue is clearly documented and I even provided a link to the Raspbian bug report on the issue from January.   Here is a link to the Alpine release notes documenting the issue and the versions that are required:

https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

While Alpine didn't make this switch until January of this year, the fix was available two years ago, that's when the backported version of libseccomp2 was released.  The OS vendors have had **PLENTY** of time to address this issue and most have.  I will not be going back to Alpine 3.12.

**Comment by tsightler** [comment]
BTW, if you really don't want to install any updates to Docker to get this working, you can simply follow the other instructions in the readme which consist of:

1) Download the [default seccomp profile](https://github.com/moby/moby/raw/master/profiles/seccomp/default.json)
2) Use your favorite edition and on line two of the file replace SCMP_ACT_ERRNO with SCMP_ACT_TRACE and then save the file
3) Run docker with this new profile by adding --security-opt=seccomp=default.json to the run command like this:

`docker run -it --rm --security-opt=seccomp=default.json --entrypoint /app/ring-mqtt/node_modules/ring-client-api/ring-auth-cli.js tsightler/ring-mqtt`

Use the --security-opt=seccomp=default.json any time you run this container, both for acquiring the initial token, and for starting.

I still think it's better to update the outdated components, because then your system will be able to run all containers that depend on a properly functioning time64 system call (Alpine was one of the first to adopt, but was not the last, and more will do so over the coming months) but the above is a fully functional alternative that lets you run such containers now, while keeping the old components.

**Comment by pixeldrew** [comment]
Had the same issue and followed your guide to updating libseccomp2 and still had the issue, ended up having to upgrade docker entirely which then got it to work. Thanks for the hand in upgrading rasbian but will probably reimage this pi to a 64 bit ubuntu image for my own sanity.

**Comment by tsightler** [comment]
Yeah, the docker in stock Raspbian is so outdated at this point, but at least a bullseye based image can't be too far away now.  However, I've been super happy since moving on to Ubuntu 64-bit on my RPi.  I prefer Ubuntu simply because I use it a good bit as part of my day job so having that same familiar feeling on my RPis is nice and I feel like they are better at staying somewhat updated vs clinging to outdated/broken packages in the name of stability.

**Comment by Nils154** [comment]
Thanks, installing the updated libseccomp2 from buster-backports fixed it on my Pi2.
