### ISSUE TITLE
Interval Snapshot Mode Not Sending Snapshots

### ISSUE THREAD

**Issue by maddox** [tsightler/ring-mqtt#241]
## Bug
I have SNAPSHOTMODE set to interval. Upon bringing up ring-mqtt (via docker), an initial snapshot is sent over. But after that nothing is ever sent again. 

## Details

**ring-mqtt.js version**: 4.7.3
**Node version** v14.17.5
**NPM version** 6.14.14
**git version** 2.32.0

## Logs

I'm not sure exactly what log items to provide as the snapshots aren't actually happening, so there's no logging. I can say that I see logging of the snapshots happening on boot, but they never happen again.

**Comment by tsightler** [comment]
The log would still be useful and required to troubleshoot this issue since they will show the initial snapshot images as well as the settings for the device.  Could you try the the "all" setting and see if you get refreshed snapshots on interval?  Also, what value is shown in the snapshot interval setting (that could also be answered with the logs).

**Comment by maddox** [comment]
Here's a link to the log - https://gist.github.com/maddox/53a4855e02d3647ebda40cc33fdb0efc

**Comment by maddox** [comment]
I know this is crazy, but I'm seeing some wild things happening while restarting ring-mqtt in a docker container.

1. Startup can hang for a really long time
2. I'm seeing disruptions in my internet.

I mean, I know that #2 is completely crazy. But I was messing with this yesterday for a few hours span and saw internet disruptions. When I stopped, so did the disruptions. I started at it again this morning, and the disruptions started again.

Now, I realize that this could be a TOTAL coincidence, and obviously if #2 is unrelated it would cause #1, but it's still a little weird.

Here's a log of a sensor I have that pings `8.8.8.8`

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/260/131139906-efc441b4-9c49-411a-a265-faf5655b5038.png">

**Comment by maddox** [comment]
I can confirm that snapshots are being updated every 30s with the `all` setting.

**Comment by tsightler** [comment]
Yep, I see that there's a bug where the snapshot refresh code doesn't trigger the schedule if set to interval only.  Not sure when that was introduced but most likely snuck in with all the changes that came with 4.7.0.  I'll either push a 4.7.4 with the fixes in the next few days or you can try the dev branch, which is mostly focused on adding support for live streaming, but now also has what I believe will be the fix for this although I haven't tested it yet.

Not sure about your Internet issues, the addon shouldn't be pulling much data overall and, based on your logs, you'd don't have many devices on average.  It's basically just some REST calls to pull JSON data, significantly less data than a typical busy web page.  The snapshots are the biggest data elements and they are still pretty small if you compare it to the average number of images a web page.  I'm not saying it's not related, I'm just saying I don't see how it could be!

**Comment by maddox** [comment]
That's great!

Yeah, this internet thing is totally wild. It's bad cable at the beach at a second home, so who knows. Now that I've noticed the pattern, I'll keep an eye on it, but like you said....its NOT a lot of data, lol. Thanks!

**Comment by eugeneniemand** [comment]
I've been experiencing the same thing with mode set to Interval. With all it works with the default 30 seconds but I cant get it to override as per the docs I've tried `ring/<location_id>/camera/<device_id>/snapshot/interval` I also tried the following as this is where it is stored `ring/<location_id>/camera/<device_id>/snapshot_interval/state` it just seems to ignore all of this.

**Comment by tsightler** [comment]
> I've been experiencing the same thing with mode set to Interval. With all it works with the default 30 seconds but I cant get it to override as per the docs I've tried `ring/<location_id>/camera/<device_id>/snapshot/interval` I also tried the following as this is where it is stored `ring/<location_id>/camera/<device_id>/snapshot_interval/state` it just seems to ignore all of this.

As stated above there's a problem with the interval setting.  I will fix it in the next version which I hope to get done one day.  However, I'm not sure what docs you are reading (maybe old ones?).  I just looked in the TOPICS.md document and it clearly shows:

ring/<location_id>/camera/<device_id>/snapshot_interval/state   <-- Get snapshot refresh interval
ring/<location_id>/camera/<device_id>/snapshot_interval/command <-- Set snapshot refresh interval

This changed happened in 4.7.0 when the interval switched from being a control on the snapshot entity to being its own entity in HA.  I probably did miss it in the release notes but you can always just look at the discovery information (even if you are not using HA the discovery information is hugely useful).

**Comment by eugeneniemand** [comment]
@tsightler thanks I saw that but I was using a setting of 'all' and thought I can set it. I was looking at the readme in this section in the last paragraph https://github.com/tsightler/ring-mqtt#snapshot-options I've done a PR to update readme https://github.com/tsightler/ring-mqtt/pull/246

**Comment by tsightler** [comment]
@eugeneniemand Ah, got it, thanks.  I'll probably remove the reference to the topic completely as I'm trying to make TOPICS.md the definitive topic reference because otherwise mistakes like this creep in where I forget to change it in other places.  Honestly the docs have become far too big for a single page regardless and I probably need to split them up some anyway.  It's on my to-do list.  Thanks!

**Comment by tsightler** [comment]
4.8.0 has been release and should address this issue.

**Comment by maddox** [comment]
Confirmed fixed 👍
