### ISSUE TITLE
Issues with tamper status?

### ISSUE THREAD

**Issue by mfedderly** [tsightler/ring-mqtt#251]
** Describe the bug **

I'm not sure if this is a bug in ring-mqtt or my own setup, but I'm having trouble getting the tamper status to change in home assistant. I'm trying to figure out if this is a bug for everyone or just a setup issue for me.

Repro steps on my local setup:
1) pull open one of the contact sensor cases to cause a tamper
2) observe that the ring app sends me a tamper warning
3) observe that the HA state is still set to off

**Debug Logs**

```
2021-09-07T23:43:03.383Z ring-mqtt [Basement Window] ring/UUID/alarm/UUID2/info/state {"batteryLevel":100,"batteryStatus":"full","commStatus":"ok","firmwareStatus":"up-to-date","lastCommTime":"2021-09-07T23:38:15Z","lastUpdate":"2021-09-07T23:38:15Z","linkQuality":"ok","serialNumber":"SERIAL","tamperStatus":"tamper"}
```

// This addon has been absolutely incredible, I really appreciate all the work you've put in making this so excellent.

**Comment by tsightler** [comment]
@mfedderly Honestly, this looks like a bug.  Probably snuck in with the 4.7.0 changes so I'm surprised no one has noticed before.  I'll try to dig into it.  I expected I'd need a few minor updates with the major changes with 4.8.0 so I'll try to fix it for 4.8.1.

**Comment by tsightler** [comment]
Fix for this is in the dev branch, I somehow never updated the value template when I switched to the new method for these entities.  This will be released as part of 4.8.1 probably sometime in the next few days.  If you want to try it now you can switch to the dev branch temporarily using the branch config option, just set it to "dev" and it will pull in the latest dev branch on the next startup, which, right now, is pretty low risk as it's just a few minor fixes discovered since 4.8.0 was pushed yesterday.  You can always switch back by changing the config option back to "addon"

**Comment by mfedderly** [comment]
That seems to have fixed things, thanks for the quick turnaround!

**Comment by tsightler** [comment]
Pushed 4.8.1 tonight which includes the fix for this.
