### ISSUE TITLE
No issue, just thanks!

### ISSUE THREAD

**Issue by broyuken** [tsightler/ring-mqtt#252]
No issue here at all, I just want to say thank you so much for your hard work on this addon, I never thought I’d get live video with ring in HA but you’ve made it happen! This is now probably my most useful add on I have in HA. 

Edit: Do you have a donation link? I’d love to buy you a cup of coffee or two.

**Comment by tsightler** [comment]
>  I never thought I’d get live video with ring in HA but you’ve made it happen!

Well that makes two of us because I never thought it would happen either, it was only the power of other open source projects that really made it possible.

I don't have a donation link because, well, honestly, I work on this project for my own enjoyment/education so everything I manage to get working is a learning experience which I find rewarding in and of itself, the fact that other people manage to also find it useful is just a bonus.  I actually started this project for the sole purpose of becoming a little more knowledgeable of Javascript and, while I'm still no expert, I've definitely learned a ton.

Also, I'm fortunate to have a great job that pays and treats me well, so I don't really feel like taking donations is the right thing to do as not everyone is so lucky.  I simply suggest that, if anyone feels like donating to the project, they should instead find some organization/cause/person that they know that could use it more, and donate there directly instead because that's probably what I would do with any donation anyway.  But of course no obligation.

Thanks for the appreciation though!
