### ISSUE TITLE
Live view 8 second lag

### ISSUE THREAD

**Issue by broyuken** [tsightler/ring-mqtt#254]
Just curious, but I’ve noticed that my live view is about 8 seconds behind when viewed through HA. If I view it through an echo show with the ring skill or through the ring app the delay is maybe 1 second. Is this expected because of the way you had to get this working or is there something possibly incorrect with my setup?

**Comment by tsightler** [comment]
I feel like this question covered pretty well in the FAQ portion of the [camera documentation](https://github.com/tsightler/ring-mqtt/blob/main/docs/CAMERAS.md#faq).  TL;DR, you can mostly blame the Home Assistant steaming framework which is responsible for 5-6 seconds of delay in most cases.  If you view the stream with a client capable of native playback of an RTSP stream, such as using the WebRTC card addon or using a medial player like VLC, the delay will be a lot less, usually 1-2 seconds at most, but varies a little based on CPU performance.  I hope to cut 1-2 seconds off with the next version due to some minor enhancements recently released in rtsp-streaming-server, but I can't do anything about the delay from the HA stream platform.

And when I say blame HA, I want to be clear, it's not even really their fault either, so I don't mean to literally blame them, it's just a limitation of the technology used there, but there were good reasons to choose it.  Home Assistant basically converts the stream from RTSP to HLS on the fly, and, while HLS is super compatible with browsers and works great because it's 100% based on HTTP/HTTPS, it's downside is latency.  To keep CPU usage minimal since HA commonly runs on pretty low-end devices they couldn't really chose to transcode the stream so instead it basically just chops the existing AVC stream at each IFRAME into an HLS segment, and the stream from Ring only has one IFRAME every 2 seconds.  HA is hardcoded to buffer 3 such segments to avoid stutter so there's your ~5-6 seconds right there.  Add that on top of any existing stream delay and you can easily see 6-8 seconds of delay, or more.

In the addon I considered using MJPEG for the output video stream, but the cost is much higher CPU usage due to having to decode and re-encode the stream, and much higher bandwidth, and you lose audio.  Just doesn't seem worth it.  For people that have the CPU available they can always use the FFMPEG component or do whatever they want with the RTSP stream.

You can read a lot of gory details about the Home Assistant camera platforms [in this post](https://community.home-assistant.io/t/i-tried-all-the-camera-platforms-so-you-dont-have-to/222999), but the one thing that is clear is that anything that uses the built-in stream component has high latency (in that article they talk about 13 seconds, which is crazy high, at least HA has improved that a little over the last year).

I personally use the WebRTC card, it works great and for me has 1-2 seconds of delay, usually closer to 1 and is pretty easy to setup as you can use either the RTSP URL directly, or the existing camera entity.  If you use the RTSP URL directly you don't even have to mess with the HA configs to add the generic cameras.  There are some other great addons that support RTSP as well, like Motioneye, but they typically expect the stream to stay alive 100% of the time so that's not great for Ring cameras where the stream is not local but always through Ring servers.

**Comment by broyuken** [comment]
well said, thank you! It's not a big issue for me, and I'll gladly take the delay if it means I can get "live" streaming in HA. Just wanted to make sure it wasn't just me.
