### ISSUE TITLE
Capture snapshot on buttonpress [Enhancement]

### ISSUE THREAD

**Issue by oramirite** [tsightler/ring-mqtt#257]
I don't really like relying on motion events on my Doorbell camera, as it pretty much captures everything happening on my street and I have a second camera higher up that points down at my front door for a much better view.

With this in mind, I'm trying to configure my Ring doorbell as more of a stick-up cam experience, and one of the things I wanted to do was have the snapshot activate when the button is pressed. this would allow me to have a low-bandwidth view that's actually useful, as well as a thumbnail to put in notifications that SHOULD always show who is at the door pretty clearly. When I livestream the camera through a card, this image would also be nice to have as the "poster" image so I can see who was at the door before the live view loads.

As a secondary option, it could be nice to get a service to call the snapshot function directly, therefore letting us automate this on our own.

Thanks for the wonderful plugin!!

**Comment by tsightler** [comment]
I've had several request for on-demand snapshots but it just feels like a slippery slope of un-supportability to me.  Snapshots on Ring cameras already have so many limitations and, if there's a button, people will definitely expect it to work, but, based on their settings, they may sometimes (or in some cases even always) get cached snapshots or it may not work at all.

I'm not sure what you mean by a "service to call", do you mean an HA service?  I'm not sure if it's possible to register a service with HA via MQTT, I thought only integrations could do that.

**Comment by tsightler** [comment]
One idea I've had is to provide a new snapshot mode option called "demand" that only provides on-demand snapshot capabilities and disables all the interval and motion snapshot capabilities.  This would be pretty easy to implement but the biggest problem is that snapshot mode is a global option and I know exactly what will happen next, people will want either demand mode on some cameras and motion/interval mode on others.

What really needs to happen is that these modes need to be configurable dynamically per-camera, but then I need to save the state of these configs so that they can be restored on a restart.  To be fair, that was alway the plan for the ring-state file anyway, not just to store the token but to also store persistent, per-device configuration state as well, so that, on restart, this data would be available.  I really need to implement this for a multitude of reasons, including some future features I have planned, but the current code isn't well setup for this and it requires ripping apart portions of the code which are ugly and yet have been working for years.

Because of this, I'm going to close this issue for now.  If I ever get around to implementing saving device configuration state, then I'll reconsider this feature.
