### ISSUE TITLE
All Ring devices showing as unavailable

### ISSUE THREAD

**Issue by caraar12345** [tsightler/ring-mqtt#258]
### Describe the bug

My two devices, a Stick-Up Cam and a Video Doorbell 2, load in when HA/`ring-mqtt` are started, but then they show up as `Unavailable` forever after.

<img width="898" alt="Screenshot 2021-09-10 at 15 52 20" src="https://user-images.githubusercontent.com/6129428/132873533-09f0a1a4-a3af-46f6-b153-a4c32ec5c29d.png">

### Debug Logs
To effectively troubleshoot the issue logs will generally be required.  Please run the script with DEBUG=ring-mqtt enabled and post any relevant output here.

I uploaded the log file to my website: https://aaroncarson.co.uk/assets/files/ring.log
I recommend you access it via `curl https://aaroncarson.co.uk/assets/files/ring.log` because it contains the colour terminal codes and looks very strange in a normal text editor 😁
I wasn't able to enable `DEBUG=ring-mqtt` as I'm using the HA Supervisor add-on however -- please let me know if there's anything else you need! I also changed the Ring device IDs to `GARAGE_ID` and `FRONTDOOR_ID`, and also masked the RTSP credentials.

**Comment by tsightler** [comment]
I use an editor that interprets the ANSI colors because it makes parsing the logs way easier with color (that's the main reason colors are even there) so no issues there.  The addon already has DEBUG enabled, that's the very logs you sent, so it's all good.

Unfortunately, after looking at those logs, I have no clue as to the problem as the logs look perfect.  Does it happen even if you restart or refresh the browser?  Do you have any errors in the logs on the HA side?

Just for some details, when I look at the logs I see all of the discovery messages, which clearly worked, so that's perfect.  The very first two lines after that, 2 seconds after discovery completes, are the messages to set the devices online, which match the availability topic messages in the discovery.  After that, it's just normal state updates and the normal rediscovery cycle that happens during startup.

Based on that, I'd have to assume either an MQTT or HA problem, not a problem with the addon.  Do you have anything unusual setup for the Mosquitto addon, like some security settings that would restrict HA from being able to see the ring/ topics but that allow it to see the homeassistant/ topics?  Can you connect to the MQTT broker with a tool like MQTT Explorer or even mosquitto_sub and see if the ring/ topic messages are getting through?

**Comment by caraar12345** [comment]
_Oh there are `ring` topics?_

That was it. The MQTT user that the addon was using only had access to write to `homeassistant/`.

Everything works now, thaaaaanks 🤦‍♂️

FWIW this is a billion times better than the official HA Ring addon so thanks for that too 😁  have a lovely weekend!!
