### ISSUE TITLE
Potential issue with discovery

### ISSUE THREAD

**Issue by green-arrow** [tsightler/ring-mqtt#26]
I'm using Mosquitto and the auto-discovery for home assistant. It looks like the entities are picked up, but on the integrations page, when selecting "MQTT", I see a page that says "Entities without devices" that lists all my ring sensors. Is that correct or is there an extra step I need to take to associate them to a device?

![image](https://user-images.githubusercontent.com/2180127/62805597-7c17d500-babe-11e9-899b-211b8e6bbc76.png)

**Comment by tsightler** [comment]
There's nothing to do, and everything is working as expected.  The script doesn't currently send any device info as part of the auto discovery, although it is something on my to-do list so I would consider it more of an enhancement request than an actual issue.

Basically, device info is a way to identify the physical device and associate it with it's available entities, so, for example, if a single physical device has two sensors, like the freeze/flood sensor, I could send device info and Home Assistant would recognize it as a single device with two sensors vs right now where it just recognizes it as two separate entities.  From a functional perspective, it doesn't change a whole lot, although it might make the GUI categorize devices/entities a little more clearly without as much manual effort.

In your case each of our physical devices only have a single entity anyway, so it really would make no practical difference.  I guess I could potentially expose the battery and tamper sensors as separate entities on the same device instead of including them as json attributes, but I think that would mostly just clutter up the interface.

**Comment by green-arrow** [comment]
@tsightler - thanks for the explanation about devices! I'm still new to HA and really appreciate it 😄
