### ISSUE TITLE
Livestream paths are not being posted to rtsp-simple-server

### ISSUE THREAD

**Issue by bsleep** [tsightler/ring-mqtt#266]
**Describe the bug**  
I've been trying to get the new live stream working, but I'm noticing that the paths are not being posted to rtsp-simple-server when the ring-mqtt service is started. I've looked over the code and can run the pieces manually to get a livestream up, just not sure why it won't automatically populate.

**Describe your environment**  
I'm running Home Assistant in a virtual environment, so ring-mqtt is installed manually by pulling the lastest release, extracting, and running npm install. Configuration is done through config.json. OS is Ubuntu 20.04.3 LTS.

**Describe your settings and what you've tried**  
contents of config.json:
`{
    "host": "localhost",
    "port": 1883,
    "ring_topic": "ring",
    "hass_topic": "homeassistant/status",
    "mqtt_user": "<redacted>",
    "mqtt_pass": "<redacted>",
    "livestream_user": "<redacted>",
    "livestream_pass": "<redacted>",
    "ring_token": "<redacted>",
    "enable_cameras": true,
    "enable_modes": true,
    "enable_panic": false,
    "location_ids": [
        ""
    ],
    "snapshot_mode": "motion",
    "beams_duration": 0,
    "disarm_code": ""
}`

I've been able to manually post to the rtsp-simple-server API using curl and get a path configured that works. Here's the json output from http://localhost:8880/v1/paths/list when I use curl to set the path manually:

`{
  "items": {
    "<redacted>_live": {
      "confName": "<redacted>_live",
      "conf": {
        "source": "publisher",
        "sourceProtocol": "",
        "sourceAnyPortEnable": false,
        "sourceFingerprint": "",
        "sourceOnDemand": false,
        "sourceOnDemandStartTimeout": 10000000000,
        "sourceOnDemandCloseAfter": 10000000000,
        "sourceRedirect": "",
        "disablePublisherOverride": false,
        "fallback": "",
        "publishUser": "<redacted>",
        "publishPass": "<redacted>",
        "publishIPs": null,
        "readUser": "<redacted>",
        "readPass": "<redacted>,
        "readIPs": null,
        "runOnInit": "",
        "runOnInitRestart": false,
        "runOnDemand": "`./scripts/start-stream.sh <redacted>_live Back_Doorbell <path>/<to>/<camera>/stream/attributes <path>/<to>/<camera>/stream/command`",
        "runOnDemandRestart": false,
        "runOnDemandStartTimeout": 10000000000,
        "runOnDemandCloseAfter": 10000000000,
        "runOnPublish": "",
        "runOnPublishRestart": false,
        "runOnRead": "",
        "runOnReadRestart": false
      },
      "source": null,
      "sourceReady": false,
      "readers": []
    }
  }
}`

When I restart ring-mqtt.service, no paths will be set until I click on the camera in the picture-glance card. At that point, there will be a path set, but none of the settings beyond the name are set. Here's the json output from http://localhost:8880/v1/paths/list when I click the camera in the picture-glance card:

`{
  "items": {
    "<redacted>_live": {
      "confName": "~^.*$",
      "conf": {
        "source": "publisher",
        "sourceProtocol": "",
        "sourceAnyPortEnable": false,
        "sourceFingerprint": "",
        "sourceOnDemand": false,
        "sourceOnDemandStartTimeout": 10000000000,
        "sourceOnDemandCloseAfter": 10000000000,
        "sourceRedirect": "",
        "disablePublisherOverride": false,
        "fallback": "",
        "publishUser": "",
        "publishPass": "",
        "publishIPs": null,
        "readUser": "",
        "readPass": "",
        "readIPs": null,
        "runOnInit": "",
        "runOnInitRestart": false,
        "runOnDemand": "",
        "runOnDemandRestart": false,
        "runOnDemandStartTimeout": 10000000000,
        "runOnDemandCloseAfter": 10000000000,
        "runOnPublish": "",
        "runOnPublishRestart": false,
        "runOnRead": "",
        "runOnReadRestart": false
      },
      "source": null,
      "sourceReady": false,
      "readers": []
    }
  }
}`

**Debug Logs**  
I have the DEBUG environment variable set in my systemd unit file and am writing contents to a log file. I'll send the logs to your email for investigation.

If there's anything else I can provide. Please let me know. I'll try to get it to you in a timely manner.

**Comment by tsightler** [comment]
What version of node?  As noted in the section on standard install, Node >= 14.17.0 is a hard requirement.  I'm assuming this is the reason as you'll get exactly this behavior, because the code depends on the "spawn" event being emitted to know that rtsp-simple-server has successfully spawned and that event was not included in Node until 14.17.0.  If you're on an older version you'll end up with a spawned process, but because there's no spawn event on those versions no paths will ever get created.

**Comment by tsightler** [comment]
BTW, I guess the note about requiring 14.17.0 was only added about a week ago, so if you started messing with this before that, it might not have been in there.  When I wrote this code I didn't realize that the spawn event was such a recent add to the node feature set as it seems like a pretty basic feature, but I don't think I'm going to back it out at this point since 99% of users already leverage the addon or docker installs.  Honestly, I'll probably deprecate standard installs when I finally decide to rev to 5.x as I really don't see the advantage of keeping them around.

**Comment by bsleep** [comment]
Yep, totally my fault. Didn't see the note about requiring 14.17.0. I just updated node and everything is working as expected. Thank you for your help.

> Honestly, I'll probably deprecate standard installs when I finally decide to rev to 5.x as I really don't see the advantage of keeping them around.

I'll hate to see standard installs go, but I completely understand. I just prefer to use a standard install over the docker environments, but I realize I'm in the minority these days. Appreciate the help, and thanks for this integration. It's the best ring integration for home assistant by far.

**Comment by tsightler** [comment]
Yeah, I resisted Docker for a long time because I preferred standard installs, but even I've finally cut pretty much everything over to Docker about 9 months ago.  And now, the burden of support has shifted it the other way, only a tiny percentage of users leverage the standard install, but since 4.8.x was released, those users have accounted for nearly 50% of the time I've spent on support, mainly due to the fact that there are now dependencies on node version, rtsp-simple-server, mosquitto clients, etc.  Docker and addon users don't have those problems.  There's also some added code complexity due to the differences in how tokens are managed, but I guess I could just standardize that across install methods.

I don't think 5.x is right around the corner though, while a lot of the code is ugly because I had no idea what I was doing when I started, it's reliable and quite proven at this point so the motivation to re-write it is low, other than the fact that I think I could do so much better if I started over now.  And it's not like I can stop people from installing it manually, probably I'll just move the docs to a separate file, try to keep the dependencies updates, and tag it as deprecated.

**Comment by sktaylortrash** [comment]
I'll say this you may have more standard install users than you think. It's possible that most just don't bug you for help. I personally would hate to see the standard install go away.

**Comment by tsightler** [comment]
If they don't bug me today then they can certainly figure out how to manually install without me having to give them instructions, I mean, there's nothing magical about it and a Dockerfile is basically nothing more than a scripted install, so it's all the instructions you need if you really want to do a standard install.  The "standard install" is basically just a set of instructions so regardless of whether it is "supported" it will always be possible.  If they already aren't bugging me then they'll just continue to install it themselves and not bug me, but when I say it's supported then people still expect me to support them when they try to get it to run on their toaster.
