### ISSUE TITLE
ChannelStateTransformation error in combination with openHAB

### ISSUE THREAD

**Issue by arjan-io** [tsightler/ring-mqtt#268]
Using ring-mqtt version 4.8.3 in a docker container, I have the topics being fed/picked up by [openHAB](www.openhab.org). In the logs I get the following error(s):
```
2021-09-21 19:25:23.579 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. Argument named 'default_value' is required but missing for filter default
2021-09-21 19:25:23.579 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. Argument named 'default_value' is required but missing for filter default
2021-09-21 19:25:23.592 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. Argument named 'default_value' is required but missing for filter default
2021-09-21 19:25:23.593 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. Argument named 'default_value' is required but missing for filter default
2021-09-21 19:25:23.595 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. Argument named 'default_value' is required but missing for filter default
```
At the same time, MQTT published the following:
```
[]({"wirelessNetwork":"XXXX","wirelessSignal":-45,"firmwareStatus":"Up to Date","lastUpdate":"2021-09-21T14:52:35Z"}
{"wirelessNetwork":"XXXXX","wirelessSignal":-45}
{"batteryLevel":"63","firmwareStatus":"Up to Date","lastUpdate":"2021-09-21T16:23:59Z","wirelessNetwork":"XXXXX","wirelessSignal":-57,"stream_Source":"rtsp://localhost:8554/XXXXXX_live","still_Image_URL":"https://localhost:8123{{ states.camera.voordeur_snapshot.attributes.entity_picture }}"}
{"wirelessNetwork":"XXXXX","wirelessSignal":-57}
{"batteryLevel":"63"})
```
This has been going on since I upgraded to 4.8.3. Previously, in version 4.6.x I had no issues. Never used version 4.7.x so could not comment on that. Both cases I ran openHAB in version 3.1.0 (stable) and same docker version. MQTT-States are reported every 5 mins, so are the errors.

The states still arrive in my openHAB items however and commands are being sent. Though it seems that the code is not entirely clean. Running openHAB with a clean log is much nicer and quicker to filter out any (real) issues.

**Comment by tsightler** [comment]
Interesting issue, but I'm not sure what I can do about it.  At first glance I would interpret it as an openHAB issue because it's trying to perform a transformation on the JINJA2 template that it is inside of the JSON attribute values.  Unfortunately I don't know much about openHAB, but I have no idea why it would attempt to interpret a template inside of a JSON value like this.  Home Assistant uses Jinja for templating, and it appears that OpenHAB implemented limited support for Jinja as part of their Home Assistant discovery compatibility, but this isn't a discovery message so I have no idea what it is complaining about.  From a person who knows mostly nothing about OpenHAB, the error message is largely non-sensical.

I suppose there might be some way to escape it or get OpenHAB to otherwise ignore it, but as I have no OpenHAB knowledge myself, I'm not sure what can be done.  I'd suggest asking someone that actually knows something about OpenHAB.  I'm not unwilling to make changes here to try to make it more compatible with OpenHAB, but I'd need to know what those changes would need to be.

As an alternative you could probably just use ACLs on the mosquitto client to keep the messages from getting the the OpenHAB instance.

**Comment by tsightler** [comment]
Actually, thinking about this problem some more, you could probably just not use the automatic discovery and just manually configure your things and channels (I think that's what openHAB calls stuff).

**Comment by arjan-io** [comment]
Thank you for your response.

About your first post: I am not sure either. When I used version 4.6.x, it was complaining about JINJA as well but the I discovered I had to 'install' it within openHAB and ever since, all was running smoothly. The 'problem' arose when I upgraded to 4.8.x so hence I thought it might be something in the code since my OH-version stayed the same, as well as any other variable.

About your second post: That's indeed what it is called and I used the manual things already. I'll see if I can remove/mute the HA things, to see if that makes a difference.

**Comment by tsightler** [comment]
The streaming support is of course new in 4.8.x, so I doubt it would have complained about the streaming URL template in that case.  But it's literally just a new attribute, nothing really has changed.  However, I wonder if I'm wrong about the actual cause of the error. 

Because it was talking about JINJA, I assumed it was attempting to transform the actual template value within the JSON attributes, but, looking more deeply at the timing info in your logs, it appears that you might be getting this message for every single attribute based entity, which actually does using a Jinja template to extract the value from the json attributes topic.

This change was actually introduced in 4.7, which is when the battery and tamper sensors were split out into their own entities rather than only being attributes of the information sensor, but the way it actually works in Home Assistant is that the entity uses a Jinja template to extract the value from the json string, and now I'm thinking that is what is failing in openHAB as that matches the symptoms more closely.

It would be interesting to know for sure if these errors definitely occur on 4.7.3.  I now think they almost certainly do, but if you could test and let me know for sure, that would help.  Admittedly, I'm still not sure I know what I could do about it as it's still an openHAB problem from my perspective, but it at least narrows the issue down a little bit.

**Comment by arjan-io** [comment]
Ok, so it turns out that _not_ using auto-discovered things like `mqtt:homeassistant_XXX` is the key here. I have now disabled those things and no log errors as such anymore.

**Comment by arjan-io** [comment]
I reopened as I saw your post after I typed mine and continued checking my log files.

This will be something for Thursday at the earliest but I'll give it a try and install 4.7.3. Would you figure that 4.7.2 would _not_ generate the error because that was still 'old' format?

**Comment by tsightler** [comment]
No, I'd expect that any version starting with 4.7.0 would have the issue, I just said 4.7.3 because it was the last maintenance version of the 4.7 line and the last version before streaming support was added, which added a lot of additional attributes.  I have a working theory as to the cause of the issue which I'll outline below:

In 4.7.0 changes were implemented that were required due templating changes introduced in [Home Assistant 2012.4](https://www.home-assistant.io/blog/2021/04/07/release-20214/#warnings-for-undefined-variables-in-templates). 

Basically, for as long as HA has existed you could just define a template with any variable like and HA would just accept it and just silently return null if the value didn't exist, which was honestly fine IMO.  But the powers that be imagined that this was somehow a problem and decided that having a template with a non-existent variable should be an error.

Of course, in the case of auto discovery, you have to send the device with the template BEFORE you send state with the actual values, so the template variable is ALWAYS defined before the value exists in the dictionary.  Never fear though, the Home Assistant folks have the perfect answer (technically I guess it's the Jinja folks that have this isn't it's just a basic feature there), if you explicitly want it to be OK that a value doesn't exist, then you must now define a default value, which can be null or other value, to be returned when the variable doesn't exist.  Don't do this and you'll get an ugly warning message in the log (and it HA 2021.10 and later, it will become an error).

This meant I had to modify the discovery templates for every device that used a json value template to extract the value from a json string to also provide a "default" null value when the value state didn't exist yet so, for example, an info sensor would have changed from:
`value_template: '{{value_json["commStatus"] }}'`
to
`value_template: '{{value_json["commStatus"] | default }}'`

If I think about your message from openHAB above it says:

`Argument named 'default_value' is required but missing for filter default`

Clearly that seems to indicate that it's treating the word "default" as a filter but tripping over the fact that there's no argument/value, but, at least according to my read of the HA document, that's what you want if you just want a null value.  It's possible I'm interpreting the HA documentation too literally though, maybe I should always include default(null) or default('') or something like that.  Or it may be that openHABs Jinja implementation needs to be updated to accept default with no value.   Not really sure honestly, I just implemented it in HA exactly the way it said in the docs and HA doesn't seem to have a problem with that.

**Comment by tsightler** [comment]
And indeed, if I look at the [Jinja specification for the default filter](https://jinja.palletsprojects.com/en/3.0.x/templates/?highlight=default#jinja-filters.default), it would appear to imply that it should always be a value, so maybe if I just changed default to default('') that would be good enough to suppress this.  I'll throw that change into the dev branch tonight and make sure it doesn't break anything on the HA side.  Let me know if you're willing to try it (you can just use the BRANCH feature to test the dev code with your existing docker so super easy)

**Comment by tsightler** [comment]
OK, I pushed an update to the dev branch that changes the value template default filter to use `| default("")` instead of `| default`.  Maybe that will satisfy OpenHAB's JINJA implementation since it's more conformant to the core JINJA specification and it doesn't seem to have any negative impact on Home Assistant.

The easiest way to test the dev branch is to use the branch feature of the addon.  Simply add the BRANCH=dev environment variable to your Docker run command and the container will pull down the latest dev branch on startup.  It should show version 4.8.4 on the banner.  You can revert to the standard version by simply re-running the container without the BRANCH environment variable.

**Comment by arjan-io** [comment]
It's under review. Will report back

**Comment by arjan-io** [comment]
So, installed the dev-branch (docker is indeed very easy in this!). Also placed back the auto discovered `mqtt:homeassistant` Things in my openHAB configuration. It has been running for over an hour now without any errors in the log. I think this issue is fixed and therefore closed.

Thank you for taking the time to look into this issue and come up with a fix.

**Comment by tsightler** [comment]
Thanks @arjan-io for testing and for bringing the issue up and providing good logs, in the process I learned a little more about Jinja.  I have a bug fix release pending that addresses an issue with event streaming so I'll roll this in as part of the 4.8.4 release and hopefully get that out in the next couple of days, or sooner if I somehow end up with additional time.
