### ISSUE TITLE
Future request: Snooze time remaining

### ISSUE THREAD

**Issue by arjan-io** [tsightler/ring-mqtt#269]
I have noticed in the Ring-app (iOS) there is a value that represents the remaining snooze time. Would such channel be available to pass to MQTT? Value is in XX hours and XX minutes format but I won't be surprised if it is only minutes 'under the hood' as so is the value to set the snooze timer. Photo for support (Dutch language).
![IMG_7932](https://user-images.githubusercontent.com/31731087/134320296-eae96288-7067-459e-b048-eed57533d3f4.jpg)

**Comment by tsightler** [comment]
Hi @arjan-io.  Currently remaining snooze time is not available although I'm not surprised that someone finally asked about it.  I actually had considered implementing it when I was writing chime support but I wasn't really sure it would be useful from an automation perspective.  It's hard for me to believe you would do something different automation wise based on whether the chime has X seconds left or not.

There are also some challenges in the details of implementation.  The value itself is in seconds, but I don't think it makes much sense to update the MQTT value every second.  Although that would probably be the most accurate representation, it feels like a lot of data updates and it also puts the burden of tracking the time on the application, since the data is only updated on polling, which is every 20 seconds.

I could easily do seconds remaining, updated every 20 seconds.  This is by far the easiest option to code, but that means the displayed time remaining is inaccurate 33% of the time since it would only be correct immediately after update.

The third option is to do something similar to the Ring app and display the time remaining in minutes.  This helps cover up the fact that the time isn't exactly accurate, but what would you do, for example, during the last minute or the last 30 seconds, should it display 0 minutes remaining, or 1 minute, neither of which would be very accurate and one of which would be super confusing.

Since I couldn't figure out an option that seemed to be both easy and ideal, and I couldn't even figure out what the use case would be from an automation perspective, I figured I'd wait until someone actually asked for this feature and then they could describe the use case and that would help inform what implementation method would be best so, feel free to share your thoughts here.

**Comment by tsightler** [comment]
BTW, to me the most logical solution is actually to display minutes remaining, and simple round the minute up/down.  This is because the snooze_duration setting is in minutes so I think it makes sense to match the time scale of snooze_duration to snooze_remaining.  If the snooze_remaining is "0" minutes but snooze is still active, then that would indicate it will go inactive sometime in the next 30 seconds or so.

This is easy to implement and doesn't overwhelm with data updates, and seems to fit best since it keeps the time scale the same as both the snooze_duration and the Ring app.  If you think this approach is good I can code it up for the 4.8.4 release.

**Comment by arjan-io** [comment]
@tsightler I see your point in 'what would you do automation wise if you have eg. 1 minute remaining'. I do struggle myself to find an actual _use_ case. I was thinking more in the direction of _informative_. To display how long the snooze is left so you could know at any specific time wether to reset it or not.
The update with every 20 seconds and rounding to the nearest minute would be for me personally a good compromise, though I am far from the only user.
If you want things to be uniform then present it as in the app. So 1-60 seconds is one minute, 61-120 seconds is two minutes etc.

**Comment by tsightler** [comment]
> I was thinking more in the direction of informative

Thanks @arjan-io.  This is a good point and one that I probably undervalue as I don't really use the dashboards of my home automation products as, for me, home automation is 99% (maybe 99.999%) the automation part.  I don't really care to view the status of things, unless I'm troubleshooting something, so the UI of these platforms are mostly wasted on me, I just want my stuff to work all the time, automatically, without me every having to think about it.  I started this project because I was frustrated that I could not trigger automations with my Ring devices easily, not because I wanted to consolidate Ring features in a UI with a bunch of other stuff.

But of course, as you correctly point out, that's really my own bias and certainly not how everyone thinks about and uses home automation.  Many do like the consolidate the view of everything in one place, so providing information is just as important as automation.

I just checked the Ring Android app and I think I can just pick any method and it won't be worse than what it does.  If I set it to "2 minutes" it immediately shows "Chime Alerts are snoozed: 1 minute remaining" and, during the last minute it says "Chime Alerts are snoozed: remaining." which is nonsensical, I mean, they could at least show <1 minute remaining or something.  Clearly I've spent more time thinking about it than they did for the app so I'm just going to implement it using minutes with a simple rounding up/down as that's easy to do and seems reasonable.

I'll try to code it up tonight and, if it goes well, push it out as part of 4.8.4.  Maybe I'll even manage to get 4.8.4 out the door tonight.

**Comment by arjan-io** [comment]
Ring has decided that, in iOS, anything <2 minutes should state 1 minute remaining ^_^
I fully agree that they could have given it a little more thought ;)

Don't rush for me. This is all done on voluntary basis so whenever there is time, there is time.

**Comment by tsightler** [comment]
In thinking about this, I believe there is a better option.  Rather than adding an entity, which really isn't the correct thing to do anyway since snooze duration is not an entity itself but rather an attribute of the "snooze" function, I should add a "seconds_remaining" attribute to the existing snooze switch entity and then just update it on each polling cycle (every 20 seconds).  That way it wouldn't be so bad that it doesn't match "minutes" since it's just an attribute that clearly says it's in seconds, and it would provide the most accurate information and if somebody really wanted to know the exact time they could use the "last_updated" attribute to calculate it.  For example, if the "snooze_remaining" attribute is 20 seconds, and the value was last_updated was 15 seconds ago, then clearly there are 5 seconds remaining.

This feels like the correct thing to do because the duration is not an entity itself, but is an attribute of the snooze switch entity. 
 Admittedly, I have no idea how well openHAB deals with json attribute values, but I assume it has to deal with them well since so many devices use json for their responses.  For Home Assistant you can easily display or trigger automations from attributes almost as easily as the primary entity state.

**Comment by arjan-io** [comment]
I am for sure no great coder but do know a thing or two. It sounds right to make the remainder an attribute rather than an entity. Like you pointed out, it is part of that snooze function thus part of the entity `snooze`.

Seconds or minutes is imho just as useful. What are the chances that someone does trigger an event based on 30 seconds remaining. I for sure can't think of a use case. Like I said, it's more informative so 30s or <1 min, who cares.

What you describe though is most likely the easiest to avoid any future request about precision. Don't know what Ring has to offer you when you get the info. If you get it presented in seconds/minutes...

About json and openHAB, there is a [json transformation service](https://www.openhab.org/addons/transformations/jsonpath/) to correctly display an Item. Most of this kind addons (like ring-mqtt) are in the format of [bindings](https://www.openhab.org/docs/developer/bindings/thing-xml.html#binding-definitions) and I would like to think that any transformation is done in there and as easily presented to the user as possible. In this case I would imagine the binding would take care about the json and calculation in between "last_update" and "lapse since" to present the info as 'time remaining' to the user.

**Comment by tsightler** [comment]
From ring it's a data attribute in seconds.  What I usually do is expose those attributes directly in the json attributes topics, although sometimes with slightly different names since the names Ring uses doesn't always make much sense to a user.  For example, this value from the Ring API json is `data.do_not_disturb.seconds_left`, but it's called snooze in the Ring app so I'd likely call it "snooze_seconds_remaining" or "snooze_seconds_left", or maybe just "seconds_remaining" since it's already an attribute of snooze, which makes including snooze in the attribute name redundant.

Actually, this value is the only thing that indicates if the devices is snoozed or not.  The way the current "switch" operates is basically just a simple if `data.do_not_disturb.seconds_left > 0` then switch is ON, otherwise OFF.  So all I really have to do is publish the "seconds_left" value as an attribute for the switch.

**Comment by tsightler** [comment]
The dev branch now has an implementation.  I played with a few options and finally decided to just keep it super simple and include a "minutes_remaining" attribute.  It's simply the number of seconds remaining rounded to nearest minute, so it's not perfect, but it's not bad either and I think it's completely suitable for information purposes.  I'll likely push 4.8.4 tonight or sometime tomorrow and it will include this.  Thanks!

**Comment by tsightler** [comment]
4.8.4 has been released so this features is now live!

**Comment by arjan-io** [comment]
Thanks. I will check it out!
