### ISSUE TITLE
Support for alarm status?

### ISSUE THREAD

**Issue by fourcadm** [tsightler/ring-mqtt#27]
Hi!

First off, awesome job!
Nice to be able to integrate the ring alarm with HA.
Any plan to report the status? Meaning I want to be able to trigger stuff in HA is the alarm is ringing or somebody pressed the panic button...

Best,

Matt

**Comment by tsightler** [comment]
This is on my to-do list.  There's actually already a pull request from another user that implements this but it appears to report based on whether the siren itself is sounding which I'm not convinced is the best method (it would trigger during siren tests, for example).  I need to find time to test the various states and see if there's a better trigger, but of course I have to test when my wife isn't home so I don't drive her crazy.

**Comment by tsightler** [comment]
I've worked out how to do this.  Now that the code refactor is behind me I'll try to put something together for this soon.

**Comment by fourcadm** [comment]
Wonderful!
Thanks!

**Comment by LargeSpark** [comment]
Is there any update on this? I want to see if the entry delay has been triggered also if that is possible. Well done on your progress so far. This is the most polished integration I've seen for something like this.

**Comment by tsightler** [comment]
The only update is that I haven't had time to work on this feature. What little time I've had to spend on this project has been mostly focused on keeping it working at all.  I still need to clean up, finish testing, and push the most recent 2FA fixes.

The goal of this feature is definitely to provide the kind of alarm status you are looking for, but lack of time and ability to test due to everyone being at home with the current situation (my house pretty much has five adult aged people at all times now) have meant this project is mostly on the back burner for right now.  Hopefully I'll be able to find some time in another month or two and knock out a few of these features.

**Comment by Mistretzul** [comment]
Hi guys,

This script is brilliant. I have integrated this with my OpenHab setup (script runs on the same Raspberry Pi as OpenHab and via MQTT it passes the relevant info). I am very interested in the Alarm State feature. I have implemented my own Base Station module, but there is very little useful info coming from the Ring API JS module to be fair...

I am struggling to understand how this AlarmState comes in as the only module that repors something that is close enough is the the Security Panel, and it reports the supported alarm types rather than the current state....

 **Security Panel Data:**

.....
ring-mqtt   instantAlarms: {},
  ring-mqtt   mode: 'none',
....
  ring-mqtt   reminderInfo: {},
  ring-mqtt   siren: { state: 'off' },
  ring-mqtt   **supportedAlarmTypes: [ 'burglar-alarm' ],**
  ring-mqtt   triggerDevices: {},
  ring-mqtt   troubleSounds: { enabled: true } } +2s
....

At the minute I am also using the Siren:State as it is the only indication I can see when the Alarm goes off... And it dos set to TRUE when you test the siren. It only goes to true when the alarm is armed (home or away) and the siren really goes off...

If you have any ideas how can we get the Alarm State, that would be lovely. I can see in Ring-Types.ts the following structure that I would really like to understand where it should come from :

alarmInfo?: {
        state: AlarmState;
        faultedDevices?: string[];
        timestamp?: number;
        uuid?: string;
    };

**Comment by tsightler** [comment]
I believe that alarmInfo is "optional" property and is part of the security panel, i.e. it doesn't exist unless the alarm is in a triggered state.  If you look at the Homebridge code it has this for the security panel:

```
if (alarmInfo && this.alarmStates.includes(alarmInfo.state)) {
      return State.ALARM_TRIGGERED
    }
```

So it's first checking if the alarmInfo property exist and, if it does, it's then grabbing the state and returning the alarm status as triggered.  My plan is to implement basically this same logic this to provide a "triggered" state for the MQTT alarm control panel and also, as part of adding perper devices support for Home Assistant, add an additional sensor to return the specific alarm that was triggered (burgler, fire, etc).

I'm hopeful to work on that sometime in July as I think I'm finally going to have at least a little time.

**Comment by Mistretzul** [comment]
Yes indeed is optional, however, I am trying to understand how/when the RingDevice will fill it in.. I am trying to "stream" that structure over MQTT if it exists (similar implementation as above) but I could not find a scenarion when this is populated...

**Comment by tsightler** [comment]
It should exist in the security panel update data when the alarm is triggered.  Are you saying that when you trigger alarm events you don't see this field in the returned message?  Overall, I expect it should be as simple as adding a few lines of code to the publishData function.

**Comment by Mistretzul** [comment]
Please ignore my incompetence..It does work correctly. I did not realized the structure is set to null while the alarm is not triggered. Indeed, when triggered the structure does exist and can be used.

**Comment by tsightler** [comment]
Finally getting around to this.  If anyone wants to test, I've pushed the first beta for the upcoming 4.0.0 release to the dev branch.  This has been a significant refactor to attempt to simplify the code, unify the handling of devices and get rid of lots of special handling to make this code easier to maintain and make it possible to start adding more features.

A big part of the 4.0.0 release is full support for the Home Assistant device registry.  All sensors now have their standard entity state, but also include a device level "information" sensor with additional data such as battery (along with a graph) tamper status, communication status, last update info, etc (exact data varies per device).

For example, related to this feature request for alarm status the standard Alarm Control Panel now has support for "pending" (entry-delay) and "triggered" (any active alarm) state which you can use for simple automations.  However, if you want more detail on the type of alarm the new "info" sensor includes the detailed alarmState attribute which can have the following values:

burglar-alarm
entry-delay
fire-alarm
co-alarm
panic
user-verified-burglar-alarm
user-verified-co-or-fire-alarm
burglar-accelerated-alarm

This way you can even build specific automation based on the type of alarm.

If any of you can test this new code from the dev branch I'd love to hear feedback, while there's still a good bit of work to do, I think it's starting to come together enough that people can test it.  I'm running it in my own setup with good success.

If you are using the addon there is a [Dev version of the addon](https://github.com/tsightler/ring-mqtt-ha-addon-dev) which downloads and installs the dev branch of the ring-mqtt script.  I will also be making some pretty decent updates the the add-on later, mainly to pull pre-build Docker images instead of building them locally, but I'm holding off on that until the primary script is finished.
