### ISSUE TITLE
Smart responses integration. 

### ISSUE THREAD

**Issue by donpearson** [tsightler/ring-mqtt#274]
Hi,
as ring has released smart responses do you know if it can be or will be Incorporated within ring-mqtt as I would love to be able to change them when I arm or disarm my alarm using home assistant. 
Thanks for your time.

**Comment by tsightler** [comment]
@donpearson Probably not any time soon, unless the capability shows up in ring-client-api or if someone does the work to figure out the required API calls, so certainly if one those things happen I would consider including it, however, for now, unfortunately, I don't have time to go poking around in the Ring API to try to figure it out as I'm taking a little bit of a hiatus from this project.

Since, as far as I know, we simply don't have this information required to implement this right now, I'm going to close this for now, but feel free to re-open if you see that the function has been added to ring-client-api, or if at least the required API calls have been determined (if we know the API functions I can implement a custom function).
