### ISSUE TITLE
Integration broken when HA is restarted

### ISSUE THREAD

**Issue by happydutch** [tsightler/ring-mqtt#276]
**Describe the bug**  
After HA is restarted, all of the entities show as unavailable. After restarting mqtt-ring docker container, the entities immediately get updated.

I have the container to restart automatically when it exits (see below). I suspect that the restart happens too early for ring-mqtt. I am not sure how else to run the container.

**Describe your environment**  
HA Running in docker. Version = 2021.9.2.
Separate mqtt server.

**Describe your settings and what you've tried**  
Docker install:
docker run  \
    --init \
    -d \
    --cpu-shares 300 --memory=256mb --memory-reservation=100mb --memory-swap=512mb --oom-kill-disable \
    --restart=unless-stopped \
    --mount type=bind,source=/root/data/ring-mqtt,target=/data \
    -e "MQTTHOST=192.168.11.225" \
    -e "MQTTPORT=1883" \
    -e "MQTTRINGTOPIC=ring_topic" \
    -e "MQTTHASSTOPIC=hass_topic" \
    -e "RINGTOKEN=mysecrettoken \
    -e "ENABLECAMERAS=true" \
    -e "SNAPSHOTMODE=all" \
    --name=ring-mqtt \
    tsightler/ring-mqtt

**Debug Logs**  
I ran docker logs mqtt-ring --since 1h --follow

It seems to be that ring-mqtt is still reporting alarm/camera status as usual. For some reason HA just doesn't receive any updates to the entities.

```
-------------------------------------------------------
| Ring Devices via MQTT                               |
| Docker Edition                                      |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt              |
-------------------------------------------------------
[cont-init.d] ring-mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
-------------------------------------------------------
ring-mqtt.js version: 4.8.4
Node version v14.17.6
NPM version 7.17.0
git version 2.32.0
-------------------------------------------------------
Running ring-mqtt...

```

**Comment by happydutch** [comment]
Note, I realize that I can create container dependencies with docker compose... However ideally the script is aware of the state of HA.

**Comment by happydutch** [comment]
A suggestion is that instead of exiting the script when HA terminates, wait for a new instance to come along. Maybe governed by a env variable WAITFORHA=1 or so.

**Comment by tsightler** [comment]
The only method the script has to know the state of HA is via MQTT which is why the script monitors for birth/last-will messages from the HA status topic.  The birth/last-will messages have been enabled by default in Home Assistant for quite a while, but if for some reason you have them turned off, or configured to something non-standard, then there's no other way for ring-mqtt to know anything about Home Assistant state.  In general this is configured with the UI for the Mosquitto integration but if you are for some reason using CLI then here is the documentation:

https://www.home-assistant.io/docs/mqtt/birth_will/

**Comment by tsightler** [comment]
> A suggestion is that instead of exiting the script when HA terminates, wait for a new instance to come along. Maybe governed by a env variable WAITFORHA=1 or so.

The script does not exit when HA terminates so I'm not sure what your are talking about.  Tons of users leverage ring-mqtt without HA at all as the project is not HA specific.  The ability to monitor birth/last will has existed in the project since day 1.  Please verify that it is configured in your case.  You should see entries in the ring-mqtt log when you restart HA that it detects this, if you don't then you need to troubleshoot this and verify you have birth/last-will enabled.

**Comment by happydutch** [comment]
I have added a restart of the container as part of HA startup and that fixes it.

**Comment by happydutch** [comment]
BTW thanks for this great project -- very nice to have Ring integrate with HA...

**Comment by tsightler** [comment]
OK, that's fine.  I'm not sure why you wouldn't just configured birth/last-will messages so that ring-mqtt would be aware of HA restarts, but you can use whatever method you like.

**Comment by happydutch** [comment]
Let me take a look at that as well - I have not explicitly disabled/changed it.

**Comment by happydutch** [comment]
HA sends normal online/offline MQTT messages, so that can't be it.

**Comment by tsightler** [comment]
That's the only trigger for ring-mqtt to know that HA has restarted.  I'd be interested to see logs from ring-mqtt after an HA restart as such events are clearly logged.  I've seen some people setup security on MQTT in a way that ring-mqtt doesn't see those messages.  I've also seen one or two cases where HA installed on a slow device, like a RPi3, sends online fairly early, but isn't really ready for the barrage of discovery messages.  The code literally resends all discovery messages every 30 seconds for 3 minutes after any HA restart, but if it doesn't no about it, or HA isn't ready, there's not much it can do.

This is not a common problem, if this wasn't working for the majority of people I'd have 100 issues open right now (I know, because it's been accidentally broken once or twice) so it has to be something unique that is either configured differently or is triggering some type of bug.

What topic is your birth messages using?  Do you see the log entry in ring-mqtt that shows that it sees the message?

**Comment by tsightler** [comment]
To give you some idea, this is the type of messages you should see in ring-mqtt when HA restarts:
```
2021-10-05T16:30:22.688Z ring-mqtt Home Assistant state topic homeassistant/status received message: offline
2021-10-05T16:30:37.117Z ring-mqtt Home Assistant state topic homeassistant/status received message: online
2021-10-05T16:30:37.118Z ring-mqtt Home Assistant restart detected, resending device config/state in 5 seconds
```
It currently monitors the following topics:
```
homeassistnat/status
hassio/status
hass/status
```
If status messages from HA are being sent to these topics and ring-mqtt is able to receive these message, then it will detect the restart and resend all device discovery and state data.  If you are not seeing these messages, then, for some reason, the messages are not being received by ring-mqtt (or perhaps some bug), and if you are seeing these messages, then it should be followed by discovery and state messages being sent every 30 seconds for 3 minutes (6x total) which should be enough in almost all cases to put devices back online.

**Comment by happydutch** [comment]
Thanks - the MQTT topic emitted by my instance is homeassistant/status. 

Observed the logs using "docker logs ring-mqtt --since 1m --follow" and that doesn't show it is responding on the "offline" or "online" message. It keeps sending device updates to MQTT. Will be looking further.

**Comment by happydutch** [comment]
I think I found it - in below function you use either the config topic, or hass/status, hassio/status. In the sample you set these to: -e "MQTTRINGTOPIC=ring_topic" -e "MQTTHASSTOPIC=hass_topic". I left it as is, as I didn't really understand what this was used for (it is undocumented). Would be good to add the default homeassistant/status as a default topic to recognize (BTW I see now you do that in config.json, so the env vars are redundant). Reopening as a suggestion, or doc bug :-)

// Process received MQTT command
async function processMqttMessage(topic, message, mqttClient, ringClient) {
    message = message.toString()
    if (topic === CONFIG.hass_topic || topic === 'hass/status' || topic === 'hassio/status') {

**Comment by happydutch** [comment]
Removed the env vars and all is fine now. Partial user error; partial doc bug.

**Comment by tsightler** [comment]
Good point, I basically removed all documentation of this as being configurable a long time ago, even though it still technically is able to be configured in the code, but I never removed the line from the docker run example.  Heck, I basically forgot it was there at all.  I should have noticed it in your first post.

For 4.8.5 the documentation is somewhat refactored to split standard install vs docker installs into different docs so I'll make sure to address it there.

Glad you got it working and thanks!

**Comment by tsightler** [comment]
4.8.5 remotes these from the docs completely.
