### ISSUE TITLE
Docker Hub Container

### ISSUE THREAD

**Issue by Banner-Keith** [tsightler/ring-mqtt#28]
Would you consider having this pushed to Docker Hub so that end users can just install it rather than having to build the docker container from the source? A build server of some sort would be needed if you wanted it to be automated. I may be able to assist there.

**Comment by tsightler** [comment]
What is the advantage of this?  I mean, it's literally one command that takes a few seconds to run.  I just don't see any benefits to this at all, but perhaps you can enlighten me.

**Comment by Banner-Keith** [comment]
It makes it so that you don't have to have node js installed and configured on the machine, or have to make sure that your copy of the code is up to date. You don't have to pull latest from git or anything. You stop and start the container to update.

I understand if you don't see the benefits, but for some of your end users, especially those that may not know git and node very well it might be helpful.

**Comment by tsightler** [comment]
I guess I can see the upside from the update perspective, but, as I don't use Docker myself, so I don't really test or support it today, I'm not sure it's something I'm interested in doing at this time, but I'll think about it in the future.

**Comment by AdamVig** [comment]
I would also benefit from having this image published to Docker Hub. I want to add this to my [Deviceplane](https://deviceplane.com/) deployment, which uses Docker Compose. Since the Docker configurations are evaluated on a remote device, it is unfortunately not as simple as "literally one command that takes a few seconds to run."

If this image were published to Docker Hub, it would be "plug and play" to run it on my device. I published it under [adamvig/ring-mqtt](https://hub.docker.com/repository/docker/adamvig/ring-mqtt) on Docker Hub, but will be glad to remove it if you ever decide to publish it under your name instead.

**Comment by tsightler** [comment]
@AdamVig Thanks for the additional feedback.  Now that I've finally finished the code refactor and once I finish debugging a few issues with it and adding support for a few additional devices, I will reconsider this request.

My biggest concern is that I really never anticipated how popular this simple script would be and I already barely have enough time to support it.  Maybe it will be better/easier now that the code is more modular.

**Comment by Banner-Keith** [comment]
If I remember correctly Docker Hub can even do the build for you automatically every time the master branch is updated. You basically just need a docker file which @AdamVig may be willing to provide.

**Comment by tsightler** [comment]
Yeah, it's not so much the effort to put it there, but the effort to support another wider audience.  Admittedly, the audience already exist, but at least if they report an issue not related to the script I can say I don't support that.  It's what I did so long with the Hass.io addon because, talk about a nightmare to support, but I finally gave up because it was falling to me anyway.

That's not to say I don't want to support people, I do, but time limitations are real and people get amazingly demanding for this free thing to work for them, so I'm always hesitant to widen the audience even further.  Perhaps that's not really fair, and going to Docker Hub doesn't really change it that much, but I see something like 20,000 pulls of other peoples Docker Hub images from ring-alarm-mqtt.js previously, so that concerns me!

Once the 3.0.0 version is stable and published, I'm hopeful that maintenance will go down and I'll consider publishing and maintaining it on Docker Hub.  Maybe I'll have to switch to running it in Docker myself!

**Comment by AdamVig** [comment]
@Banner-Keith I would be glad to contribute one, but thankfully there is already [a Dockerfile](https://github.com/tsightler/ring-mqtt/blob/6d27f69d556799d4746281410253f3e6a3f6cea0/Dockerfile).

Docker Hub can build containers automatically, but as far as I can tell, it only builds for one architecture at a time. I want to run this on my Raspberry Pi, so I would need an ARM build. This should be straightforward with the GitHub Actions [build matrix feature](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix).

@tsightler Great points about maintenance and time constraints! I would be glad to help with documentation and continuous integration setup (assuming the project works for my use case, which I think it will).

**Comment by Banner-Keith** [comment]
@AdamVig ah. Right you are. I had forgotten that there was a docker file. I have mostly done this with. NET Core so I only had one docker hub build and that was sufficient. I think the build matrix option sounds like a good idea.

@tsightler I totally get the concern with having a wider audience and the increasing amount of work that can create. I read that most open source projects, even many widely used projects, have two or fewer people that do the majority of the work and that projects won't survive without them. Hopefully this project can be something that doesn't consume more of your time than it is worth.

**Comment by tsightler** [comment]
I did setup an automatic publish to Docker Hub but it's only the amd64 arch.  I'm working on building and publishing for arm, once I figure it out.

**Comment by tsightler** [comment]
OK, I've setup a Buildx environment and automated a simple process to push builds to Docker Hub for the linux amd64, arm64, arm/v7 and arm/v6 architectures.  I feel like that should cover the reasonable use cases but if I missed an arch it's super easy to add it with Buildx, so just let me know.

I tested the created images on my RPi3b+ Raspbian Buster install and on an Ubuntu VM and both pulled and ran with no issues but this is my first real experience building multi-arch and pushing to Docker Hub so testing and reports of success/failure are appreciated and any pointers if I'm doing something incorrectly.  It seemed pretty straightforward.

I'll consider this "official" and start publishing any releases to master going forward as well as update the documentation to perform docker pull vs build.  Thanks for the encouragement to do this, I hope people find it useful.

**Comment by AdamVig** [comment]
@tsightler Thank you for doing this! I was able to pull the image and run it on my Raspberry Pi. It seems to run fine. (I'm having trouble connecting Home Assistant/Mosquitto/Ring MQTT in Docker Compose, but I think that's a problem on my end, not an issue with this project.)
