### ISSUE TITLE
Opening Stream

### ISSUE THREAD

**Issue by Bradley225** [tsightler/ring-mqtt#290]
I am having a problem when first opening the stream of my camera by clicking a camera in Homeassistant which shows in the log of ring-mqtt the following. Sometimes the camera will require me to press play again and it will appear. It seems to not have this issue on VLC.

  ring-rtsp I [0/0] [RTSP] [conn 127.0.0.1:63019] opened +2s
  ring-rtsp I [0/0] [RTSP] [session 467476551] opened by 127.0.0.1:63019 +1ms
  ring-rtsp I [1/0] [RTSP] [session 467476551] is publishing to path '343ea427c826_live', 3 tracks with TCP +3ms
  ring-rtsp I [1/0] [RTSP] [conn 127.0.0.1:63020] opened +509ms
  ring-rtsp I [1/0] [RTSP] [session 271646042] opened by 127.0.0.1:63020 +1ms
  ring-rtsp I [1/1] [RTSP] [session 271646042] is reading from path '343ea427c826_live', 3 tracks with TCP +1ms
  ring-rtsp I [1/1] [RTSP] [conn 127.0.0.1:62984] ERR: read tcp 127.0.0.1:8554->127.0.0.1:62984: read: connection reset by peer +621ms
  ring-rtsp I [1/1] [RTSP] [conn 127.0.0.1:62984] closed +0ms
  ring-disc Republishing existing device id: 343ea427c826 disc +30s

Anything I should be looking at when this kind of issue occurs ?

**Comment by tsightler** [comment]
That's nowhere near enough logs to troubleshoot an issue like this as that's just the stream data itself.  Please provide full logs, or at least entire logs of the stream startup if you want any detailed help.

How long are you actually waiting in Home Assistant for the start displaying the stream?  The fact that your saying clicking play will get it to start makes me think your not waiting long enough.  Home Assistant uses HLS for streams so it buffers ~5-6 seconds of video before the stream will display and since it normally takes 2-3 seconds for the stream to start you will usually have to wait ~7-9 seconds for the video to initially start streaming in Home Assistant after clicking the video.  VLC of course doesn't have this issue since it's just playing the RTSP stream directly with only about 1 second of buffer (by default) so it starts much faster.

From the perspective of ring-mqtt, there's zero difference between Home Assistant starting a stream and VLC starting a stream, they are both just RTSP streams, so if one works and one doesn't, it's unlikely to be a problem on the ring-mqtt side. 
 My first guess is you're just not being patient enough since HA is so much slower starting to display the stream due to it's buffering.  Without more detailed logs, it's more difficult to make a second guess, but, if it's not simply that you are not waiting long enough, then the second guess would be that, for whatever reason, the stream doesn't always start within the 5 second RTSP timeout which HA has, but this should be visible in the HA logs.

**Comment by Bradley225** [comment]
Thanks for responding. I should have mentioned I am now using webRTC to show the video via Homeassistant but this problem has existed from the start of getting it streaming when just using Homeassistant to view the cameras. It seems to not happen at all on the host device - VLC or Homeassistant maybe because it is connected by LAN whereas it happens quite often on Tablet and Phone which are connected by WiFi or 4G.

I'm not sure how I can not give it enough time as I now have the runOnDemandStartTimeout value passed properly and it just seems to try to load the camera and then comes up with errors such as restart stream, no video or i/o timeout on the camera view so I have no choice but to press play again.

It is difficult to debug as it is intermittent, I have just restarted ring-mqtt so I knew it wasn't connected already at all to rtsp and then opened the streams fine on tablet over host device and then on WiFi. Tried to do the same over 4G (restarted ring-mqtt) and the connection reset by peer error appears again. Other than posting a load of mqtt data I am not sure what debug logs you need as the data I posted earlier seems to be the only rtsp relevant data at the time the error occurs. 

Thanks for your help and again for an amazing project. Would love to get it working on my phone or tablet like it is doing on my Mac!

**Comment by tsightler** [comment]
runOnDemandStartTimeout has nothing to do with the reader side of RTSP, only the publishing side and, in general, most RTSP clients will timeout if the stream does not start in 5 seconds.

WebRTC is not very reliable outside of the local network, and it also doesn't work very well when there are multiple cameras (I find it exceptionally unreliable with more than about 2-3 cameras).  These problems are mostly in WebRTC and are documented there, including possible workarounds (mostly, manually opening UDP ports), I'm not going to be able to help with those.

Realistically, the only thing useful for troubleshooting is full logs of the issue so then we can see, that includes MQTT data because the RTSP server uses MQTT to signal the streams to start and to monitor stream state, without that information there's not much to go on.  As noted when opening a case, you can send the logs via email if you don't want to post them here, then provide a time when the streaming worked vs when it failed, and I can see if there's anything happening on the addon.

That being said, since you say it's working on your Mac, then there's not likely to be anything wrong with the addon as the web components that present the streams are not in my control, it may simply be that your expectations are too high.

**Comment by tsightler** [comment]
Closing this as I don't see anything I can help you with here.  Good luck!
