### ISSUE TITLE
Support the project?

### ISSUE THREAD

**Issue by TheLinuxTrucker** [tsightler/ring-mqtt#292]
I really appreciate all of the work you do on the project and would like to give some money in addition to just saying THANK YOU! Maybe a way to do this could be added to the readme or somewhere it is easy to find? I'm sure other people feel the same way

**Comment by tsightler** [comment]
While I've had multiple offers to contribute money to the project I've been extremely hesitant to accept such contributions because, honestly, at least at this current point in my life, I just don't need the money and any amount contributed would be inconsequential.  More importantly, it wouldn't make a difference as to how much time I have available for this project.  If I could figure out a way to make contributions directly benefit the project then I'd be more open to it.  I've historically just told people that wanted to contribute cash to donate it to some other project or charity of their choice.
