### ISSUE TITLE
Interval snapshot not working on Ring Doorbell 2 (battery)

### ISSUE THREAD

**Issue by jackyaz** [tsightler/ring-mqtt#295]
Hi,

I'm a new user to this project and love it! I've noticed interval snapshots don't seem to work - they're enabled every 14 minutes in the Ring app, but don't update via ring-mqtt. I see the below messages in the log.

2022-01-10T16:55:56.274Z ring-mqtt [Front Door] Error: Not found with response: no snapshot
2022-01-10T16:55:56.274Z ring-mqtt [Front Door] Could not retrieve updated snapshot for camera

It's possible this is a Ring issue, as when I open the app and start a live view, the snapshot in the app updates and then so does ring-mqtt

Just wanted to check if there was any way I can poke around ring-mqtt to see if its a Ring issue?

**Comment by tsightler** [comment]
Hi @jackyaz.  The first error message is the error returned by ring-client-api and the second is expected since the first message failed.  The ring-client-api does nothing more than make one call to an API endpoint which request the camera to refresh the current snapshot.  Clearly in your case this call is failing.

I see one other report of this in the ring-client-api Github issues page:

https://github.com/dgreif/ring/issues/119

Notice they have the identical message because ring-mqtt and ring-homebridge use the same ring-client-api underneath.  It looks like in the case of this issue rebooting the camera solved the problem.

Note that there can be other reasons for this failure, for example, battery cameras are not able to take snapshots during livestreaming or recording, so this is important to understand as well, or mode settings that disable motion detection, which also disables the ability for the camera to take a snapshot.

One thing that might be interesting, what happens if you login to the Ring account from a standard web browser (i.e. not the app but from say, Chrome on a desktop).  Does that camera refresh immediately?  The reason this might be interesting is because it's actually using the very same API to update the snapshot.  In the end, this code is largely unchanged for years now so I doubt it's anything on the code side that is causing this issue.

**Comment by jackyaz** [comment]
Hi, thanks for the swift reply! I'll test this as soon as I can - both ring-mqtt and the Ring integration can no longer authenticate to my account - not sure why. When trying to sign back in the syslog throws:
```
Jan 11 09:49:34 BorkBorkPi d70531bdc60b[998]: 2022-01-11T09:49:34.302Z ring-mqtt WARNING - Unhandled Promise Rejection
Jan 11 09:49:34 BorkBorkPi d70531bdc60b[998]: TypeError: argument val is invalid
Jan 11 09:49:34 BorkBorkPi d70531bdc60b[998]:     at Object.serialize (/app/ring-mqtt/node_modules/cookie/index.js:116:11)
Jan 11 09:49:34 BorkBorkPi d70531bdc60b[998]:     at ServerResponse.res.cookie (/app/ring-mqtt/node_modules/express/lib/response.js:857:36)
Jan 11 09:49:34 BorkBorkPi d70531bdc60b[998]:     at /app/ring-mqtt/lib/tokenapp.js:71:25
Jan 11 09:49:34 BorkBorkPi d70531bdc60b[998]:     at runMicrotasks (<anonymous>)
Jan 11 09:49:34 BorkBorkPi d70531bdc60b[998]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by jackyaz** [comment]
OK, got it working again. Looks like Ring didn't like my HA being connected via NordVPN

When ring-mqtt started up, I saw the same error as initially reported, and the snapshot shown was of last night (dark screenshot). I logged in to Ring.com which updated the screenshot and showed "3s ago", at which point ring-mqtt noticed and updated the screenshot.

**Comment by jackyaz** [comment]
Saw the snapshot error again, so logged in to Ring.com . This time, it showed the snapshot as 1m ago, but ring-mqtt hasn't noticed. In fact, this just popped up from ring-mqtt in its usual logging:

"lastUpdate":"2022-01-11T16:09:48Z"

How often should it be polling for changes from Ring - or has their API simply not pushed an update to retrieve?

**Comment by tsightler** [comment]
This doesn't make a lot of sense as the snapshot used by ring-mqtt is not the same one used by the Ring.com app, even though they use similar methods to acquire the snapshot.  Logging in to Ring.com was just to see if it worked since I knew they used a very similar method so it helped to rule out any strange issues with the camera itself.  To me this implies that the problem is more of a timing related issue.

Right now the code basically requests a refreshed snapshot from the camera via the Ring API, waits 1 second, then queries the API to see if the new snapshot is there and, if not, you get the "could not retrieve updated snapshot" message.  In all of my testing I've never seen a case where 1 second wasn't enough time but I wonder if battery cameras can sometimes be slower because, in your case, nothing actually seems to be failing, it just the snapshot isn't there, perhaps it's just not there yet.  In 4.8.5 I made a change that used this hard coded snapshot method because the method used by ring-client-api was causing a lot of reported issues, however, it was more robust in the sense that it didn't just wait 1 second, but rather had a retry loop to wait for the snapshot to appear.  Perhaps this change introduced this issue.

Due to the battery drain the default behavior for battery cameras is whatever you have the snapshot capture interval set to in the Ring app, which you said above was 14 minutes, so I wouldn't expect a refresh more often than that.  Note that the snapshot retrieved is not the same as the one in the app, it just uses the same interval as the default.  Of course, you can change this interval, at the expense of battery life.

**Comment by jackyaz** [comment]
Many thanks for getting back to me. Should I try a downgrade to 4.8.4 to see if it helps?
Also, how do I override the interval temporarily for testing?

**Comment by tsightler** [comment]
If it's not too much trouble to try 4.8.4 it would be very interesting to see if it fixes the problem.

If you select the device in HA you will see that one of the controls is "Snapshot Interval" which allows you to set the interval in seconds.  For some reason it's not always possible to read the value from the Ring API (some accounts don't seem to provide it) so in that case it just default to something like 30 seconds for wired camera and I think 600 seconds for battery cameras, although I don't own any battery cameras and I can't remember for sure.

**Comment by jackyaz** [comment]
Interestingly, without downgrading, setting the interval to 60s seems to show successful snapshots every minute
```
ring-mqtt [Front Door] ring/yyy/camera/xxx/snapshot/image <binary_image_data>
ring-attr [Front Door] ring/yyy/camera/xxx/snapshot/attributes {"timestamp":1641920902}
```

**Comment by tsightler** [comment]
What was the interval before?

**Comment by jackyaz** [comment]
840, so 14 minutes pushed from the Ring app

**Comment by jackyaz** [comment]
I wonder if it trying to get a snapshot at the same time as ring is/was clashing?
EDIT: Setting to 600, I see an error. Back to 60, no errors. Very weird. I've put it back to 600 will see if it ever suceeds. If not, I'll try 4.8.4

**Comment by tsightler** [comment]
> I wonder if it trying to get a snapshot at the same time as ring is/was clashing?

Well, it shouldn't as only the interval valued is pulled, the schedule of when those snapshots are taken is not synchronized between them, so ring-mqtt is unlikely to be overlapping.  Was it really failing every 14 minutes before?

I think I'll probably just add a little retry logic to the existing code.  I have a 4.9.0 scheduled to bump some dependencies and get the code based to the point where I can start making updates again.

**Comment by tsightler** [comment]
One thing, it's possible that the battery camera goes into some kind of battery saving/sleep mode, perhaps polling for a snapshot every 60 seconds keeps it awake, while if you set the interval longer it takes longer to get that first snapshot.

I really don't know anything about the detailed behavior of Ring battery cameras as I determined a long time ago that they were too non-functional for me so I don't even own one to test with.  In many ways I regret every attempting to add snapshot features for battery cameras beyond what the ring-homebridge plugin has because they are just so limited as to always be a pain.

**Comment by jackyaz** [comment]
Battery saving sounds like a good theory! I'm beginning to realise the limitations of the battery camera now that I'm pushing it - unfortunately getting a wired one is a bit impractical/costly for the time being. 

Should I downgrade, or can I try 4.9.0 alpha/beta when you have a version with some retry logic added?

**Comment by jackyaz** [comment]
Powersaving might be on the money. Note the link speed when snapshots fail:
![image](https://user-images.githubusercontent.com/6189420/148994369-544a3be0-4579-4088-b4a9-5a64ebd0cf47.png)
And here it is when setting 10s interval:
![image](https://user-images.githubusercontent.com/6189420/148994613-1b4612c1-46f2-4f2e-9557-6d4c7547ca9b.png)

**Comment by tsightler** [comment]
What install method are you using (Standard/Docker/Addon)?

Normally I push changes to the dev branch and people can test them out easily using the branch feature, however, due to some of the dependencies having breaking API changes I can't use the branch feature to test 4.9.x with existing docker images.  Because of that, I'll probably push 4.9.0 with dependency bumps only just to get the base image updated as I already have it queued up and ready to go, I just didn't quite get it all done last night.

After that, I can push some simple retry logic into the dev branch and you can try it and, if it works, I'll queue it up for 4.9.1, which will also include a few other pending fixes as well.

**Comment by tsightler** [comment]
> Powersaving might be on the money. Note the link speed when snapshots fail: ![image](https://user-images.githubusercontent.com/6189420/148994369-544a3be0-4579-4088-b4a9-5a64ebd0cf47.png) And here it is when setting 10s interval: ![image](https://user-images.githubusercontent.com/6189420/148994613-1b4612c1-46f2-4f2e-9557-6d4c7547ca9b.png)

Interesting to see.  We also know, based on other projects, that setting polling too often absolutely sinks the battery life in a non-linear way, so all of that evidence suggest that powersave mode is almost certainly a contributing factor.

Of course there are significant benefits to battery cameras as well, and it makes sense they would have limitations to help with battery life, but the tradeoff in functionality is significant for the Ring battery cameras.  I mean, Ring cameras have significant limitations in general, battery or wired, I decided I could live with the wired limitations due to ease of install and use, especially for the rest of the family, but battery was just a little too limited to me.  I'm not criticizing anyone of using them though, sometimes they are just the only practical option.  I helped my daughter install a solar powered version, which basically has the same limitations as the battery cameras, but it was the only practical option for the location that wouldn't have required 10x the work.  It's just that the limitations are a little difficult to code around, especially when I don't own one and I implement a feature based on the cameras I do have and then realize how those will never work well for battery cameras.  It's created a support challenge for this project because not everyone realizes these limitations.

**Comment by jackyaz** [comment]
I maintain several projects myself and I can appreciate supporting things you don't own - in my case, it's Asus router models!

I use ring-mqtt as a Home Assistant Addon via HACS. I'm very new to HA in general but I'm not code shy! It looks like you have a branch config option, is that what I'd change to give the dev branch a go?

**Comment by tsightler** [comment]
Yes, I implemented the (crude) branch feature some time ago to make it easier for users (and even myself) to quickly test code from the dev branch without me needing to push a new addon/container image every time or maintain a separate dev version of the addon like I did previously, which was a lot of annoying overhead.  It's basically just a crude shell script executed during startup that pulls in the named branch from github.

It usually works just fine, but it only updates the actual JS code, not the dependent binaries, like rtsp-simple-server as those are included as part of the Docker image build (I guess I could modify the script to include these in the future, but it's usually not required).

In the 4.9.x version I had to make changes to support the newer versions of rtsp-simple-server which included some changes to the API that were not backwards compatible with prior versions so I can't use the branch feature to test the 4.9.x code base on a 4.8.x docker image.  I mean, technically everything would probably work except for video streaming, but I'm not sure if my code is robust enough to not fail completely when the API calls break (I think it would, but it's definitely untested).

**Comment by jackyaz** [comment]
Thanks, so it sounds like I should wait for 4.9.0 stable, and then when you have kindly put something on the dev branch, change the config? No rush on any of this, I'm happy to wait when you have time to release things!

While I think of it, is there any way to use a service/script call to trigger a snapshot update, outside of the scheduled snapshots? I'm just thinking that could be quite cool to put into an automation for a motion event to ad-hoc grab a screenshot - assuming Ring's battery camera doesn't block it while it's doing its own capture :D

**Comment by tsightler** [comment]
Well, that feature already exist in ring-mqtt, so there's no need to script it (the snapshot documentation covers this, you can do interval snapshots, or motion snapshots, or both).  Also, Ring's battery cameras do block snapshots during capture (any recording on a battery camera blocks snapshots and of course motion events trigger recordings).  There's been some effort to reverse engineer access to the rich notification image, but it seems Ring blocks the use of the push API except for their own apps and I haven't had time to do more work to try to get around it (I feel like it might be more doable now that the Ring.com web based app has notifications, although I don't know if they are rich).

In the interim the code in ring-mqtt detects if a camera is battery or wired and, if battery, attempts to work around this by connecting to the live stream and grabbing a key frame from the stream.  This takes longer and is less reliable, but is the only available option for battery cameras other than waiting for the recording to end (which is what, for example, ring-homebridge does).

You can read the full list of limitations for Ring battery cameras and snapshots here:

https://github.com/dgreif/ring/wiki/Snapshot-Limitations

**Comment by tsightler** [comment]
Oh, and yes, easiest is to wait for 4.9.0, shouldn't be long though, it's literally queued up and ready to go, just have to push the button to do the release when I'm prepared for the reports of upgrade issues.

**Comment by jackyaz** [comment]
> Well, that feature already exist in ring-mqtt, so there's no need to script it (the snapshot documentation covers this, you can do interval snapshots, or motion snapshots, or both). 

I've had a look through and can't see a way to say "collect a snapshot now", I guess that's deeper in the API? It sounds like your workaround of grabbing a frame from the livestream would work, so I'll sit tight and wait for the retry logic (or dial up the frequency for the time being) to see if I can get a fairly recent snapshot included in notifications.

Thanks for all your help so far!

**Comment by tsightler** [comment]
Sorry, guess I wasn't clear, you said:

> I'm just thinking that could be quite cool to put into an automation for a motion event to ad-hoc grab a screenshot

My point was that's already a feature, i.e. grabbing a screenshot during motion event, nothing extra is needed.

There is currently no method to create a snapshot on demand.  It's been requested a few times, but I've been hesitant to include it because it's ripe for abuse.  I've already had people that wanted to set snapshots to every second for all cameras for example, which would hammer the Ring API servers and likely cause them to look into doing things that block 3rd party apps from using their API at all (at this point, they seem to mostly look the other way and, in some cases, even tacitly support us).

I could theoretically implement some type of throttle, but that's even more work, just doesn't really seem required as, IMO, the most useful feature is grabbing a snapshot of the motion event, and this is already there and build it.

**Comment by tsightler** [comment]
The problem you'll have with a battery camera is that you'll have to delay the notification for probably 5-10 seconds to have any shot of having a current image in the notification because it will always have to use the livestream to grab the image, which takes time, a snapshot will never work for a battery camera, maybe if you took snapshots every 10 seconds (the smallest interval currently allowed), but then the battery will probably die in hours.

Motion snapshots should already work right now as it's not dependent on the interval snapshots as they use completely different methods to grab the image.

**Comment by jackyaz** [comment]
its a shame that things with good intentions usually end up being abused by the few and spoiling it for the many

it sounds like i should give up on using the Ring's snapshot in HA for anything, and if i want that feature, get a wired doorbell

i'll wait for the updated version with retry to see if that solves the failures im seeing

**Comment by tsightler** [comment]
Well, having the feature to take snapshots on demand wouldn't change this behavior anyway since you can't take a snapshot while the camera is recording and motion events always trigger recordings.  By the time the notification gets to HA the recording has already started so it's too late to take a snapshot at that point, which is why the current code connects to the live stream and grabs a frame instead, it's the only marginally viable workaround for battery cameras other than waiting 30+ seconds for the recording to end.

**Comment by jackyaz** [comment]
I've noticed the interval keeps resetting itself to 840 - have I got something misconfigured?

**Comment by tsightler** [comment]
The interval will always reset if the addon is restarted because the code doesn't have the ability to save the state of runtime values so, during startup, it always defaults to the value from Ring settings.  It shouldn't reset in other cases.

**Comment by tsightler** [comment]
BTW, I've pushed 4.9.0 last night and, as of about an hour ago, the dev branch now has a retry implemented for snapshots.  Would be interesting to see if this fixes the issue when the interval is long.  You can just change the "branch" configuration option from "addon" to "dev" to give it a whirl.

**Comment by jackyaz** [comment]
> The interval will always reset if the addon is restarted because the code doesn't have the ability to save the state of runtime values so, during startup, it always defaults to the value from Ring settings. It shouldn't reset in other cases.

makes sense, i think i'd restarted the addon


> BTW, I've pushed 4.9.0 last night and, as of about an hour ago, the dev branch now has a retry implemented for snapshots. Would be interesting to see if this fixes the issue when the interval is long. You can just change the "branch" configuration option from "addon" to "dev" to give it a whirl.

installing dev now, will let you know how it goes, thanks!

**Comment by jackyaz** [comment]
I'm not sure if a retry is occurring?
```
2022-01-13T13:18:32.010Z ring-mqtt [Front Door] Requesting updated snapshot for camera
2022-01-13T13:18:33.786Z ring-mqtt [Front Door] Error: Not found with response: no snapshot
2022-01-13T13:18:33.786Z ring-mqtt [Front Door] Failed to retrieve updated snapshot for camera after all retries
```

Looking at the code, I can see that there should be a loop of several attempts... https://github.com/tsightler/ring-mqtt/commit/891684fa6b741ab3a7aa05c23aa8252687a96aaf#diff-35fa3bb3a9ec0a8014453a0c469b8089734c0198067bf03e85d7bd520fa96486R544

Ah...is the catch grabbing the error I wonder...

**Comment by jackyaz** [comment]
Would modifying the loop to something like this work?
```
let retries = 6                                                                                                                                                                                                                                           
while (retries-- > 0 && !newSnapshot) {                                                                                                                                                                                                                   
    await utils.sleep(1) // Give time for the snapshot to actually update                                                                                                                                                                                 
    try{                                                                                                                                                                                                                                                  
        newSnapshot = await this.device.restClient.request({                                                                                                                                                                                                  
            url: clientApi(`snapshots/image/${this.device.id}`),                                                                                                                                                                                              
            responseType: 'buffer'                                                                                                                                                                                                                            
        })                                                                                                                                                                                                                                                  
    }                                                                                                                                                                                                                                                     
    catch (error){                                                                                                                                                                                                                                        
        this.debug(error)                                                                                                                                                                                                                                     
        this.debug('Failed to retrieve an updated snapshot, retrying in 1 second...')                                                                                                                                                                         
    }                                                                                                                                                                                                                                                     
}  
```

**Comment by tsightler** [comment]
Yeah, silly mistake on my part.  I was thinking that I don't really want to retry if the request failure is anything other than "Not found", but then didn't write anything to catch only that case.  In the end, it's probably not worth it because the error case should be rare so your fix is easy.  That's what I get for coding up stuff too late at night while distracted with other things!

**Comment by jackyaz** [comment]
I know what that's like! I'll restart the container to pull down the modified loop once it's ready. I did try locally editing the file in the container, forgetting that the changes would be lost on a restart! I wasn't sure if I could restart node in the container, so thought it best to suggest a change here and see if I was even on the right track

**Comment by tsightler** [comment]
If you kill the node process in the container it should restart as it's supervised by s6.  I'd suggest killing both the node and rtsp-simple-server process because, for some reason, the rtsp-simple-server process is not always reaped when killing the parent node process and that will block the second node process from starting properly.  I use this method sometimes when I want to test a quick code change without pushing anything.

**Comment by jackyaz** [comment]
thanks for that - swapping the modded loop into camera.js seems to have promising results so far 
```
2022-01-13T16:11:02.495Z ring-mqtt [Front Door] Requesting updated snapshot for camera
2022-01-13T16:11:04.142Z ring-mqtt [Front Door] Error: Not found with response: no snapshot
2022-01-13T16:11:04.142Z ring-mqtt [Front Door] Failed to retrieve an updated snapshot, retrying in 1 second...
2022-01-13T16:11:05.643Z ring-mqtt [Front Door] Succesfully retrieved updated snapshot for camera
```
i'm having to take it at face value, as typically there's 0 activity outside today so the snapshots are going to all look pretty similar...

**Comment by tsightler** [comment]
Thanks!  Part of me wonders if I should just wait two seconds by default for battery cameras if the interval is over, say, 60 seconds.  I guess the retry isn't that big of a deal though.  I know that ring-client-api has a much more complex solution that caches images and returns the most recent snapshot if it was taken within 10 seconds, but it causes a lot of issues if I'm trying to get a motion snapshot since a capture from 5 seconds earlier misses the motion event in many cases.

**Comment by jackyaz** [comment]
I finally have visual evidence its working, the camera has gone night mode now and the snapshot updated accordingly. The most i've seen is 2 retries, but most are taking at least 1 retry before reporting success. I think this approach works well!

```
2022-01-13T16:53:02.496Z ring-mqtt [Front Door] Requesting updated snapshot for camera
2022-01-13T16:53:04.289Z ring-mqtt [Front Door] Error: Not found with response: no snapshot
2022-01-13T16:53:04.289Z ring-mqtt [Front Door] Failed to retrieve an updated snapshot, retrying in 1 second...
2022-01-13T16:53:05.625Z ring-mqtt [Front Door] Error: Not found with response: no snapshot
2022-01-13T16:53:05.625Z ring-mqtt [Front Door] Failed to retrieve an updated snapshot, retrying in 1 second...
2022-01-13T16:53:07.042Z ring-mqtt [Front Door] Succesfully retrieved updated snapshot for camera
```

**Comment by jackyaz** [comment]
All still ticking along nicely, i think we have a fix

**Comment by tsightler** [comment]
I did push a new version last night with slightly refactored code for this, hopefully I managed to do that without breaking anything.  Thanks for your testing and feedback, I'll probably push a 4.9.1 with this and a few other minor fixes, in the coming days.

**Comment by jackyaz** [comment]
I've just restarted the addon to clone your dev changes, I'll let you know if anything is amiss

**Comment by tsightler** [comment]
Version 4.9.1 has been pushed and includes this fix.  Thanks for the testing!
