### ISSUE TITLE
Location is Disconnected?

### ISSUE THREAD

**Issue by Coch** [tsightler/ring-mqtt#3]
Have configured a location in my ring account and a single Stickup Cam -- I've been running in a Docker container and not seeing anything published to MQTT for Home Assistant.

Based on the documentation, I ran ring-mqtt manually via 'DEBUG=* ./ring-mqtt.js'
`ring-mqtt Location <location-id> is disconnected +0ms`

I don't yet have an alarm system at this location -- but I did confirm by going through the debug output that the hardware ID for my camera is being returned:
 ```
 ring Making request: {
  ring   "method": "GET",
  ring   "url": "https://api.ring.com/clients_api/ring_devices",
  ring   "data": "",
  ring   "headers": {
  ring     "content-type": "application/x-www-form-urlencoded",
  ring     "authorization": "Bearer <long-string-that-probably-has-something-sensitive>",
  ring     "hardware_id": ",<legit-hardware-id-goes-here>"
  ring   }
  ring } +284ms
```

Not really sure why this would be returned as disconnected if there's an online device at the location.

**Comment by Coch** [comment]
Actually what's really odd is I commented out if/else for the disconnected portions and ended up with:

```
  ring-mqtt Location <location-id-goes-here> is connected +0ms
  ring-mqtt HASS config topic: homeassistant/binary_sensor/<location-id-gies-here>/32698296_motion/config +8ms
  ring-mqtt {
  ring-mqtt   name: 'Front Door Motion',
  ring-mqtt   unique_id: '32698296_motion',
  ring-mqtt   availability_topic: 'ring/<location-id-goes-here>/status',
  ring-mqtt   payload_available: 'online',
  ring-mqtt   payload_not_available: 'offline',
  ring-mqtt   state_topic: 'ring/<location-id-goes-here>/camera/32698296/motion/state',
  ring-mqtt   device_class: 'motion'
  ring-mqtt } +1ms
  ring-mqtt HASS config topic: homeassistant/switch/<location-id-goes-here>/32698296_siren/config +6ms
  ring-mqtt {
  ring-mqtt   name: 'Front Door Siren',
  ring-mqtt   unique_id: '32698296_siren',
  ring-mqtt   availability_topic: 'ring/<location-id-goes-here>/status',
  ring-mqtt   payload_available: 'online',
  ring-mqtt   payload_not_available: 'offline',
  ring-mqtt   state_topic: 'ring/<location-id-goes-here>/camera/32698296/siren/state',
  ring-mqtt   command_topic: 'ring/<location-id-goes-here>/camera/32698296/siren/command'
  ring-mqtt } +0ms
  ring-mqtt ring/<location-id-goes-here>/camera/32698296/motion/state OFF +2s
  ring-mqtt ring/<location-id-goes-here>/camera/32698296/siren/state OFF +3ms
  ring-mqtt HASS config topic: homeassistant/binary_sensor/<location-id-goes-here>/32698296_motion/config +28s
```

**Comment by tsightler** [comment]
Sorry for the delay, finally managed to find some time to work on this codebase.  The likely issue is that I had never tested this code for sites that only had cameras, i.e. no alarm.  The "Location <location-id> is disconnected" is because, if there is no alarm, there is no websocket connection as cameras only do polling.  The old code use the websocket to determine if the connection to Ring was up and available so if there was no alarm, thus now websocket, it would never publish any devices, which is why commenting that out would make it work.

Tonight I've pushed a major update to this codebase that includes a massive refactor, separating all devices into separate classes and in their own files.  This will hopefully make the code more maintainable.  I've also fixed a number of bugs (and probably introduced a few) and tried to generally make the code more robust, although there's still lots of error handling that could use improvement.

The new code should publish cameras even when there is no websocket connection (I've tested it by blocking the account I was using from seeing the alarm system and it seems to work).  I've also added event subscription monitoring on the camera devices so that hopefully they will reconnect after any internet or Ring services blips (without a websocket there's not a lot to monitor other than this).

Be aware that there were some breaking changes to the topic labels again to create consistency between alarms and cameras.  For cameras the motion and doorbell dings are now binary_sensor class, while lights are "light" class and "siren" is a "switch" class device.  This makes them line up accurately with the alarm device topics.  However, be warned, 3.0.0 is still in beta and I'm considering one final change for these to change all generic "state" to include a descriptor (i.e. light_state, motion_state, switch_state, co_state, smoke_state, etc)  I think that would make things 100% consistent across alarms and cameras so i'll probably code that up for 3.0.0b2 sometime in the next few days.  After that, there should be no more breaking changes and I will migrate ring-alarm-mqtt to this repo.

**Comment by Coch** [comment]
Thanks - ironically, this solved another one of my problems (added the alarm retrofit kit and not all my zones were showing up - fixed now!)

Is there a new environment variable for DOCKER for enable_cameras?  I noted everything worked fine when I started it manually, but noted that the config didn't seem to carry over...assuming I'm missing something in my docker-compose.yaml

**Comment by Coch** [comment]
Disregard - found it in the ring-mqtt.js
"enable_cameras": process.env.ENABLECAMERAS
Will try it out and advise

**Comment by tsightler** [comment]
Yes, I'm preparing this codebase to completely replace ring-alarm-mqtt, including those using the Hass.io addons provided by others, but Home Assistant has support for cameras via the native Ring component so I needed to make that optional and disabled by default.  I'm planning to decommission the old ring-alarm-mqtt.js later.

I added the support for the retro kit to this as part of the refactor since it was easy.  I'll close this for now but feel free to report any other issues that come up.
