### ISSUE TITLE
Modes of alarm

### ISSUE THREAD

**Issue by euhkah** [tsightler/ring-mqtt#309]
Hello, I installed ring-mqtt 4.9.0 on homeassistant, and my problem concerns the modes of alarm, and more precisely automation to send a notification of the state of the mode.
When the system reboot, I receive the notification 6 times, because the alarm goes 5 times for 1 second in "disabled" at regular intervals... (look at the picture).
![Sans titre](https://user-images.githubusercontent.com/9191753/150306698-675aee81-d4ab-4b8d-b4a4-b428cc06c981.jpg)

HomeAssistant 2021.12.10 on raspberry pi 4 (Home Assistant OS 7.1)
MQTT Mosquitto broker 6.0.1

**Comment by tsightler** [comment]
During startup ring-mqtt sends discovery information multiple times, specifically, after it detects a reboot it sends discovery every 30 seconds for 3 minutes (total of 6x).  This is done because, in some cases, HA will send the online event before it's really ready to process new devices (especially common when running on slower platforms like RPi3).  One option would be to set retain on discovery data, but this causes other support challenges and I don't plan to change this.

You'll have to modify your notification trigger to ignore these events.  I'm not an HA expert so I can't really help you here, but I'm guessing you could use some kind of condition, for example, if it was "disabled" for less than 1 second, etc., or perhaps a simple delay to notification after an HA restart.   As this is not really an issue with ring-mqtt per-se, I'm going to close this issue.  Good luck!
