### ISSUE TITLE
New Ring Floodlight Pro shows model as "unknown" and has no siren or light control

### ISSUE THREAD

**Issue by torekal** [tsightler/ring-mqtt#319]
I have both a Ring Floodlight Plus and just added a Ring Floodlight Pro (https://en-uk.ring.com/products/floodlight-cam-wired-pro)

The video stream and basic stats (sensors) for the pro are pulling through fine, but unlike the Plus it's not adding a "Siren" or "Light" control to it.

The model for the Pro shows as <unknown> where as for the Plus it shows "Floodlight Cam".

Is there a way I can force it to detect this as a Floodlight Cam or manually add those controls?

Thanks a lot

**Comment by tsightler** [comment]
My guess is that the Floodlight Pro is simply not yet supported by ring-client-api, as there is no model specific code in ring-mqtt itself as that is completely abstracted by the ring-client-api code.  Can you provide [device discovery](https://github.com/dgreif/ring/wiki/Data-Discovery) for this device?

I'm a little surprised that the light/siren doesn't show up even with the device being "Unknown" as this is initialized by the API based on the presence of specific keys being available in the device data so it makes me wonder if these new lights use different values, but maybe it's just because of the unrecognized type.  Regardless, the discovery data from above would make that clear and most likely, an issue would need to be opened on the ring-client-api project.

**Comment by torekal** [comment]
Thanks for your reply, I appreciate it. Though I'm struggling to follow your instructions, though it;s likely my fault for not giving enough info initially. 

I'm running HomeAssistant in docker.

I tried running the command npx -p ring-client-api ring-device-data-cli - but get errors which seem to indicate it's for homebridge not HomeAssistant?

But in case it's helpful, the error I get is:

root@hs:~# npx -p ring-client-api ring-device-data-cli
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/10183/lib/node_modules/ring-client-api/node_modules/ffmpeg-for-homebridge/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-for-homebridge@0.0.9 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffmpeg-for-homebridge@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-13T17_45_42_394Z-debug.log
Install for ring-client-api@latest failed with code 1

**Comment by davidadanieljr** [comment]
I had a similar issue as a work around I just created a sensor in my binarysensors.yaml file

  - platform: mqtt
    name: "Livingroom Front"
    state_topic: "ring/bf77b154-d303-46e4-505c-7bcb706f0b24/alarm/194a96f7-3542-4562-b15e 09454dde9cea/undefined/state"
    availability_topic: "ring/bf77b154-d303-46e4-505c-7bcb706f0b24/alarm/194a96f7-3542-4562-b15e-09454dde9cea/status"
   device_class: motion
    qos: 1

**Comment by tsightler** [comment]
Well, I wouldn't consider them my instructions per-se, they are from the ring-client-api project which is the client library used by this project.

To be completely clear, this discovery doesn't need to be run on the Home Assistant system, just on any system with NodeJS installed, which you can do on pretty much any computer.

**Comment by davidadanieljr** [comment]
I had a similar issue with a motion sensor, so I just created it manually in my binarysensors.yaml file. I used  mqtt explorer to grab the necessary topics 

- platform: mqtt
    name: "Livingroom Front"
    state_topic: "ring/bf77b154-d303-46e4-505c-7bcb706f0b24/alarm/194a96f7-3542-4562-b15e-09454dde9cea/undefined/state"
    availability_topic: "ring/bf77b154-d303-46e4-505c-7bcb706f0b24/alarm/194a96f7-3542-4562-b15e-09454dde9cea/status"
    device_class: motion
    qos: 1

**Comment by tsightler** [comment]
@davidadanieljr That should not happen and would appear to be a bug (topics should not have "undefined" in them for sure, but I'm not sure what kind of device that is).  However, I also don't think this behavior is related to this users issues as you are clearly posting about an alarm device and OP is talking about a camera.  I'm going to hide your comment to avoid confusing, but please feel free to open an issue to investigate your device.

**Comment by torekal** [comment]
@tsightler I didn't realise that command could be run on any system with NodeJS on it, thanks for that. 

I've got the JSON output now (which is fairly huge due to having quite a few ring devices). I've pulled out the new camera and the old camera separately. The new one is just called "Garden" the old one is called "GardenOld"


[Garden.txt](https://github.com/tsightler/ring-mqtt/files/8056422/Garden.txt)

[GardenOld.txt](https://github.com/tsightler/ring-mqtt/files/8056424/GardenOld.txt)

Hopefully I've done this right...

**Comment by tsightler** [comment]
@torekal Yep, that was perfect.  I looked through it and the only significant difference I see is that it's kind is "floodlight_pro" vs "floodlight_v2" and ring-client-api hasn't added this model to the type definitions yet, but the rest of the data returned by the API looks identical, other than feature differences between the devices.  I'm not sure why this is keeping the light/siren switch from appearing though, it should just list it as "Unknown Model" and move on.  I'll open an issue with ring-client-api project to get them to add the model to the list, but I'll need full debug logs from ring-mqtt to troubleshoot why the light/siren switch is not showing up.

**Comment by tsightler** [comment]
@torekal Any chance you could get the full ring-mqtt logs from an instance after startup/discovery, I'd like to see if there are any obvious errors there since I can't see any reason why this shouldn't work now.

**Comment by alvinchen1** [comment]
Haha @tsightler , I was trying to help you to go ahead and submit a bug report on the Pro Camera type and looks like we did it at the same time.  I am getting one tomorrow and will install it, and get your the ring-mqtt logs for you to help out.

**Comment by tsightler** [comment]
If you get a chance please try the dev branch which is using the new 10.0.0 beta version of ring-client-api and includes the floodlight pro.  I don't see how it would solve the issue with missing siren/light, but it should show the proper model number.  If you can't provide.

**Comment by alvinchen1** [comment]
Restarted Ring-MQTT while still on dev.  

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] ring-mqtt.sh: executing... 
-------------------------------------------------------
| Ring-MQTT with Video Streaming                      |
| Addon for Home Assistant                            |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt-hassio-addon |
-------------------------------------------------------
Updating ring-mqtt to the dev version...
Cloning into 'ring-mqtt-dev'...
Installing node module dependencies, please wait...
Updating ring-mqtt to the dev version...
-------------------------------------------------------
[cont-init.d] ring-mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
-------------------------------------------------------
ring-mqtt.js version: 5.0.0-beta1
Node version v16.13.2
NPM version 8.1.3
git version 2.34.1
```

New Camera installed and everything seems to be working.

![UnderPatio](https://user-images.githubusercontent.com/26409535/154816480-e8a8375b-4b7f-4eb1-8dd6-8024593a24e3.png)

```
2022-02-19T19:32:52.917Z ring-mqtt   New device: Under Patio (54e019da2588)
2022-02-19T19:32:52.917Z ring-mqtt               floodlight_pro

```
![image](https://user-images.githubusercontent.com/26409535/154816471-af5b5f28-5348-4061-a66c-8d4c5084cdde.png)

Following tested and working:
- Light 
- Siren 
- Motion Sensor 
- Snapshot 
- Event Stream 
- Live Stream
- Snapshot Interval (matches configured setting)
- Wireless (matches Device Health information)

Looks good!

**Comment by torekal** [comment]
Sorry for the delayed reply. Should I try moving over to this dev version (Which I assume means changing the git hub path in HACS?) or would those logs still be useful? thanks!

**Comment by tsightler** [comment]
This addon has nothing to do with HACS so you don't need to do anything there for sure (addons are completely different from HACS).  All you need to do to try it is to change the BRANCH configuration option in the addon to "dev" from the default "addon" and restart the addon, it will pull down the most recent dev version during startup.  To switch back just change the config option back to "addon".

**Comment by alvinchen1** [comment]
@torekal, 

> You can just use the BRANCH feature of the addon, in the addon configuration tab just change branch config option from "addon" to "dev" and restart the addon. On startup it will pull down the latest dev code and dependencies. If for some reason it doesn't work just change the config option back to "addon" and restart and it will revert to the code in the pre-built Docker image.

![image](https://user-images.githubusercontent.com/26409535/154873222-575b85d9-6e7f-4d8a-8495-9e7b033e8e5d.png)

Restart the Ring-MQTT addon and test.

If you want to revert back, change back to "addon" and restart.

**Comment by alvinchen1** [comment]
Hi @tsightler, I read your comments on https://github.com/dgreif/ring where the Pro is added to 10.0.0-BETA of ring-client-api.  Thinking of waiting to deploy 5.0.0 to main until ring-client-api deploys 10.0.0?  I'm happy on dev right now, have my new Floodlight Pros working.  For those who may chose not to run dev and stick to main 4.9, just might have to sit tight and wait a bit and curious your thoughts on timing release?  The new snapshot seems to work great on all 4 of my cameras.  Anything else I can provide for logs? Otherwise, I think we can mark this for closed and upcoming in 5.0.0?

**Comment by tsightler** [comment]
I'm not really sure on timing but I don't think it's really that dependent on ring-client-api going to 10.0.0.  I understand the changes to 10.0.0 pretty well and I've done a ton a stream testing to this point with good success so I'm comfortable with the use of the new streaming and snapshot API endpoints and the other changes are quite minimal.

Really 5.0.0 release is dependent on when I finish the refactor work that I had planned for the 5.x release, which are primarily to standardize configuration and state file management to work the same way across all install methods, and to complete the modularization of the mqtt/ring functions into their own classes.  I've tried to accelerate this somewhat, since there are a number of new devices and features that are blocked behind this, and I've made more progress than I expected by this time, but I now need to test all of the migration and failure cases for the various modes.  I tested most of the cases and fixed a few bugs with standard installs last night, but I still need to test the Docker migration cases, and then the re-test all of the failure cases (i.e. bad refresh token, unreachable servers, loss of network connection, etc).  Once I'm sure the migration hasn't broken any of this, I'll feel pretty good about releasing 5.x and then, after a few weeks if user migration goes reasonably well, I can start to work on device level state, which is the real goal of the 5.x release.

**Comment by alvinchen1** [comment]
Appreciate all your work on this.  Totally understand about the release and such.  Thanks again.

**Comment by tsightler** [comment]
Turns out I've hit quite a few unexpected challenges, not in the code refactor itself, which is going pretty well, but in the API libraries the code uses.  I spent most of this week tracking a memory leak issues which was causing the process to grow by about 100MB/day which I thought was due to some of my refactor, but eventually turned out to be caused by the latest MQTT.js versions.

Then more recently, while testing streaming, I've noticed that, while the new v10.0.0 ring-client-api code works well using the new WebRTC API, it has one side effect in that it uses a lot more CPU, which lowers the amount of streams that can be supported on given hardware by about half.  For example, with 9.24.0, I can get 6 streams going on my RPi4b, and even with 7 (which is all my cameras) it works with some minor artifacts.  However, with 10.0.0 and the new streaming components, artifacts start showing up at just 3-4 streams.  I don't really want to release with a regression like that so I either have to figure out a workaround or backport some of the device support to a custom 9.24.0 version.

In the interim I've been working on some of the other stuff I had planned for later versions of 5.x, specifically, splitting out the core functions into their own libraries and moving to a more event based approach instead of the spaghetti of function calls used previously (doesn't really impact function, but make it easier for me to maintain), and, more for users, implement device level state persistence so that, for example, you can set snapshots intervals and capabilities, or lighting durations, or bypass most on sensors, and those settings will be remembered in future versions.

I'm hopeful to finish most of this in the next 2-4 weeks and maybe, by then, I'll have figured out how to resolve the streaming issues.

**Comment by torekal** [comment]
> @torekal,
> 
> > You can just use the BRANCH feature of the addon, in the addon configuration tab just change branch config option from "addon" to "dev" and restart the addon. On startup it will pull down the latest dev code and dependencies. If for some reason it doesn't work just change the config option back to "addon" and restart and it will revert to the code in the pre-built Docker image.
> 
> ![image](https://user-images.githubusercontent.com/26409535/154873222-575b85d9-6e7f-4d8a-8495-9e7b033e8e5d.png)
> 
> Restart the Ring-MQTT addon and test.
> 
> If you want to revert back, change back to "addon" and restart.

Very late reply sorry, but today I've followed these instructions and moving to the dev branch has fixed it and I can now control the lights - thanks to both of you

**Comment by tsightler** [comment]
Closing this as v5.0.0 has finally been released!
