### ISSUE TITLE
RingMqtt reports unavailable in Home Assistant

### ISSUE THREAD

**Issue by heffneil** [tsightler/ring-mqtt#321]
So I have been running this docker for quite some time on two different hosts.  For some reason after random periods of time Home Assistant will show the motion sensor as "unavailable".  I have had the container run successfully for days and because it was a nuisance I was restarting the container every 45 minutes but even between those restarts, there were periods where it would show unavailable.  I am only relying on the motion aspect of the project and not the camera.  I am trying to santize my logs to provide them and I see a lof of data.  I have removed my SSID and I have removed the chime and camera paths in the logs.  I am unclear if I need to santize the recordingUrl.  If I could get some clarification I hope I can help with the logs.  Also I am not sure what I should see in the logs because even after it is showing unavailable I am seeing:

today at 6:27:18 AM2022-02-17T11:27:18.557Z ring-attr [Front Door] ring/unique-id/camera/other-id/motion/attributes {"lastMotion":1645097238,"lastMotionTime":"2022-02-17T11:27:18Z","personDetected":false,"motionDetectionEnabled":true}
today at 6:29:14 AM2022-02-17T11:29:14.150Z ring-mqtt [Front Door] New motion event detected, updating the event recording URL

I am running 
Mosquitto broker
Current version: 6.0.1

RingMqtt details:

today at 8:24:39 AM-------------------------------------------------------
today at 8:24:39 AM| Ring-MQTT with Video Streaming                      |
today at 8:24:39 AM| Docker Edition                                      |
today at 8:24:39 AM|                                                     |
today at 8:24:39 AM| Report issues at:                                   |
today at 8:24:39 AM| https://github.com/tsightler/ring-mqtt              |
today at 8:24:39 AM-------------------------------------------------------
today at 8:24:39 AM[cont-init.d] ring-mqtt.sh: exited 0.
today at 8:24:39 AM[cont-init.d] done.
today at 8:24:39 AM[services.d] starting services
today at 8:24:39 AM[services.d] done.
today at 8:24:40 AM-------------------------------------------------------
today at 8:24:40 AMring-mqtt.js version: 4.9.0
today at 8:24:40 AMNode version v16.13.2
today at 8:24:42 AMNPM version 8.1.3
today at 8:24:42 AMgit version 2.34.1

If I can provide anything else please let me know. Thanks so much!

**Comment by tsightler** [comment]
If all you want is motion sensing then why use this vs the native Home Assistant integration which should do this quite adequately?

Without full logs it's unlikely I will be able to help.  Feel free to send them to me via email (same username at Gmail) rather than posting here.  I know you may feel the urge to clean them before sending them to me, even privately, but remember that you've basically already included me into your circle of trust by running code from the internet that I wrote.  The recording URLs are only valid for like 15 minutes (you'll see them change regularly) so there should be no significant risk to sharing them and, without the authentication token, the other information like location/device IDs is unlikely to be useful, for example, Ring makes no attempt to hide them in the webapp as they are right there in the URL bar for anyone to plainly see.  The logs don't include things like your username/authentication token/address/etc.  Probably the most sensitive thing might be the livestream username/password, but you can feel free to change that to anything with a quick search/replace before sending it.

The online/offline camera status code is super simple, basically, there's a counter (heartbeat) that is set to a value of 3 when the camera is published and then any time a new polling data event is received (unlike alarms, cameras don't have a websocket to monitor so the API has to poll for status).  There's a simple monitoring loop which runs every 20 seconds and decrements the counter.  If the counter ever reaches 0, that means that multiple 20 second polling cycles have been missed so the monitor routine sets the device offline, if the counter ever goes above 0 again, then it means polling has resumed so the device is set online again.

If the device is going offline something is causing this polling to stop.  The polling actually happens within ring-client-api, not ring-mqtt itself, the ring-mqtt code is just a consumer.  Are you seeing the camera availability topic being set offline (again, logs would help here)?

Generally, the only thing that will cause the polling to stop is network or authentication issues as the ring-client-api code is written to just try forever.  Do you definitely have time sync configured correctly?  This is important for reliable communications with the Ring API and one that has caught a few users over the years.

**Comment by tsightler** [comment]
Closing this issue since there has been no response in 7 days.
