### ISSUE TITLE
Live and event streams error out if "Ring Edge" local SD video storage enabled on Ring Alarm Pro

### ISSUE THREAD

**Issue by madsmooth** [tsightler/ring-mqtt#338]
Not sure if this ticket should be here and/or the  ringapi or homebridge projects. Running ring-mqtt as an add-on in homeassistant on a raspberry pi4 (5 floodlight cams, a doorbell and recently added Alarm Pro with sensors). Everything works great over mqtt and in homeassistant when Ring Edge is disabled. When enabling Ring Edge for a given camera, the addon reports error starting live video streams. When disabling Ring Edge for a given camera streaming works again. For a camera the event stream plays the last non-edge recordings but never any sd card recording like in the native ring app or web page. Let me know if there is anything I can test or try out to help!

## Important note regarding camera support    
The ring-mqtt project does not magically turn Ring cameras into 24x7 CCTV cameras suitable for continuous streaming.  Ring cameras are designed to work with Ring cloud servers for on-demand streaming based on detected events (motion/ding) or interactive viewing.  Even when using ring-mqtt, all streaming still goes through Ring cloud servers and is not local.  Using this project for continuous streaming is not a supported use case and attempts to do so will almost certainly end in disappointment.  Any support cases opened for issues with continuous streaming (i.e. more than one streaming session back-to-back) will be closed as unsupported.  This includes use with NVR tools like Frigate or motionEye.

## Please read before opening a bug report
This is a community project and opening an issue indicates that you are prepared to interact as a community member.  Note that this does not mean that I expect you to be a developer or a super tech guru, but you must at least be willing to put some time and effort into helping me understand your environment, answer questions, provide logs, and do so in a reasonably timely manner.  In general I will do my best to help whenever I can, but I answer these issues on my own personal time and my effort to do so will largely be commensurate to the effort that you put in.  I'm sorry for being so blunt, but recently, the number of people that opened issues with a single sentence, or that open an issue and then never respond to any requests for additional information, has grown to the point that it really makes working on this project less than enjoyable, and that puts the entire project at risk.

I don't want to discourage users from opening an issue if there is a problem, I promise that, if the appropriate effort is made, I will do my best to meet that effort, assuming available time.  Please remember that I am not associated with Ring in any way, other than the fact that I own some of their products, I can't help you solve problems with your Ring devices and I can't do anything about their limitations, I suffer with those limitations just like you do.  The goal of this project is simply to make it as easy as possible to integrate the features of Ring products the home automation platform of your choice.

### Describe the bug
A clear and concise description of the issue.  Please enter a brief summary of the issue in the title above as well.

### Describe your environment
Please include details on your enviornment, including OS versions, platform, etc.

### Describe your settings and what you've tried
Please make sure to share you configuration settings (other than sensitive information like token, etc) and anything you have done to attempt to solve the problem to this point.

### Debug Logs
In many cases the only way to effectively troubleshoot an issue is to review the logs, without this, I'll mostly just be guessing at the problem.  Please run the script with DEBUG=ring-* enabled (note this is enabled by default for the addon and Docker versions) and collect logs.  Logs will likely contain potentially sensitive information so you probably do not want to post them publicly on Github, which I certainly understand.  Please feel free to send the logs, or a link to download them, to my personal email address, which is the same username at gmail and be sure to reference the open issue by number or link.

**Comment by tsightler** [comment]
Ring Edge is not supported as it dramatically changes the method to access streams and, more importantly, enables end-to-end encryption which is already not supported.  I know the maintainer of ring-client-api has been working on this for the v10 release of the API, but I don't think he's quite there yet and I have no idea when it will be supported or if it will ever be.  If it is eventually included in ring-client-api then I'll be able to add it here, or perhaps it will "just work". 

I'll add a note that this is not supported to the main page and FAQ and close this for now since this is not a bug but rather a known limitation and there's nothing I can actually do about it.

**Comment by madsmooth** [comment]
Makes sense. I assumed it was not supported but it was not explicitly clear so adding verbiage about that would be beneficial to the user community. I wanted to share my findings in case it might help development. I will investigate in the ring-client-api project. Thanks!

**Comment by tsightler** [comment]
I feel like it's pretty clear as there is section that explicitly list what is supported, and it's not on there, but it seems like other people somehow don't come to this conclusion.  It's very difficult to know what things Ring has that aren't supported and it seems like mostly a waste to list everything that doesn't work since that's a forever growing list that, 90% of the time, I won't even be aware of since I don't follow Ring's products that closely.

You can see some of the work ongoing for Ring Edge support in this branch:
https://github.com/dgreif/ring/tree/ring-edge-websocket

**Comment by tsightler** [comment]
If you happen to still be following this, the current dev branch has an initial cut a supporting Ring Edge enabled devices.  I've not been able to test this end-to-end myself since I don't have , but I was able to force the code to use the new code path and everything seems to work.  Note that the server running ring-mqtt will need to have network access to the Ring Alarm Pro base station.  Very interested in hearing any results as I'd really like to have this officially supported as part of the v5 ring-mqtt release which I hope to make in the next few weeks.
