### ISSUE TITLE
Failed to call service select/select_option. must contain at least one of entity_id, device_id, area_id.

### ISSUE THREAD

**Issue by jackyaz** [tsightler/ring-mqtt#353]
i'm seeing the above error, I think since updating to 2022.4.X, when changing the event select entity that is created by this addon

Please let me know what information you need to look into this further?

I'm using a Ring Doorbell 2 (battery)

**Comment by tsightler** [comment]
How are you attempting to change the option?  Based on the message, which is clearly a message from Home Assistant, not ring-mqtt, you are attempting to call the select service and not providing the required data that this service needs.  Do you have any issues changing the setting via the UI?  Please provide details on exactly what you are doing and how you are calling this service.

**Comment by jackyaz** [comment]
I'm changing the option both via an entity card and on the device page itself. For the latter, go to Configuration, Integrations, click Devices under MQTT (or whatever the integration is called for you), then the doorbell entity.

It does seem like something that an automatons would usually fire on change but i have no automations tied to the entity

**Comment by tsightler** [comment]
But do you have any automation tied to the device or area, or anything else that might trigger when the value is changed?  This pretty much has to be from an automation as it's a call to an HA service and ring-mqtt doesn't make any direct calls to any services, nor is it even able to do so as its only interface to Home Assistant is via MQTT, which provides no service call method.  The likely reason it only showed up after 2022.4.X is because of a change made by Home Assistant, see the very first entry in [breaking changes](https://www.home-assistant.io/blog/2022/04/06/release-20224/#breaking-changes) section of the release notes about service calls.  In prior versions this error would likely have been silently ignored.

My suggestion is to change the value, and then immediately go to Configuration...Automations, sort by last triggered, and see if anything there was triggered at the same time as you made the change.

**Comment by jackyaz** [comment]
No automations are reporting as triggered when changing it. I'll keep digging

**Comment by jackyaz** [comment]
Interestingly, snapshot mode on the device also fires the warning

**Comment by tsightler** [comment]
Maybe a scene?  Or do you have anything external like Node Red or something that does external service calls?  Do you mean just enabling/disabling snapshot mode fires the warning, or you get the warning on every snapshot?  Also, does everything work fine and it's just a warning?  I've tried and can't seem to reproduce this in my two instances and I just don't see how it could be in ring-mqtt since it can't even call a service.  But maybe a state update on MQTT internally calls a service?  But that wouldn't really explain why I don't see this behavior anywhere.

**Comment by jackyaz** [comment]
I think this might actually be a bug with the Entities card. I no longer get errors on the Device page and see the mqtt events firing when it changes. When changing via an Entities card the error appears and no mqtt events appear in the logs

**Comment by tsightler** [comment]
Hmm, I added an entities card to my UI with the event select and can change it with no warnings.  Maybe try removing the entity and re-adding it to the card?

**Comment by jackyaz** [comment]
I'm really sorry for the inconvenience :(

I went diving through the debug console in the browser and found the broken call is actually coming from the "Honeycomb menu" frontend mod from HACS. I don't actually use that mod anywhere so removed it, and no more error.

Sorry to bother you!

**Comment by tsightler** [comment]
Glad you got it sorted and that my analysis that this couldn't be coming from ring-mqtt was correct.
