### ISSUE TITLE
Possible issue with snapshots on Battery Powered Cameras?

### ISSUE THREAD

**Issue by alvinchen1** [tsightler/ring-mqtt#354]
### Describe the bug
Noticed that the Snapshot image for my single battery powered camera does not appear to update until Ring-MQTT restarts.  I know you had mentioned that you don't have any battery powered cameras so might not be able to test this or might not be aware of the issue, so wanted to see if maybe it was me, or maybe it was something else, just in case.  If this looked like there might be a problem, of course, I'd be happy to try and test.

### Describe your environment
Ring to MQTT, Dev Channel, 

### Describe your settings and what you've tried
Have noticed in the last few days (not sure when I first noticed this), but the snapshot for my one battery power camera (Battery Powered Spotlight Camera) does not update.  Both the camera.back_yard_snapshot and camera.back_yard_event show the same errant thumbnail.

The device info shows updating.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/26409535/163183304-41094c5f-1e4c-46c8-aa47-a30f39703295.png">

Snapshot interval is 600 (correct), mode is auto, and the Snapshot itself is idle (like all other cameras)

<img width="340" alt="image" src="https://user-images.githubusercontent.com/26409535/163183568-d75e7d13-6f07-4cde-9614-60397a092095.png">

Here's a screenshot of the four cameras last night (when it was dark)
![image](https://user-images.githubusercontent.com/26409535/163183987-b9379bc9-688e-4a5f-be14-34e8f15c465c.png)
Note the back yard (bottom right is daylight).

This morning, I restarted the Ring-MQTT addon and got the following slice of the log

2022-04-13T09:30:25.992Z ring-mqtt [Back Yard] Successfully retrieved updated snapshot
2022-04-13T09:30:26.002Z ring-mqtt [Back Yard] ring/dqcjx5-pcv7-0/camera/909a77ff8182/snapshot/image <binary_image_data>
2022-04-13T09:30:26.004Z ring-attr [Back Yard] ring/dqcjx5-pcv7-0/camera/909a77ff8182/snapshot/attributes {"timestamp":1649842226}

And then here's a screenshot of the four cameras showing them all aligned to the darkness this morning.

![image](https://user-images.githubusercontent.com/26409535/163184299-cd32f239-f3d9-46a5-ae2e-8efb37ab1866.png)

Fast forward three or so hours and now the Back Yard hasn't updated

![image](https://user-images.githubusercontent.com/26409535/163184395-0f58b8af-74c6-4529-b5d5-fc6742dd32da.png)

Even though in the native Ring App, the snapshot image has updated (and there has been detected movement as I moved my car)

![image](https://user-images.githubusercontent.com/26409535/163184507-a96165ce-f4e4-44a3-a315-c91deff3ac1b.png)

Attached is the MQTT Diagnostics for the Back Yard Camera
And one for a working Front Door Camera

[mqtt-ff89701f254e706b768e469269595b4f-Back Yard-dd169e6fd5138b7ff7f2f4cbd82e65ff.json.txt](https://github.com/tsightler/ring-mqtt/files/8481596/mqtt-ff89701f254e706b768e469269595b4f-Back.Yard-dd169e6fd5138b7ff7f2f4cbd82e65ff.json.txt)

[mqtt-ff89701f254e706b768e469269595b4f-Front Door-66b4c66b2f18fd0ec9f32d8a8631636d.json.txt](https://github.com/tsightler/ring-mqtt/files/8481604/mqtt-ff89701f254e706b768e469269595b4f-Front.Door-66b4c66b2f18fd0ec9f32d8a8631636d.json.txt)

Pardon my light troubleshooting, but it looks like most of the screenshots key off attributes.entity_picture
which for all cameras appears to be "/api/camera_proxy/[camera]_snapshot?[token]"
So I'm guessing that something inside camera_proxy is the next place to look, but I couldn't figure out how to look in there to see if something is updating or changing for the three cameras that work, but not for the one that doesn't.

As always, if you have any suggestions for any information I can help to provide you, I'm happy to do so.

**Comment by tsightler** [comment]
Unless I'm misunderstanding something, I think what you are seeing is expected behavior of the current dev branch. The current behavior of auto mode (a new option in v5) in the dev branch is as follows:

Wired/Full power mode cameras: Motion and interval snapshots enabled
Battery/Low power mode cameras: Motion snapshots enabled, interval snapshots disabled

I went with this because of consistent complaints about battery drain with battery powered cameras.  If a user wants both interval and motion snapshots for a battery camera the snapshot mode must be explicitly set to "all".  I'm not 100% sure I will stick with this for the final release, but the thought process is that I wanted the default mode to be something that would definitely have 0% chance of any battery impact since some people install the addon and then don't even use the camera snapshot features but I want to have camera support enabled by default in v5 since a lot of users seem to struggle with reading the documentation and end up asking in random places why their camera sensors/switches don't show up (this is especially common for users that only have cameras).

**Comment by alvinchen1** [comment]
Oh, and apparently, I am one of those who have problems reading the documentation.  Yes!  That is exactly correct.  I gotcha, set to interval snapshots all and will test.  I think that's exactly it.  My battery camera has two batteries and is on a solar panel, so I am not concerned about battery life on the camera (never gets below 80%).  

So I went through the ring app to look over my configuration completely before creating this, thinking maybe I had something not set.  I even disconnected the camera from my wifi, and pulled the batteries to reset it just to make sure there wasn't something that a good old reboot wouldn't fix.  Then I switched from default channel (from dev channel) and it seemed to work, so that's why I filed this.  I also went through the Ring App to make sure I had everything set. I had the camera set to 5 minute snapshots which is well within my battery life tolerance.  The other options are 14 minutes and 1 hour.  


So interesting discussion as to whether or not it makes sense to change the battery ones to just Motion snapshots.  I can totally see why it would make sense, you are right about users reading docs and developer notes.  But I think a user who has it set there in Ring App probably wants Ring-MQTT to behave at least at the same level, provided it doesn't cause additional battery drain.  And so far what I can see, the only thing that might cause additional drain would be triggering live events, but pulling existing data that the camera has already uploaded to the Ring Cloud (such as snapshots, and old events) shouldn't cause additional drain regardless of the Ring-MQTT settings, should it?  Also, the Ring App does gently alert the user of battery consumptions when adjusting the Snapshot interval (as well as KINDLY forwarding them to the Amazon page to buy the solar panel, nice).  So I totally understand your precaution and design choice, and yeah, I should probably read the documentation more clearly, which is funny cause I think I've spent a lot of time in both your code and documentation... :)

**Comment by tsightler** [comment]
> Oh, and apparently, I am one of those who have problems reading the documentation. Yes!

Well, I haven't yet updated the docs for the dev branch since it's still in a massive state of flux right now, so there's nothing to read, thus I can't blame you on this one!

However, I see posts on Reddit, on HA forums and really, in all kinds of places, especially with camera only users, that install the addon or the docker image and become frustrated with the fact that they don't see any devices and think something is wrong.  Also, there are lots of users of ring-mqtt that don't use HA and have no need for images/snapshots/video support at all, so I need to make sure those cases are 100% non-impacting to battery life if I want to have cameras enabled by default.

> But I think a user who has it set there in Ring App probably wants Ring-MQTT to behave at least at the same level, provided it doesn't cause additional battery drain

The problem is, it does cause additional battery drain, unless you are lucky.   The issue here is that, as of today, ring-mqtt is aware of what interval the snapshot capture setting is set to, but it has no idea when those snapshot are taken, it just uses those settings as a guideline for how often to take it's own snapshots.  So, for example, if snapshot capture is set to every 5 minutes, ring-mqtt detects this and also takes snapshots every 5 minutes, but there's no guarantee that both of these snapshots are taken at the same time.  The camera may take its snapshot at 12:03, and the ring-mqtt then takes its snapshot at 12:05, which means two wakeups every 5 minutes instead of one and thus twice the battery usage.

The new snapshot API introduced in ring-client-api v10 does have some cool stuff, like allowing the request of the most recent snapshot within a given timeframe, but my initial cut at playing with this didn't seem to work as expected.  If I can figure that out it might allow more granular control of all this or even lead to the possibility to align the interval times, but I sure as heck haven't had time to try to dig into all of that and, for my case, it's irrelevant since my cameras are all wired, so it's also a little difficult to find the motivation.

**Comment by alvinchen1** [comment]
Ah!  That makes a lot more sense.  I just assumed that Ring-MQTT was simply pulling the captured cloud uploaded interval snapshot not actually taking one at its own interval itself.  That makes sense as to how that could possibly increase battery drain.  Good to note and much better now I understand.

As usual, thanks for your work on this.  I hope I'm not being too annoying asking you all these questions and filing all these bugs.
