### ISSUE TITLE
RTSP Snapshot Camera

### ISSUE THREAD

**Issue by broyuken** [tsightler/ring-mqtt#358]
Is there any way you could add the snapshot camera as an rtsp camera?

the use case is to add the snapshot cam into frigate for object detection. Specifically my dogs to know when they’re at the door.

**Comment by tsightler** [comment]
This certainly isn't something I'm interested in adding.

Will Frigate even work with such low frame rate feeds?  I was under the impression it required a minimum frame rate of a few frames/sec to even be useful.  If it does work, doesn't Frigate just use ffmpeg for it's stream input?  At least I thought that was the case.  If so, you should be able to create a long-lived token in HA and use the camera proxy API as the source, which is basically what I'd end up having to do in ring-mqtt anyway since you can't just send snapshots via RTSP.

**Comment by broyuken** [comment]
Thanks, I’ll look into the camera proxy api, didn’t know that was a thing. It may work with frigate, not sure, but I’ll give it a shot.

**Comment by broyuken** [comment]
So I've looked into this a bit and I can't seem to find a way to get the token to update as it changes in HA. I can do something like this.

http://10.0.86.138:8123/api/camera_proxy/camera.front_door_camera?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

but after a few minutes the token changes and I need to manually run the api call to get a new token.

http://10.0.86.138:8123/api/camera_proxy/camera.front_door_camera?token=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

Do you know of a way to make this dynamically change? I'm hoping it's just something simple that I'm missing.

**Comment by tsightler** [comment]
From within HA you can always just use a value template (just like the Still Image URL).  For example, you could just write an automation that saved or pushed the images somewhere using the value template.

if you're outside of HA then, as mentioned above, you'll need to manually generate a long lived token for authentication to HA vs trying to use the dynamic, short-lived token which is primarily for use within HA itself.  Long lived tokens can be generated from the HA UI by just going to the profile of the logged in user and scrolling down to the long-lived access tokens section.

I'd personally create a separate, restricted account, login with that, and generate a token for it, then use that to authenticate.

Realistically however, I'm not a Home Assistant expert, I really use it only very lightly, so you might be better asking these questions on the HA forum.

**Comment by broyuken** [comment]
I tried using the long lived token, but it's saying unauthorized. 

http://10.0.86.138:8123/api/camera_proxy/camera.front_door_camera?token=longlivedaccesstoken

It seems like for ring we HAVE to use the token on the entity, is this your understanding as well?

**Comment by tsightler** [comment]
Yeah, you can't just tack the long lived token onto the end like that, the long lived token is the authorized the client using normal HTTP authentication, which means it needs to be passed as part of the HTTP headers.  Alternatively, I think you can just add the IP address of the system that needs access as trusted in configuration.yaml and then it doesn't need authentication.  You can also just create an automation to save the image to the same file and use that, or to push it somewhere.

But really, these are Home Assistant questions, not really related to this project specifically.  There's nothing special about Ring cameras in HA, the snapshot cameras are just generic MQTT camera entities and behave the same for all such cameras.

I'm going to close this issue again because this is not an issue with this project that needs my attention.  If you'd like, you can open a thread in the discussion section, and maybe someone else there would be interested, or, even better, the HA forums, since there are already threads there on using the camera proxy from external sources.

**Comment by broyuken** [comment]
I ended up just using deepstack and it’s working great

**Comment by tsightler** [comment]
Great!  Glad you found something that works for you!
