### ISSUE TITLE
`className` of Window Contact Sensors

### ISSUE THREAD

**Issue by respectTheCode** [tsightler/ring-mqtt#36]
It looks like all contact sensors are reported with the `className` `door`. Would it be possible to detect the ones that are windows in some way?

**Comment by tsightler** [comment]
I don't know how it would be possible to autodetect this, other than something super unreliable like parsing the sensor name and changing the class to window if the name included the word window.  I had considered this at one point, or even having a separate file where users could create an override for device classes because generic sensors all just look the same but could be sensing a variety of things.  However, in the end, I just haven't had time to add those types of things to the code.

I will consider patches if they do things in reasonable ways.

**Comment by respectTheCode** [comment]
Without thinking about it I named all of my sensors with `Door` or `Window` in the name. I think this is a reasonable start.

It looks like this will be a really simple change. I will take a stab at it tonight.

**Comment by tsightler** [comment]
I agree it should be pretty simple.  I don't happen to have any sensors on any windows, but all of my door sensors also happen to include the word door.  I think best would be to use it as a "hint", i.e. if it detects the string "Window" in the name, then override the class.  Should be really easy.  I'm still not sure if I like the idea overall, but it's the best I've got!

**Comment by tsightler** [comment]
Thanks for the PR.  I have merged this into the master branch.
