### ISSUE TITLE
Register request has failed with Error=PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by jackyaz** [tsightler/ring-mqtt#366]
I'm seeing this error after upgrading to 5.0.1
```
Register request has failed with Error=PHONE_REGISTRATION_ERROR
```

Where should I look to fix this? I'm assuming I have something misconfigured somewhere

**Comment by tsightler** [comment]
Unless you are getting these continuously there's nothing to fix, it's just a warning and the very next line should clearly say "Retry #..." and eventually it will work (I've only ever seen it fail 2-3x during startup at most).  Unfortunately, this message is output directly from a dependency so I'm unable to trap it.

**Comment by jackyaz** [comment]
Ah right, I do see just 2-3 and then no more. I wasn't sure if it was giving up after those attempts or not

**Comment by SultanSGillani** [comment]
This is happening continuously for me now. 

ring-mqtt  | Register request has failed with Error=PHONE_REGISTRATION_ERROR
ring-mqtt  | Retry... 1
ring-mqtt  | Register request has failed with Error=PHONE_REGISTRATION_ERROR
ring-mqtt  | Retry... 2
ring-mqtt  | Register request has failed with Error=PHONE_REGISTRATION_ERROR
ring-mqtt  | Retry... 3
ring-mqtt  | Register request has failed with Error=PHONE_REGISTRATION_ERROR
ring-mqtt  | Retry... 4
ring-mqtt  | Register request has failed with Error=PHONE_REGISTRATION_ERROR
ring-mqtt  | Retry... 5
ring-mqtt  | Register request has failed with Error=PHONE_REGISTRATION_ERROR

**Comment by tsightler** [comment]
I suspect it will eventually succeed as Ring quite regularly has short outages in push notifications that don't make their status page.  Realistically there's not much I can do about it anyway as the code that registers for push notifications is well below ring-mqtt level.  I've figured out a crude way to hide this message so that's likely what I will do in future versions since people seem so concerned about it.
