### ISSUE TITLE
Motion snapshot is not updating

### ISSUE THREAD

**Issue by motarek17** [tsightler/ring-mqtt#370]
Hello,

the snapshots are not updating with motion, I have the below error in add-on log.

Log: Motion snapshot needed but notification did not contain image UUID and battery cameras are unable to snapshot while recording

The camera is not recording and I do not have a ring protect plan, do I have to have it to get updates?

I am using Ring doorbell version 1 connected to a solar panel, the add one version is 5.0.1, homeassistant version is 2022.5.4, Supervisor version is 2022.05.2 and Home Assistant OS 7.6.

Thanks a lot,

**Comment by tsightler** [comment]
> The camera is not recording and I do not have a ring protect plan, do I have to have it to get updates?

What do you mean it is not recording?  Ring cameras generally always record on motion events, at least all motion events for which they notify.  I'm not aware that it's possible to get a Ring camera to send a notification but not record the event.

> The camera is not recording and I do not have a ring protect plan, do I have to have it to get updates?

This is covered in the [FAQ](https://github.com/tsightler/ring-mqtt/wiki/Frequently-Asked-Questions-(FAQ)#snapshots) and in the [Upgrading to 5.x](https://github.com/tsightler/ring-mqtt/wiki/Upgrading-to-v5.x#push-notifications) document.  Summary is, yes, at least a basic Ring Protect subscription is required for battery/low-power cameras to provide motion snapshots as it's the only way to get a snapshot before the recording starts.

Basically, when motion is detected, the Ring camera immediately takes a snapshot just before it starts recording.  It sends this snapshot to Ring cloud servers as part of the event indicating that motion was detected for the camera.  When rich notifications are enabled, the push notification includes the UUID of this snapshot so that ring-mqtt can retrieve this image.  Wheb rich notifications are not enabled, the motion notification does not include this UUID and, by the time the notification is received by ring-mqtt, the camera's local recording process has already started, thus there's no way for ring-mqtt to take a snapshot because battery/low-power cameras don't have the ability to take a snapshot while recording.  Unfortunately, rich notifications require at least a basic Ring Protect Plan.

**Comment by motarek17** [comment]
Got it, thanks a lot!

Apologies, I was not aware that the camera will record the motion event by default even when I am not subscribed to a protect plan.

Cheers,
