### ISSUE TITLE
Bypass mode is less useful

### ISSUE THREAD

**Issue by bdrewery** [tsightler/ring-mqtt#373]
Please bring back the global switch, or allow confirming bypass _per arm mode_, or adding _arm mode X with bypass_ services. The breaking change made here forces my automations to be more complex and I don't see how trivial 1 switch controlling global behavior would be a problem worth breaking users _security systems_.

**Comment by tsightler** [comment]
Sorry.

**Comment by tsightler** [comment]
I'm sorry that you find the new bypass method less useful you _for you_. The goal of the change was to address long-standing complaints from users that the global bypass mode was too complex for simple, common cases and not flexible enough for other cases.  Now many of those cases require only very light automation or, in some cases, no automation at all.

Regarding breaking users _security systems_, well, I'd say this is just a personal project that I wrote and shared with the public, it's not a product.  People pay nothing for it and are not entitled to any specific service level.  I did bump the major version and provide ample warning in the release notes regarding 5.0 being a breaking release and even suggested not updating if you value stability.  But, again, it's also just a personal project, so you're 100% welcome to fork a prior version and maintain it yourself since, as you say, it is trivial, maybe people will even prefer to use your version, and that's 100% OK.

All of that being said, I'm open to consider additional improvements that might make use of bypass mode easier for you.  I had originally considered keeping the global bypass switch and having individual device default to "global" bypass mode, but honestly, the most useful thing would be to describe your automations/use case in more detail.
