### ISSUE TITLE
The ring-mqtt docker container is not publishing messages to mqtt

### ISSUE THREAD

**Issue by SultanSGillani** [tsightler/ring-mqtt#375]
### Describe the bug
Ring-mqtt is not publishing anything to mqtt

### Describe your environment
Docker

### Describe your settings and what you've tried
I have the config.json setup correctly with no issues showing in ring-mqtt for docker. 

### Debug Logs
mqtt logs show this but in the mqtt app it does not show the ring topic being published.

```
1653160288: Received PINGREQ from mqttjs_3a935d4a
1653160288: Sending PINGRESP to mqttjs_3a935d4a
```
Is what shows only for the ring-mqtt docker container.

Running netcat on the ring-mqtt server shows the url to has the port open based on my settings. I do not have mqtt set as needing a user or password as homassistant, zwave, can publish without it.

The ring-mqtt logs really does not show anything useful.

```
ring-mqtt  | Running ring-mqtt...
ring-mqtt  | 2022-05-21T19:10:24.787Z ring-mqtt Detected runmode: docker
ring-mqtt  | 2022-05-21T19:10:24.789Z ring-mqtt Configuration file: /data/config.json
ring-mqtt  | 2022-05-21T19:10:24.791Z ring-mqtt MQTT URL: mqtt://10.10.0.45:1883
ring-mqtt  | 2022-05-21T19:10:26.128Z ring-mqtt Reading latest data from state file: /data/ring-state.json
ring-mqtt  | 2022-05-21T19:10:26.216Z ring-mqtt Attempting connection to Ring API using saved refresh token...
ring-mqtt  | 2022-05-21T19:10:26.535Z ring-mqtt Successfully established connection to Ring API using saved token
ring-mqtt  | 2022-05-21T19:10:27.556Z ring-mqtt Successfully saved updated state file: /data/ring-state.json
ring-mqtt  | 2022-05-21T19:10:28.536Z ring-mqtt Attempting connection to MQTT broker...
ring-mqtt  | 2022-05-21T19:10:28.578Z ring-mqtt MQTT connection established, processing Ring locations...
ring-mqtt  | 2022-05-21T19:10:29.958Z ring-mqtt ------------------------------------------------------------------------------------------
ring-mqtt  | 2022-05-21T19:10:29.958Z ring-mqtt This account has access to the following locations:
ring-mqtt  | 2022-05-21T19:10:29.959Z ring-mqtt            Home (***)
ring-mqtt  | 2022-05-21T19:10:29.959Z ring-mqtt
ring-mqtt  | 2022-05-21T19:10:29.959Z ring-mqtt IMPORTANT: All alarm and smart lighting hubs at these locations *MUST* be online
ring-mqtt  | 2022-05-21T19:10:29.959Z ring-mqtt            or device discovery for that location will hang indefinitely!
ring-mqtt  | 2022-05-21T19:10:29.959Z ring-mqtt            If desired, use the "location_ids" config option to restrict discovery
ring-mqtt  | 2022-05-21T19:10:29.960Z ring-mqtt            to specific locations. Please see the documentation for more details.
ring-mqtt  | 2022-05-21T19:10:29.960Z ring-mqtt ------------------------------------------------------------------------------------------
ring-mqtt  | 2022-05-21T19:10:29.960Z ring-mqtt New location: Home (***)
ring-mqtt  | 2022-05-21T19:10:48.256Z ring-mqtt Home Assistant state topic homeassistant/status received message: online
ring-mqtt  | 2022-05-21T19:10:48.256Z ring-mqtt Home Assistant restart detected during existing republish cycle
ring-mqtt  | 2022-05-21T19:10:48.256Z ring-mqtt Resetting device config/state republish count
```

**Comment by tsightler** [comment]
There's an important notice there in the logs, I'm not sure if you've read it.

**Comment by SultanSGillani** [comment]
Huh? I hid my location I'd from thiss issue. Not sure what you mean

**Comment by SultanSGillani** [comment]
Nevermind. Thanks

**Comment by SultanSGillani** [comment]
Just an fyi, thanks. I realized the bridge I had was not connected. However I am not in school anymore(this isn't homework), so it would have been appreciated if you would have just been nice, and just told me your thoughts instead of having me waste more time trying to figure this out by your "hint".

**Comment by tsightler** [comment]
So let me get this straight, you are scolding me for not being nice but you didn't respect my time enough to just ask this on the discussion group here on Github, where other users might be able to help you, or to, you know, actually take a few minutes to read the logs you were posting, or try to figure out what those logs were telling you, or perhaps to double check your setup and make sure everything was online and working 100% before assuming it was a bug?  You couldn't even be bothered to read the issue categories and at least open a "support" issue but rather went straight for "bug".  You opened the issue completely in a "matter of fact" wording, no "thanks for the great project but I can't get it to work", or "I'd appreciate it if you could help me" and then this lovely icing on the cake:

> The ring-mqtt logs really does not show anything useful.

Pretty insulting when the message telling you what you should check is, quite literally, right there.  So I take a couple of seconds of my personal time to type a quick message, in the middle of my wife's birthday party, just because I wanted to get you an answer as quickly as possible, and that message suggests that you should read the important notice in the logs because I thought it might not be clear to you that this is what was happening.  Could that message have been worded better?  Well, sure, and you would have received a better message later, when I had more time to write a proper answer (I was already typing it when you closed the issue), but, in the end, it was still enough to get you to the resolution.

> having me waste more time trying to figure this out by your "hint".

Are you serious!?!?  You know I'm not your personal support person, I don't owe you any response _*AT ALL*_!  You downloaded someone's personal project from the web, a project that I've spent literally 100's of hours writing and testing, creating documentation, implementing and testing dozens of features that I don't even use, just because people ask for them, crafting log messages to help users know what to do when things don't work, answering and closing over 500 Github issues and dozens if not hundreds more on the Home Assistant forums, all shared 100% for free here, but I _wasted your time_?

**Comment by SultanSGillani** [comment]
Wow. Sorry for not following etiquette. This was the only time I have ever opened up an issue here. I appreciate your work but what you said is a little harsh. I apologize but I don't think your response is warranted. 

I am sorry again and thanks for your personal contribution. I value your work and think it is pretty extraordinary. 

I won't bother you again, sorry for the trouble. 

I am not being sarcastic here. Just was asking a question. I just felt like you were talking down to me is all. 

Thanks again and did not expect that response. Good luck in the future and I hope you are successful.

**Comment by tsightler** [comment]
@SultanSGillani I don't want you to feel bad and I apologize for responding harshly, I should have just not responded at all, but somehow it just really struck me poorly to be told I could "just be nice" and that I was somehow wasting your time when I was literally just trying to help as quickly as possible.  Looking back at it, I guess I can at least see how my first response could have been interpreted as talking down, even if that wasn't my intent, I'll try to do better with my wording in the future.

I'm willing to just chalk this up to a little bit of miscommunication between us and move on and you are welcome open a discussion or issue here in the future.

**Comment by SultanSGillani** [comment]
Thanks for that. Your repository is amazing and without it I would be in shambles so thanks. 

I also should be more diligent in reading everything on your issue templates. I will def make sure to use the discussions section next time. 

Thanks again for all that you do, and sorry I was an asshole as well.
