### ISSUE TITLE
Battery cam with 2 batteries - MQTT battery entity is only for 1 battery

### ISSUE THREAD

**Issue by landiuk** [tsightler/ring-mqtt#389]
Apologies if this is not correct, new to this.

This is not a breaking issue for me (as I can use the Ring generated entity) and this has been the same since install and through multiple updates.

Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Ring integration for Ring Battery Cam includes second battery in single battery entity, however RING-MQTT entity for the Battery Cam battery appears to be only based on one of the batteries.

The item on the left is the Ring integration battery entity, the item on the right is the Ring-MQTT entity for the same.
So on change of batteries the Ring entity shows 200%, whereas the MQTT entity shows 100%

![image](https://user-images.githubusercontent.com/106375211/174445389-9fbc86c4-2a24-42ba-9bcf-796133aec4b1.png)

**Comment by tsightler** [comment]
Not really a bug, just a limitation of the current implementation.  Currently the code reports the battery level that is reported by Ring API via device health, and, as far as I can tell, this only reports a single property, battery_percentage,  I would have guessed that, for devices with multiple batteries, this would have been some type of average total capacity remaining, but as I don't own and have never owned any Ring battery powered cameras, I'm not really sure what is reported here in this case, I'm just passing this value through unmodified.  One person told me that it reports the value of the lowest battery, but I haven't been able to verify this.

That doesn't mean it couldn't be improved, but, since I don't own one, it's quite difficult to know what to do with it unless someone provides the API information for a camera with multiple batteries.  I guess I could try to look at the native integration and try figure it out, but I'm not sure reporting 105% is really a win, I suspect most people would want to report each battery separately.

**Comment by landiuk** [comment]
@tsightler  Okay as I said new to this.
I do get the 200% as the cam have one or two batteries, so the Ring integrations reports 100% if only one fully charged battery is fitted.
When you say API information, what are you looking for? As I have the Cam with two batteries, will help by providing info if I can.

**Comment by tsightler** [comment]
A lot of systems don't allow battery levels >100%, I'm actually surprised HA allows this, but ring-mqtt is not HA specific, so I don't want to offer a value >100%.

I did a little bit of researching what ring-homebridge does, because the ring-client-api that is used by ring-mqtt is the same, and they have a similar issue, Homekit only allows one battery per device and does not accept charge values >100%.

Ring cameras appear to use batteries in an active/standby fashion, only drawing power from a single battery at a time.  The ring-homebridge code originally averaged both batteries together, but users didn't seem to like this, so the current code simply reports the value of the lowest battery.  I actually think that may be what is happening with ring-mqtt as well so I'm not really sure this should even be changed.

I think the best thing to do for now would be for you to share your feedback as to how it's behaving now.  For example, I know you are showing 105% for native integration, and 6% for ring-mqtt, so does that mean you have 1 fully charged battery (99%) and one that is at 6%?

I do see in one of the cases that there is a battery_life and battery_life_2 property, so maybe I should just report those as attributes in the info sensor if they exist for those that want more specific battery details.

**Comment by landiuk** [comment]
At time of writing this the Ring app shows:
Left battery level 99%
Right battery level 6%
With the HA entities still showing same as above, 105% & 6%

I then tried pulling one of the batteries and display changed to the below.
![image](https://user-images.githubusercontent.com/106375211/174459685-1322cb73-dd7a-4193-94d1-003f4fbfc6ea.png)

Reinserting battery returned display 103% & 6%

The drop in battery is probably because opening the Cam triggered detection for lights and capture.

**Comment by tsightler** [comment]
Thanks for the details, not sure why you decided to close the issue but I will consider enhancements to the battery functionality in a future version when/if I have time to get back to this project.

**Comment by landiuk** [comment]
I closed the issue because it's not really an issue. 

As you said you don't want to offer battery value >100% and I get that. If at some point you add both batteries as sensors under MQTT as an enhancement and you want any more information, then happy for you to reach out and I'll give you any info you need.

In the meantime, there is the Ring integration sensor that detects both batteries, so I am running alerting off of that to remind me to change the batteries.

**Comment by tsightler** [comment]
Fair enough, thanks for sharing the details with me it was useful to spur me to look at other implementations.

**Comment by dcmeglio** [comment]
I'm having a related but different issue. My MQTT addon is reporting that the battery level is only 7%, but I have two batteries and battery 2 is at 100%. So based on what OP said here I'd expect to get 107%? This is causing me problems because I get daily low battery alerts from HA but actually I have plenty of battery left

**Comment by tsightler** [comment]
Unfortunately, not all systems will even accept a battery values higher than 100%.  Current code simply reports value of active battery.  This behavior will change slightly with 5.1.0 due to https://github.com/tsightler/ring-mqtt/issues/529, but the only real difference is that you would now be able to monitor each value separately via BatteryLife and BatteryLife2 attributes.
