### ISSUE TITLE
Please add Doorbell

### ISSUE THREAD

**Issue by grasshide** [tsightler/ring-mqtt#39]
I've been trying for days now to integrate my doorbell into node-red.
Unfortunately it seems that with the change of the ring API none of the available nodes work anymore. After some research I found the repository of @davglass. Awesome approach! Some more research and I found your project - a perfect fit - I thought.
After setting everything up the only thing I got was status: "offline". And only later I red that the Doorbell was not supported.

Hence the request: Please include the doorbell in this project. It would be a perfect fit.

Happy new year and thank you very much!

**Comment by tsightler** [comment]
Please check out https://github.com/tsightler/ring-mqtt which supports doorbells and cameras as well as alarm.  The goal of that project was actually to eventually support everything Ring (lighting, etc), but I just haven't had any time to work on it during the last 6 months, however, even in it's current state doorbells/cameras should work fine.  Currently it supports doorbell "dings", motion "dings" for cameras, and lights and siren for cameras that support those features (Stickup cam, spotlight/floodlight cam, etc).

I've been exclusively using this code myself for the last 6 months and it's fairly stable, but there is one little glitch that I just can't seem to track down where it stops receiving state from some devices very occasionally.  I think it has to do with not recovering from short connectivity/service outages.  It's only happened 2-3 times in those 6 months but otherwise the code has been very stable for me.  PLease feel free to report success/fail or open bugs on that project.

**Comment by respectTheCode** [comment]
It looks like ring-mqtt does everything that ring-alarm-mqtt does. Are both repos maintained? is this one needed?

**Comment by tsightler** [comment]
It does all the same things as ring-alarm-mqtt, it's just a newer version where I've added support for cameras and, hopefully, one day, other devices.  It just didn't make much sense to call it ring-alarm-mqtt if it supported devices other than the alarm.

My plan was to eventually migrate all users of ring-alarm-mqtt to ring-mqtt, but I need to add a flag to disable doorbell/camera support for Home Assistant since that's about 99% of the users of this code and it doesn't make sense to have doorbell/camera support enabled for HA since it already has a native plugin for this.

Both projects are "maintained" at least as much as I have time, which isn't very much.  I'd argue that ring-mqtt is even more maintained at this point since it's the code I'm using so I at least make sure that it keeps working.

**Comment by respectTheCode** [comment]
It looks like your implementation of the doorbell uses a web socket connection to ring while the HA integration polls an HTTP API. I have found that the HA ring integration is slow enough that I don't do anything with it. On the other hand the ring-alarm-mqtt stuff is very fast.

I will see if I can find some time to test this and to add the flag to disable the functions that a user isn't using.

**Comment by tsightler** [comment]
That's not really 100% correct.  My code leverages the excellent [ring-client-api](https://github.com/dgreif/ring) which handles all of the HTTP functions for communicating with the RING API.  It does use a websocket, but that websocket is only for alarm functions (technically, lighting as well, but there's no support on my side).

The doorbells/cameras do not use the websocket and still require polling which is why you have to set cameraDingsPollingSeconds on the API.  The code defaults to polling every 2 seconds, which seems to be the same as the Ring app, and response time is pretty good, but it's still not nearly as fast as the websocket connections for the alarm.  Still, it is faster that the HA ring module, which is 5 second polling and honestly seems unreliable to me, which is largely the reason I decided to add doorbell/camera support to ring-mqtt.

The big issue is that I really want to refactor this code to split out support for alarm/camera/lighting, etc into modules to make it more maintainable.  When I first started this project I had literally never written anything significant in Javascript so it was a learning experience.  When I decided to move the ring-mqtt the plan was to refactor and make it a fully functional replacement for ring-alarm-mqtt with wider support, but I just haven't had any time to devote to these projects over the last 6 months or so so I've reverted to just keeping them functional.

**Comment by tsightler** [comment]
Closing this as the request is already met by ring-mqtt which is currently in development as a successor to this script.
