### ISSUE TITLE
HA gets send 'old' image

### ISSUE THREAD

**Issue by mhoogenbosch** [tsightler/ring-mqtt#393]
### Describe the bug
It seems HA gets send an old snapshot when pressing the doorbell or detecting motion. As a reference I took two pictures:

The following picture is from the ring app on my phone:

![ringapp](https://user-images.githubusercontent.com/36899598/177205941-4ee703fe-039c-4d94-a120-e21e521230d9.jpg)

The following picture is from the HA app, both getting send through notification but also on the HA UI.

![haapp](https://user-images.githubusercontent.com/36899598/177205959-c6d71e71-803a-46a3-b952-0684c613e978.jpg)

As you can see on the second which is from the HA app, the guy isn't even at the doorbell. So I guess the image is 'old' which get's send to HA.

There are no errors in the HA logs regarding this automation nor for the camera entry. 

The logs on docker seem just fine, note: these aren't from the same time as the pictures are but are from a ding press.

```
2022-07-04T19:16:54.291Z ring-mqtt [Voordeur] Received motion push notification, expires in 180 seconds
2022-07-04T19:16:54.291Z ring-mqtt [Voordeur] Requesting motion snapshot using notification image UUID: 72fce8fb-d192-41d1-a07f-d58e484087ff:32263120
2022-07-04T19:16:54.291Z ring-mqtt [Voordeur] ring/u1hrxc-4o007-0/camera/3ce1a1b06608/motion/state ON
2022-07-04T19:16:54.292Z ring-attr [Voordeur] ring/u1hrxc-4o007-0/camera/3ce1a1b06608/motion/attributes {"lastMotion":1656962214,"lastMotionTime":"2022-07-04T19:16:54Z","personDetected":false,"motionDetectionEnabled":true}
2022-07-04T19:16:54.811Z ring-mqtt [Voordeur] Successfully retrieved updated snapshot
2022-07-04T19:16:54.812Z ring-mqtt [Voordeur] ring/u1hrxc-4o007-0/camera/3ce1a1b06608/snapshot/image <binary_image_data>
2022-07-04T19:16:54.812Z ring-attr [Voordeur] ring/u1hrxc-4o007-0/camera/3ce1a1b06608/snapshot/attributes {"timestamp":1656962215}
2022-07-04T19:16:55.749Z ring-mqtt [Voordeur] Received ding push notification, expires in 180 seconds
2022-07-04T19:16:55.749Z ring-mqtt [Voordeur] ring/u1hrxc-4o007-0/camera/3ce1a1b06608/ding/state ON
2022-07-04T19:16:55.749Z ring-attr [Voordeur] ring/u1hrxc-4o007-0/camera/3ce1a1b06608/ding/attributes {"lastDing":1656962215,"lastDingTime":"2022-07-04T19:16:55Z"}
```
### Describe your environment
Running version 5.0.2 of Ring-MQTT on a Raspberry Pi 4. 
Running HA 2022.6.7 docker image on same host

### Describe your settings and what you've tried
I'm using a automation to send the snapshot from the 'snapshot camera' to my mobile phone. I tried setting a delay from 1 - 5 seconds but doesn't seem to make any difference. As the snapshot is on HA UI too, you mentioned it would make sense to first investigate why it seems to send the old snapshot.

Obviously I'm more than willing to participate in trying to solve this issue.

**Comment by tsightler** [comment]
If I'm reading the logs correctly, the first image is from the motion event, while the second image is from the ding event.  As currently written and documented, ring-mqtt only provides image updates on motion events, the ding event will of course register the ding even, but will not provide an updated image.

**Comment by mhoogenbosch** [comment]
Right, that must be it then. My apologies then, if it is by design ;-) I thought i read your documentation quite clearly.

Just out or curiosity, is this a technical limitation or just something on a todo list?

**Comment by tsightler** [comment]
I'd say that the docs could be more clear, they don't explicitly mention anything about dings, but they do only talk about motion.  Dings are something completely different.

The historical reason for not including images from dings is that most Ring doorbells are battery powered, or, even if they're not, behave like battery cameras (for example, the Doorbell Wired is still a low-power camera, even though it has no battery).  These cameras aren't able to take a snapshot while recording and, in general, recording starts on motion events which will generally always happen before the ding, thus there was no way to get an image from the ding itself.

Because of this, versions of ring-mqtt prior to 5.x would connect to the live stream when motion was detected and grab a still image from the stream.  This would commonly take 5-7 seconds from when the motion was initially detected, but it was the best that was possible to get.

Now that there are options to use the UUID from the rich notification to retrieve the image, it might make sense to grab and update the image for dings events as well, but, for most people, getting the image from the motion event, which is prior to the ding, seems to be good enough.  For me, I find that images from dings are usually worse than those from the motion event as, for my camera position, the person usually has an arm extended pressing the doorbell and this obscures the view, while the motion event happens when the person is walking toward the door.

That being said, I live quite rural, and don't have many visitors, even fewer that actually ring the doorbell.  I also only alert on person detection for the doorbell because I have two cameras to watch the driveway and another that catches an up top angle on the front porch, so those are used for initial detection and automations.  I have 7 Ring cameras total, but only one is a doorbell, the other 6 are floodlight and stickup cameras, so motion is all they have, no ding.

I'm not unwilling to consider adding an option to include image updates for dings, but it's literally never been asked before, and it wasn't previously easily possible anyway.

**Comment by mhoogenbosch** [comment]
Thanks for your explanation, I for sure would love to have the picture from the actual ding. I'm using a Pro which is labeled as high power device, right? I will look into a way to get a better image and fizzle around a bit with adding more delays. Thanks again!

**Comment by tsightler** [comment]
Adding additional delay won't help because the image from the ding is never sent.  As far as I can tell you are getting the image from the motion notification, which is the image I would expect.

**Comment by tsightler** [comment]
Oh, and the Pro should be a high power device, it's actually the doorbell I personally own.
