### ISSUE TITLE
Phantom (previously deleted) MQTT entities reappearing

### ISSUE THREAD

**Issue by aaronganek** [tsightler/ring-mqtt#399]
**### Describe the bug**
I have deleted MQTT devices/entities reappearing.

I have a Ring Alarm system. I had some devices (light switches) connected to Ring via Zwave. I recently performed a proper Zwave exclusion process to remove the devices from the Ring system and Ring app. I then deleted the associated MQTT devices in HA (which were via the Ring-MQTT add-on). Everything worked as expected. The light switches no longer appeared in the Ring app and no longer appeared in Home Assistant. The light switches flashed showing that they were factory reset. All good...

Until I restarted HA. All of my former MQTT devices/entities get recreated in HA. The entities are stale and do not function ofc because they no longer present in the Ring app. Any idea why my devices are re-appearing in HA?

**### Describe your environment**
Home Assistant 2022.7.3
Ring Alarm Base Station 1.52.0
Leviton Decora Z-wave Light Switches and Dimmers
Ring-MQTT 5.0.2

**### Describe your settings and what you've tried**
I have properly removed old Zwave devices from the Ring App (including the full z-wave exclusion process). I have deleted the MQTT devices+entities from HA.

**### Debug Logs**
The device in the logs below no longer exists. This log appears at HA startup. It must be referencing a cached state from before I removed the device.
`2022-07-14T03:11:40.323Z ring-mqtt [Patio Light] ring/8266f233-39f9-49bb-946f-XXXX3db90df4/alarm/637XXXfd-aaa5-4df1-8d65-03df8c51a61f/light/state OFF`
`2022-07-14T03:11:40.323Z ring-mqtt [Patio Light] ring/8266f233-39f9-49bb-946f-XXXX3db90df4/alarm/637XXXfd-aaa5-4df1-8d65-03df8c51a61f/light/brightness_state 100`
`2022-07-14T03:11:40.323Z ring-attr [Patio Light] ring/8266f233-39f9-49bb-946f-XXXX3db90df4/alarm/637XXXfd-aaa5-4df1-8d65-03df8c51a61f/info/state {"commStatus":"ok","lastCommTime":"2022-07-14T02:12:06Z","lastUpdate":"2022-07-14T02:12:06Z","linkQuality":"ok","tamperStatus":"ok"}`

**Comment by tsightler** [comment]
> Until I restarted HA

Did you also restart the ring-mqtt addon?  I assume when you say this you mean you used the restart option in the UI under Settings->System, which only restarts the container that runs the HA core components, the containers which run the addons are not impacted by this option and must be restarted individually (there's a button to restart the addon) or, optionally, you can reboot the host (Settings->System->Hardware->Three-dots menu->Reboot Host).

This addon does not support dynamic add/remove of devices so any time devices are added or removed devices to/from Ring the addon must be restarted so that it will retrieve a new device list.

**Comment by aaronganek** [comment]
You nailed it. I am thoroughly impressed!

I was restarting HA via the UI, yep. I was unaware that did not restart the add-on as well, yep.

Cleaning HA. Restarting the Ring-MQTT add-on. And then restarting HA. No issues.

Thank you!
