### ISSUE TITLE
Support form modes without alarm

### ISSUE THREAD

**Issue by denniswham** [tsightler/ring-mqtt#44]
Recently Ring introduced modes to control the behavior of your Cameras, even without having a Ring Alarm.

Does this component support the modes without having an alarm? And if not , are there plans to support that scenario?

**Comment by denniswham** [comment]
Just noticed this is also discussed in ring alarm API at dgreif/ring-alarm, since this component is leveraging this, closing this item.

**Comment by tsightler** [comment]
I don't really understand the statement.  Ring has had cameras from day one, the doorbell camera was their first product back in 2013.  The Ring alarm system is actually quite new by comparison only being released in 2018.

Home Assistant already has native support for Ring cameras and there were already several projects that supported MQTT for Ring cameras so this project was started to provide that same functionality for the alarm that was already available for cameras.  However, do to many request, I do have a separate script called, ring-mqtt, that is intended to eventually support all Ring devices, and currently supports cameras, but it's still in development.

**Comment by denniswham** [comment]
Recently the Ring Modes feature was released, which works great even if you don't have the Ring Alarm. 
https://support.ring.com/hc/en-us/articles/360036107792-Control-All-your-Ring-Cameras-with-Modes. (Dis)arming works similar to the Alarm, but apparently it is a different feature. And the Ring Modes are not (yet) available in HA.

I have the camera integration setup in my HA config for some time now.

Does this make sense?

**Comment by tsightler** [comment]
OK, thanks.  So I guess the request is to be able to set the "Home/Away/Disarmed" mode even if you don't have an alarm?  I'd guess that would make sense but I have no idea how it works from the Ring side so I'd have to research that.

Right now, the Home/Away/Disarm commands are sent via websocket to the alarm base station device, so if you don't have an alarm, they must have some separate API for this, because there wouldn't be a base station.  But, perhaps, if you do have an alarm, this code would just work.  I really don't know.  I'll keep it in mind and try to follow the conversation on Ring API.
