### ISSUE TITLE
Bug: Container fails to start up beginning 5.0.3

### ISSUE THREAD

**Issue by aneisch** [tsightler/ring-mqtt#446]
### Describe the Bug

Readonly container fails to start. This ability was introduced in response to #249

### Steps to Reproduce

Upgrade to 5.0.3, set env S6_READ_ONLY_ROOT=1

### Expected Behavior

Container runs in RO root mode

### Log Output

```shell
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
/package/admin/s6-overlay/libexec/preinit: info: read-only root
/package/admin/s6-overlay/libexec/preinit: info: writable /run. Checking for executability.
/package/admin/s6-overlay/libexec/preinit: warning: unable to find /run in /proc/mounts, check that your container manager pre-mounts /proc, and that /run is a tmpfs. The container is likely to crash soon, if /run is (incorrectly) mounted noexec.
s6-linux-init: fatal: unable to copy /run/s6/basedir/run-image to /run: Operation not permitted
```

### Config File

```shell
ring-mqtt:
        container_name: ring-mqtt
        image: tsightler/ring-mqtt:5.0.3
        restart: 'always'
        user: '99'
        ports:
            - 8554:8554
        environment:
            - S6_READ_ONLY_ROOT=1
            - MQTTHOST=10.0.1.22
            - RINGTOKEN=XXX
            - ENABLEMODES=true
            - SNAPSHOTMODE=all
            - ENABLECAMERAS=true
        volumes:
            - '/opt/ring-mqtt:/data'
```
```


### Install Type

Docker

### Version

v5.0.3

### Operating System

Home Assistant

### Architecture

x86_64

### Machine Details

NUC

**Comment by tsightler** [comment]
Did you verify that tmpfs is mounted to /run like it says?  This is a change in s6-overlay v3 vs prior versions which previously only required /var to be rw.

Unfortunately s6-overlay support for running as user other than root was always pretty limited and, based on their documentation, this seems to be even more true with v3.  It does indicate that it should still be possible to get it to work based on the documentation, but I don't have the time or motivation to dig through it and figure it out at this time as it's just not important to 99.9% of users.

You can always just override the default entrypoint and run the script directly, completely bypassing the s6 supervision tree, then running as any user should be possible.   If you'd like to dig into the s6-overlay changes yourself and figure it out, I'd be happy to entertain a PR.

**Comment by aneisch** [comment]
Thanks for the response. At this very moment I'm also lacking the time and motivation to look closely into this, just wanted to open an issue to document. If I get around to digging into it and find a fix I'll send a PR your way. 

As always, thanks for everything you do to maintain this wonderful project!

**Comment by tsightler** [comment]
OK, if I get some time at some point I will try to figure it out.  I'm actually not surprised that the upgrade to s6-overlay v3 broken non-root containers as I saw other reports of this as well.

**Comment by tsightler** [comment]
I finally found a little time to dig at this and it seems the issue is indeed that v3 of s6-overlay expects a writeable and, more importantly, an executable path mount the /run.  This means to run with a regular user you must mount something to /run.  This should theoretically work with tmpfs, however, for reasons I don't yet fully understand, although I have a theory, this isn't working.  However, if you do a bind mount to a host volume that the user you specify for running the container also has access to write to on the host, then it runs just fine.

I think the possible reason that tmpfs doesn't work is because I'm explicitly setting /run to mode 777 during the Docker build process and I think the s6-overlay doesn't like this.  According to the documentation it wants 755 and the /run to be owned by the user the container is running as.  It implies that docker should do this automatically when you mount tmpfs, but, at least so far, I can't get this to work.  The default behavior of docker seems to be that the container mounts tmpfs to /run with 1777 and owned by root.

It seems like the entire Docker tmpfs stuff is a total mess, some stuff works from the CLI, some from compose 2.x, others in compose 3.x.

I guess the easy option is to just use a bind mount if you really want this for now.  You can always create a tmpfs on the host and then bind mount it to /run and then it will work fine without any changes.

**Comment by tsightler** [comment]
OK, I finally found the magical required options.  As the message above states, /run must be executable in the container.  Previously it would work with just 777 permissions on /run but the new version of s6-overlay is more strict on having secure permissions and wants the /run path to also be owned by the same uid as the USER directive.

After some playing around, I finally found the magical combination of specifying the uid of option for the tmpfs mount option, so for example, if you want to run as non-root user with read only root you now must also have Docker setup the tmpfs for /run as follows:

`docker run -it --rm --mount type=bind,source=/home/notyouradmin/data,target=/data --tmpfs /run:exec,uid=1099 --user 1099 -e S6_READ_ONLY_ROOT=1 tsightler/ring-mqtt`

This works right now, with existing 5.0.3 docker image, so no changes were required to the Docker image itself.
