### ISSUE TITLE
ring doorbell gen2, Motion snapshot needed but notification did not contain image UUID

### ISSUE THREAD

**Issue by Stefan300381** [tsightler/ring-mqtt#451]
Hi,

any idea why my AC powered ring doorbell gen 2 isn't always able to send a motion snapshot via mqtt, while it's able to send a motion notification? The log says, UUID is missing, but how can I "fix" this? Not sure, but it seems sometimes it works, sometimes it doesn't.

```
2022-09-04T15:37:10.536Z ring-mqtt [Haustür] Received motion push notification, expires in 180 seconds
2022-09-04T15:37:10.536Z ring-mqtt [Haustür] Motion snapshot needed but notification did not contain image UUID and battery cameras are unable to snapshot while recording
```

best regards

Stefan

**Comment by tsightler** [comment]
What do you mean by AC powered?  I was under the impression that these doorbells only had a USB charging cord.  Do you have a link to the specific camera and specs?

Getting a motion snapshot from low power cameras that cannot take a snapshot while recording requires that the push notification includes the UUID of the image so that the snapshot can be retrieved from the Ring API.  For the push notification to contain the UUID the camera must have rich notifications enabled, which requires a Ring protect plan.

If you have both a Ring protect plan and rich notifications enabled, then I'm afraid I don't have any idea why the UUID wouldn't be part of the push notification.  I've seen some anecdotal evidence that it might happen when a camera has relatively poor connectivity or slow response time as it seems like Ring will only wait for a second for the snapshot image before going ahead and sending the notification anyway (probably makes sense, you don't want to delay notification just for the snapshot).  That being said, I don't even own any of these low powered Ring devices so I'm only guessing based on the fact that several users that reported this problem also had very slow response from their cameras.

There's really nothing I can do about this though, the push notification either has the UUID or it doesn't.  If it doesn't, and the camera does not allow snapshots, then there's nothing to be done.

**Comment by Stefan300381** [comment]
Hi there,

>> What do you mean by AC powered? I was under the impression that these doorbells only had a USB charging cord. Do you have a link to the specific camera and specs?

This is the one: https://ring.com/products/video-doorbell-v2
You can either charge or power it via USB (5V DC) or 8-24V AC
See here: https://support.ring.com/hc/en-us/articles/205180710-How-to-Connect-Your-Ring-Video-Doorbell-Directly-to-a-Low-Voltage-Transformer-Without-a-Pre-existing-Doorbell-

>> Getting a motion snapshot from low power cameras that cannot take a snapshot while recording requires that the push notification includes the UUID of the image so that the snapshot can be retrieved from the Ring API. For the push notification to contain the UUID the camera must have rich notifications enabled, which requires a Ring protect plan.

I guess this is my showstopper. Even running with 8V-24V AC the device is still considered "low powered". What a pity. 
Currently the only workaround I found is to grab or rather convert a still image from the rtsp stream.

best regards
Stefan

**Comment by tsightler** [comment]
It's not just considered low powered devices, it is a low powered device.  Basically, the software in these devices are optimized for battery life and have limitations that the line powered devices do not have.  Note that you state that you can "power it via USB or 8-24V AC", but that's not exactly what the specs for this camera say, actually it says this (emphasis added):

> Can be hardwired to an existing doorbell system or transformer for **_continuous charging_** (8-24 VAC, 40VA max, 50/60Hz)  

So in the end, the device is still battery powered, it's just using the wired power to keep the battery charged all the time.  This is also true of, for example, the new Doorbell Wired devices, but they don't have batteries at all.  They appear to be basically the same hardware as the old battery cameras, but it seems that maybe they've included a super capacitor, or something similar, instead of a battery, to use for reserve power.

Of course there are "high powered" wired doorbells too, the Doorbell Pro models for example (which is what I own).  These guys are quite a bit more expensive but do behave like traditional line powered devices.

If you own a low power device, then these cameras simply cannot take a snapshot while recording so the only way to get the snapshot is from the rich notification, which requires a Ring protect subscription or, as you've pointed out, you can indeed can get one from the RTSP stream, which is actually what ring-mqtt did prior to push notifications, but it was slow and error prone and many times managed to get an image too late to be useful since it takes several seconds for the stream to start and get the first reference frame, but indeed you can still do it with an automation (I'm assuming that is what you are doing).

**Comment by Stefan300381** [comment]
awesome explanation, highly appreciated. Thanks a lot for your passion, support and this great project.

**Comment by anandv85** [comment]
I have the same Ring camera.  The motion snapshot was working perfectly fine for more than one year.  Recently for the last one week, it stopped working.  I'm no longer getting the motion snapshot.  The log indicates `the motion notification did not contain image UUID and battery cameras are unable to snapshot while recording`

I wonder if this is something related to the Ring Addon issue rather the Ring cloud itself? Any thoughts?

**Comment by tsightler** [comment]
> I have the same Ring camera. The motion snapshot was working perfectly fine for more than one year. Recently for the last one week, it stopped working. I'm no longer getting the motion snapshot. The log indicates `the motion notification did not contain image UUID and battery cameras are unable to snapshot while recording`
> 
> I wonder if this is something related to the Ring Addon issue rather the Ring cloud itself? Any thoughts?

Have you stopped paying for your Ring subscription or did you potentially run out of an initial subscription.  Motion snapshots cannot work for these devices without a Ring subscription.

**Comment by tsightler** [comment]
Also, you will want to verify the rich notifications are enabled for you device.  You can check this in the Ring app, under Device Settings...Notification Settings...Rich Notifications.

**Comment by anandv85** [comment]
> > I have the same Ring camera. The motion snapshot was working perfectly fine for more than one year. Recently for the last one week, it stopped working. I'm no longer getting the motion snapshot. The log indicates `the motion notification did not contain image UUID and battery cameras are unable to snapshot while recording`
> > I wonder if this is something related to the Ring Addon issue rather the Ring cloud itself? Any thoughts?
> 
> Have you stopped paying for your Ring subscription or did you potentially run out of an initial subscription. Motion snapshots cannot work for these devices without a Ring subscription.

I do have the ring protect subscription.  I'm able to see all the motion alerts and video recording in my Ring app for all my cameras.

**Comment by anandv85** [comment]
> Also, you will want to verify the rich notifications are enabled for you device. You can check this in the Ring app, under Device Settings...Notification Settings...Rich Notifications.

Yes, the Rich Notifications is enabled for the Front Door Ring camera.

**Comment by anandv85** [comment]
Please let me know if you need any additional logs or data from the Home Assistant.  I really appreciate your help and contribution to the Ring Addon in HAOS.

**Comment by anandv85** [comment]
@tsightler As you mentioned above, I suspect this could be the WIFI signal strength issue.  I noticed the camera went offline intermittently. May be I will first solve this signal strength issue and then let you know if I still facing the motion snapshot issue. Thanks again for all your help.

**Comment by tsightler** [comment]
Ring did roll out a bunch of new features on Nov 5th.  I have no idea how these feature might impact the behavior of some of these things, for example, the Video Preview Alerts could possibly interfere with image snapshots, if this feature is enabled.  My cameras don't support this feature so I've not seen any issue here, but it is possible.

Overall however, the function of this feature is super simple, ring-mqtt simply receives the same push notification that the Ring app receives, and it includes a UUID for an thumbnail that can be retrieved from Ring servers.  If the UUID isn't in the push notification, there's not much that can be done about it from a code perspective.

**Comment by anandv85** [comment]
@tsightler I fixed the issue by setting up an HA automation for snapshot whenever motion is detected.  With this, I'm consistently getting the motion snapshot.  I'm pretty sure Ring changed something at their backend and that is flow down to HA Ring Addon.  I know its very hard to catch up all the Ring changes and sometime, it is not possible as well.  As a software engineer, I can understand the pain.

Anyways, the simple solution is to create an automation for the doorbell motion snapshots.  To avoid redundant motion snapshots, I configured the Ring Addon doorbell camera motion event to only "ding".  I wish I can configure the motion event to permanently "disabled" but then the Ring Addon will not initialize the doorbell snapshot upon a HA reboot.  So I have to set the motion event to a lowest category "ding".  Overall, I'm all set for now.  Once again @tsightler, your help is much appreciated.  I believe several hundreds of users are getting benefited with your Ring Addon for HA.  Keep up the great work!

**Comment by tsightler** [comment]
Can you clarify exactly what your automation does?  Perhaps sure it.

While I can't rule it out, I don't think Ring has changed anything as we know the structure of the push messages in pretty good detail and it would be broken for 1000's of users (ring-mqtt alone has ~10,000 users, and the API underneath is used in projects which represent at least another 10,000 more).  Because of this extensive user base, API changes usually take very little time to reach dozens of reports of issues.  We also have a very good understanding of how the push notifications work in general.

It's important to note that this message does not mean the snapshot will not be updated, only that the initial push notification did not contain it.  As noted above, battery/low power cameras sometimes have multiple notifications, the initial one without the snapshots, and then one a bit later that includes the snapshot.  It would be very interesting to see the full logs from an event.

**Comment by anandv85** [comment]
Below is the automation I created in HA.  I will get you the full log shortly. Thanks!

```
alias: Front Door Camera Snapshot
description: ""
triggers:
  - type: motion
    device_id: xxx
    entity_id: xxx
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - device_id: xxx
    domain: button
    entity_id: xxx
    type: press
mode: single
```

**Comment by tsightler** [comment]
@anandv85 Thank you very much.  Based on what turns up in the logs, I may ask you to run a dev version with some additional debugging enabled, so that we can grab the raw push notification.  Your help is much appreciated.

**Comment by anandv85** [comment]
[Ring_Doorbell_Log.txt](https://github.com/user-attachments/files/17788821/Ring_Doorbell_Log.txt)
@tsightler Please see attached log.  Log is filtered for the doorbell camera.  I still see the same issue (no UUID).  This was tested with motion event some 20 minutes ago (see timestamp).  I'm OK to run the dev version to get you more information. Thanks!

**Comment by anandv85** [comment]
> Below is the automation I created in HA. I will get you the full log shortly. Thanks!
> 
> ```
> alias: Front Door Camera Snapshot
> description: ""
> triggers:
>   - type: motion
>     device_id: xxx
>     entity_id: xxx
>     domain: binary_sensor
>     trigger: device
> conditions: []
> actions:
>   - device_id: xxx
>     domain: button
>     entity_id: xxx
>     type: press
> mode: single
> ```

FYI:  The automation works great so far.  I'm seeing snapshot getting updated for every single motion event without a miss. Thanks!
