### ISSUE TITLE
Ring Doorbell wired - Video Live Stream

### ISSUE THREAD

**Issue by AxDevl** [tsightler/ring-mqtt#468]
#### Describe the problem
I'm not able to open the video live stream neither manually by switch, nor by opening in camera generic.

##### Describe your environment
Raspberry Pi 4, 4GB, 64x OS HA and using MQTT Broker Add-on, 32GB SD, Wired Ethernet Connection, Full Fibre Internet (meaning no access to router)
Ring Doorbell Wired 2021 + Chime Pro V2 (Snapshots and Ding (Cleared or on) work)

#### Describe any steps you've taken to attempt to resolve the problem
I've looked at the logs and it's saying no one is publishing to path.

#### Debug Logs
**CENSORED WITH #####**
2022-09-19T13:06:09.704Z ring-mqtt [Doorbell] Received set live stream state ON
2022-09-19T13:06:09.704Z ring-mqtt [Doorbell] Starting a keepalive stream for camera
2022-09-19T13:06:09.739Z ring-mqtt [Doorbell] The keepalive stream has started
2022-09-19T13:06:09.748Z ring-rtsp INF [RTSP] [conn ############] opened
2022-09-19T13:06:09.748Z ring-rtsp INF [RTSP] [conn ############] closed (no one is publishing to path '#########_live')
2022-09-19T13:06:09.752Z ring-mqtt [Doorbell] The keepalive stream has stopped
2022-09-19T13:06:14.754Z ring-rtsp INF [API] [conn #########] GET /v1/paths/list
2022-09-19T13:06:14.759Z ring-mqtt WARNING - Unhandled Promise Rejection
TypeError: Cannot read properties of undefined (reading 'sourceReady')
    at Camera.startKeepaliveStream (/app/ring-mqtt/devices/camera.js:747:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-09-19T13:06:28.056Z ring-mqtt [Doorbell] Requesting an updated interval snapshot
2022-09-19T13:06:33.690Z ring-mqtt [Doorbell] Successfully retrieved updated snapshot

I'm quite new to Home Assistant so there could be a problem of me just setting it up!

**Comment by tsightler** [comment]
Please provide full logs, I can't possibly help from that small amount of data with the device id's redacted.  The logs are very strange because it's not even trying to start the stream, did you install the addon or did you install ring-mqtt via one of the other methods?

**Comment by AxDevl** [comment]
I installed it though the Add-on. Sorry for the small log because I’ve looked through it and didn’t find anything unusual (or any errors) with also interval capture working. As I turn on the livestream switch, it just turns off (same with events)

**Comment by tsightler** [comment]
The logs are important because the initial startup of the addon logs things like the discovery and rtsp server initialization process.  The fact that it's failing without even trying to run the on-demand script makes me thinks that, for some reason, this is failing in your case, but without the full logs, or at least more snippets that include startup, I can't put all of that together.  I've never seen this fail nor had any reports that match anything like this so it's very strange for sure.

Please follow the process documented here and provide full logs from startup including showing an attempt to start the live stream:

https://github.com/tsightler/ring-mqtt-ha-addon/blob/main/GET-LOGS.md

If you don't want to post them here you can email them to me directly.  My email is the same username as here at gmail, but I don't think I can even come up with any ideas without seeing more logs.  Please include logs from start of the addon with a few failed attempts to start the stream.

Also, to be clear, the event stream is expected to turn off immediately as it can't be triggered manually, it can only be started with an RTSP client requesting the stream.

**Comment by AxDevl** [comment]
I understand your struggle, part of it is my fault due to being let's say (under educated) in HA. At the moment, I'm having troubles installing the SSH (saying unhealthy system for some reason however I'll figure it out) because the OpenSSH I have doesn't want to run the command for some reason. 

Could it be something with not being up-to date with Home Assistant or something is missing that I missed out of the installation guide?

**Comment by tsightler** [comment]
How out of date is your HAOS/supervisor.  I mean, I doubt it would cause the problem you are seeing, but unhealthy state is not great, and who knows what that might cause.  Any change you are out of space, perhaps filled up by backups or something?

**Comment by AxDevl** [comment]
It was only 1 update out, however I've updated now as all working fine with downloading SSH. I'll go ahead with download. 


I've got only 14% used SD card (23GB free) and only have like 2/3 backups.

**Comment by AxDevl** [comment]
Good news! After updating supervisor, the streams are activating now and showing up as viewed sessions in the Ring App by the switch! I'm downloading the core HA update now, however I'm trying to add it now as a generic camera which I'm having issues.
Somehow updating home assistant fixed the first problem :)

**Comment by AxDevl** [comment]
Hooray! I've got it working :)) 

Add in your documentation to update Home Assistant!
