### ISSUE TITLE
Door lock always reports "unlocked" status

### ISSUE THREAD

**Issue by eingram23** [tsightler/ring-mqtt#47]
Running Hassio 0.104.3 with 0.52 of this component.  I believe this just started happening within the last day or two.  Basically, HA always thinks the door lock is unlocked, regardless of whether it is or not.  This is happening on two Schlage locks that I currently own.

**Comment by tsightler** [comment]
This issue is already addressed here:

https://github.com/tsightler/ring-alarm-mqtt/issues/40

A new version of the script was published last week to adjust for the changes in 0.104.  To get these updates you just need to click the "REBUILD" button in the add-on which will download the latest version of the script.  The add-on version will not change as there are no changes to the add-on itself, the add-on just downloads the latest version of the script from github.  Please note that I do not maintain the add-on.
