### ISSUE TITLE
ffmpeg time out / bad request issue

### ISSUE THREAD

**Issue by Stefan300381** [tsightler/ring-mqtt#473]
Hi,

a few weeks ago I installed ring-mqtt docker image for my battery powered doorbell.
Whenever a motion event is triggered I launch ffmpeg to connect to the rtsp stream generate a still image.
This worked fine for weeks.

Now ffmpeg wanrs me "server returned 400 Bad Request"
And in ring-mqtt I see:

```
2022-09-30T09:36:57.912Z ring-rtsp INF [RTSP] [conn 172.19.0.1:40840] opened
2022-09-30T09:36:57.915Z ring-rtsp INF [path 90486c08df10_live] runOnDemand command started
2022-09-30T09:36:57.918Z ring-rtsp [Haustür] Sending command to activate live stream ON-DEMAND
2022-09-30T09:36:57.922Z ring-mqtt [Haustür] Received set live stream state ON-DEMAND
2022-09-30T09:37:07.916Z ring-rtsp INF [path 90486c08df10_live] runOnDemand command stopped
2022-09-30T09:37:07.918Z ring-rtsp INF [RTSP] [conn 172.19.0.1:40840] closed (source of path '90486c08df10_live' has timed out)
2022-09-30T09:37:07.918Z ring-rtsp [Haustür] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)
2022-09-30T09:37:07.920Z ring-mqtt [Haustür] Received set live stream state OFF
```

Any idea what's wrong?

Here is my ffmpeg result:

```
[11:35:30] root@openHAB:/etc/openhab/rules# ffmpeg -y -i 'rtsp://admin:xxxxx@192.168.2.9:8554/90486c08df10_live' -an -q:v 1 -vsync vfr -frames:v 1 bla.jpg
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
rtsp://admin:xxxxx@192.168.2.9:8554/90486c08df10_live: Server returned 400 Bad Request
```

**Comment by tsightler** [comment]
Did you restart ring-mqtt?  Is that really all of the log messages?  The most confusing thing is that, immediately after the message "Received set live stream state ON-DEMAND", there should be a message stating that it is "Starting a live stream session via Ring servers", yet that message doesn't exist in the logs you posted.  This implies that there is a live session stuck in activating state, but restarting should clear it.

**Comment by Stefan300381** [comment]
Hi,

no I didn't restart ring-mqtt by intention ;-) Couldn't sleep, so I restarted it just now in the middle of the night. Let's see tomorrow if the issue is gone. Feel free to close the ticket.

Btw: A nice feature would be to automatically save a still image every X seconds (not sure if this would be even possible)

best regards

**Comment by tsightler** [comment]
I may need to add some additional debugging, but I've seen a few reports where, after a while, the live stream will stop activating for some reason.  I think it's because a stream gets into activating state, but never actually activates, and then just hangs there, thus new request aren't able to be processed because they detect that a stream is already activating, however, I've never been able to actually reproduce this issue myself.  Probably I need to add some timeouts and perhaps some additional debugging, to try to get to the bottom of those cases.

> Btw: A nice feature would be to automatically save a still image every X seconds (not sure if this would be even possible)

That's not really something that fits within the realm of this project.  To goal of this project is to be the bridge between Ring's proprietary API and standard based protocols of MQTT and RTSP, that's it.  From that point any tool that can use these protocols can be leveraged to do whatever a user wants with the data.  For example, ring-mqtt already supports taking snapshots on motion or at set intervals (down to as often as every 10 seconds, although that's battery drainer for non-line powered cameras), and it sends these images via MQTT topics.  It's up to whatever tool you like to use to look for these images and save them or otherwise do whatever you want with them.  A simple HA automation or Node Red flow can do what you ask.

**Comment by Stefan300381** [comment]
Just to add, the restart fixed the issue until it came back the day after :-( Since I didn't have time to restart again, I will do it right now.

**Comment by Stefan300381** [comment]
I can confirm now this happens from time to time and a restart solves it.

**Comment by tsightler** [comment]
Without full logs of a session where it was working and then fails, there's not much that can be done here.
