### ISSUE TITLE
Ring new login security

### ISSUE THREAD

**Issue by jac2424** [tsightler/ring-mqtt#48]
Ring now sends new login verification and app can't work with it.

**Comment by tsightler** [comment]
I don't know what this means, can you please clarify what you are asking for?

**Comment by tsightler** [comment]
If you are talking about 2FA, this is already supported in the code and is covered in the authentication options sections of the readme.

**Comment by sktaylortrash** [comment]
I imagine they are.  As of today 2FA is becoming mandatory for all Ring accounts




-------- Original message --------

**Comment by aidanblack** [comment]
This isn’t working for me. The username and password are blank and the ring_token has the value from the CLI. All I get in the log is “Exit code: 1”

**Comment by tsightler** [comment]
I've just re-cloned the repository and run through the process of enabling 2FA on an account and getting the refresh token, pasted it into the config and it works fine.  If you have an invalid refresh token it prints a message that the token is not accepted.

If you are getting "Exit code: 1" this almost always implies that the refresh token was not copied and pasted correctly.  Common issues are copy-paste from a terminal that includes line breaks, extra quote marks, or, if you added the refresh token to an existing config.json, forgetting to add the comma after ring_pass, etc.  The refresh token must be a single line with no line breaks, enclosed in a single set of of quote marks.  Please use the below as a template:
```
{
    "host": "localhost",
    "port": 1883,
    "ring_topic": "ring",
    "hass_topic": "hass/status",
    "mqtt_user": "",
    "mqtt_pass": "",
    "ring_user": "",
    "ring_pass": "",
    "ring_token": "<huge_long_string_in_quotes with no ling breaks>"
}
```

**Comment by aidanblack** [comment]
Apologies - it looks like the HassIO add-on hasn't been updated to pass the new parameters to your code that are required for 2FA.

**Comment by tsightler** [comment]
Yes, that's true, although there is already a fork with a PR to include it so you can use that for now.

To be honest, this hit me at a bad time as I was gearing up to merge this repo with [ring-mqtt](https://github.com/tsightler/ring-mqtt) which I've been working on during the last few weeks.  It's much more modular, has support for cameras (optional for those that want it) and a few other goodies, but, most importantly, I was going to release my own HASSIO add-on so that all maintenance was in a single place, but I won't have time to get it out there for a few days.

**Comment by aidanblack** [comment]
I  was going to clone the fork but I may just hang on for ring-mqtt in that case! Thanks for all your work on this - especially since Ring keeps on moving the goalposts...

**Comment by jasonhyland** [comment]
Thanks for your work @tsightler! Hoping for a fix for HASSIO, but makes sense to wait for ring-mqtt!

**Comment by jac2424** [comment]
Thanks for looking into it. Will wait for the new hass.io addin to fix the issue.

**Comment by tsightler** [comment]
Since this script already has support for 2FA there's really nothing to do in this project so I'm going to close this issue.

I have published my own Hass.io addon that uses the new ring-mqtt script.  I would consider it beta quality at this point, but it's mostly identical to the original addon with simple the added fields for refresh token and enable/disable for camera support.  If anyone wants to test please find it here:

https://github.com/tsightler/ring-mqtt-hassio-addon

Please report any issues with the addon in that project.
