### ISSUE TITLE
can't start ring-mqtt

### ISSUE THREAD

**Issue by hgmorse** [tsightler/ring-mqtt#502]
Hello,

I crash my old installation so i need to reinstall everything. My last installation was on the old version and somme thing have changed.

i have follow the install manual guide, everything seems to be ok with DEBUG=ring-mqtt ./ring-mqtt.js

but when i try to lauch ssystemctl status ring-mqtt i have this message
![image](https://user-images.githubusercontent.com/57915348/201736613-ead3d9a2-2b08-4fa1-b0bd-5a647fea8732.png)

I'm on Pi4, debian 10.13.

Ring-mqtt was installed on home/jeedom/ring-mqtt

here is my raing-mqtt.service 
`#!/bin/sh -
[Unit]
Description=ring-mqtt
After=network.target

[Service]
ExecStart=/usr/bin/node /home/jeedom/ring-mqtt/ring-mqtt.js
Restart=always
#User=root
#Group=root
Environment=PATH=/usr/bin/:/usr/local/bin
Environment=NODE_ENV=production
Environment=DEBUG=ring-mqtt
StandardOutput=file:/var/log/ring-mqtt.log
StandardError=file:/var/log/ring-mqtt.log
WorkingDirectory=/opt/ring-mqtt

[Install]
WantedBy=multi-user.target
Alias=ring-mqtt.service
`
could you help me?

**Comment by tsightler** [comment]
I don't provide support for manual install method and your issue is related to basic system administration, not anything specific to ring-mqtt so, unfortunately, I can't really help you.  However, my guess is possible that you haven't set the working directory which should generally be the same as the directory where ring-mqtt is installed (/home/jeedom/ring-mqtt in your case).  You also have remarked out the user/group, but you should probably set these to some user that has read/write permissions to said working directory.
