### ISSUE TITLE
Docker Script Error

### ISSUE THREAD

**Issue by JoeStratton** [tsightler/ring-mqtt#51]
Ever since the new implementation I have not been able to use the script/container. I tried using MFA and generated my code but still receive the following

> ring-mqtt@3.0.0-beta.2 start /srv
> node ring-mqtt.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ring-mqtt@3.0.0-beta.2 start: `node ring-mqtt.js`
npm ERR! Exit status 1

npm ERR! Failed at the ring-mqtt@3.0.0-beta.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-02-22T15_36_47_417Z-debug.log

I have tried multiple docker container images as well as tried building my own.

I tried filling int he user/pass variables as well as leaving them blank since I am using a token now. 

Last note, I have been using this for a few months before this without issue, great app!

**Comment by tsightler** [comment]
Unfortunately, the error above simply means the script exited with an error, it doesn't really give any clue as to why because the script produces no output without debug being set.  Please add "-e DEBUG=ring-mqtt" to your "docker run" command and see if that provides any clues.

**Comment by JoeStratton** [comment]
Thanks for the quick reply, the debug command told me that it was missing a environment variable. Upon closer inspection its because I had "ring_token" as the variable instead of "RINGTOKEN".

You might want to update your readme as its showing both.(see the docker run example vs the paragraph below it) but thanks for the insight!

**Comment by tsightler** [comment]
Yeah, that's a side effect of having to rush this release out this because of Ring's sudden decision to eliminate standard username/password authentication.  I haven't had time to proofread all of the docs or even test and fix everything and I don't use Docker in my own environment so it's something I have to test separately manually.  I've already spent way too many hours on this project the last few weeks, hours I don't really have, so thanks for pointing it out, I'll fix it.
