### ISSUE TITLE
Ding sensor stays on for too long

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [tsightler/ring-mqtt#524]
Hi everyone,
I have noticed that the Ding sensor takes about 5 minutes to change back to "clear" after pressing the button. 
Is it supposed to do that? I  won't get notifications if someone rings in those 5 minutes...
<img width="218" alt="image" src="https://user-images.githubusercontent.com/54823311/210626433-c47be51f-83ab-4f5e-a0f6-86bbac2d3512.png">

Is there a way to  change this ?

I'm running the HA addon and I have awired ring doorbell

Thanks

**Comment by jeffgraham-hub** [comment]
The motion and ding events for my doorbell and other cameras take 3 minutes to clear/reset. I assume this is the intended behavior, but I will let @tsightler confirm that.

**Comment by tsightler** [comment]
This topic should likely have been asked in the discussion forum, not opened as an issue.

Ring cameras/doorbells do not really have state, they mostly just trigger events called "dings".  There are two kinds of dings a "ding" ding, i.e. a doorbell press, and a "motion" ding and these dings include metadata as to when they expire.  I'm not sure what Ring uses the expire time for, but I think it's used to determine if the event was answered or not, i.e. any live view of the camera within the expire time is considered an "answered" ding.

As dings are simply immediate events, but ring-mqtt has to translate them into a state of some sort, I made the decision to use the expire time of the ding as the state.  Any time there is a non-expired "ding" then the state is "on", any other time the state is "off".  Since the expire time of each ding is 180 seconds, it will always be at least this long and will be extended by this much for each new event.  This actually made total sense at the time because the Ring motion sensors also maintained similar state for 180 seconds, so it provided a consistent experience between the cameras and the alarm motion sensors.

However, saying that, I've recently purchased a 2nd generation motion sensor and noticed it uses a much shorter time for motion state, so perhaps it makes sense to shorten the ding time to something like 30 seconds or maybe to the same as the record time since Ring cameras don't send new events while they are recording.

Note however that, even now, ring-mqtt does send a state update for each new ding, but of course if the state is already "ON" then Home Assistant would not recognize this as a state change and would not send a new notification.  However, you can always trigger on something else, like the "Last Ding" attribute, which should update with every new ding so a trigger on "last ding" with the condition that the ding state is "on" should trigger for each doorbell press even if the state is already on.
