### ISSUE TITLE
Bug: crash "loop" since updating to 5.1.0

### ISSUE THREAD

**Issue by Scope666** [tsightler/ring-mqtt#538]
### Describe the Bug

Monitoring the log, I can see it keeps crashing every 20 seconds or so

### Steps to Reproduce

Update to 5.1.0

### Expected Behavior

Not crashing.

### Log Output

[ring-mqtt.log.gz](https://github.com/tsightler/ring-mqtt/files/10575246/ring-mqtt.log.gz)

### Screenshots

![image](https://user-images.githubusercontent.com/31927547/216501034-1fd5d479-48d6-495d-8596-131563a4f98d.png)

### Config File

```shell
root@xbmcdown:/mnt/user/appdata/ring-mqtt# cat config.json 
{
    "mqtt_url": "mqtt://192.168.1.200:1883",
    "mqtt_options": "",
    "livestream_user": "",
    "livestream_pass": "",
    "disarm_code": "",
    "enable_cameras": true,
    "enable_modes": false,
    "enable_panic": false,
    "hass_topic": "homeassistant/status",
    "ring_topic": "ring",
    "location_ids": [
        ""
    ]
}
```

### Install Type

Docker via Unraid

### Version

v5.1.0

### Operating System

Unraid

### Architecture

x86_64

### Machine Details

12th Gen Intel® Core™ i7-12700 @ 2079 MHz

**Comment by tsightler** [comment]
I believe this should be fixed in the dev branch if you don't mind giving it a spin.

**Comment by Scope666** [comment]
Think I figured out how to do it on Unraid:

```2023-02-03T03:23:43.439Z ring-mqtt Succesfully started the token generator web UI
-------------------------------------------------------
| Ring-MQTT with Video Streaming                      |
| Docker Edition                                      |
|                                                     |
| For support questions please visit:                 |
| https://github.com/tsightler/ring-mqtt/discussions  |
-------------------------------------------------------
Updating ring-mqtt to the dev version...
Installing node module dependencies, please wait...
The ring-mqtt-dev branch has been updated.
-------------------------------------------------------
ring-mqtt.js version: 5.1.1
Node version v18.12.1
NPM version 9.1.2
git version 2.38.3
-------------------------------------------------------
Running ring-mqtt...

**Comment by tsightler** [comment]
Yep, that looks right.  I've got everything staged to push 5.1.1 once you confirm the crash is gone.  I can't really test it because I don't have a non-Pro version of the Chime, but the fix seemed obvious so hopefully that was it.

**Comment by Scope666** [comment]
No dice, same error.     :(

![image](https://user-images.githubusercontent.com/31927547/216506952-9edf4c7b-2836-43fb-8431-b12149a36678.png)

**Comment by Scope666** [comment]
PS ... My Chime is a "Chime Pro (1st Gen)" as reported in the Ring app.

**Comment by tsightler** [comment]
Well, that makes this more complicated.  Does the 1st gen Chime Pro not have a nightlight?

I'll likely require a data discovery from your device to fix it:
https://github.com/dgreif/ring/wiki/Data-Discovery

**Comment by Scope666** [comment]
PPS ... perhaps there's a way to "hide" my Chime Pro from ring-mqtt since I don't really need it for HA?

Here's the Discovery output:

```         "chimes":[
            {
               "description":"Downstairs",
               "firmware_version":"Up to Date",
               "kind":"chime_pro",
               "settings":{
                  "volume":9,
                  "status_led_enable":true,
                  "network_settings":{
                     "multi_net_pref":1
                  }
               },
               "features":{
                  "ringtones_enabled":true,
                  "cfes_eligible":false,
                  "dynamic_network_switching_eligible":false
               },
               "owned":true,
               "alerts":{
                  "connection":"online",
                  "ota_status":"successful"
               },
               "do_not_disturb":{
                  "seconds_left":0
               },
               "stolen":false,
               "is_sidewalk_gateway":false,
               "created_at":"2020-05-02T03:01:27Z",
               "shared_at":null,
               "deactivated_at":null

**Comment by Scope666** [comment]
There is a "status light" you can turn on/off in the app.  Don't think it has a separate nightlight.

**Comment by tsightler** [comment]
Ah, looking at the Ring documentation for the Chime Pro 1st generation it doesn't appear to have a nighlight.  I guess only the Chime Pro 2nd generation has a nightlight.  So the code is currently trying to get a status for a nightlight that doesn't exist.

**Comment by Scope666** [comment]
Is there a way to do an IF loop for the nightlight status?  `If generation=1 skip` kind of thing?

Or perhaps just ignore gen 1 Chime Pros altogether...

**Comment by tsightler** [comment]
You can just downgrade to previous version, that's by far the easiest thing to do.  But I'll have a fix in the dev branch in a few minutes now that I know the v1 Chime Pro didn't have a nightlight.  That's the problem when you are trying to reverse engineer things but you don't have access to every version of every device.

**Comment by Scope666** [comment]
Awesome, let me know when you want me to test.  More than happy to pull any logs/info you need.   (or anything else for that matter)

BTW, I want to let you know that I LOVE this addon.  It's added so much more capability to my camera page in HA.  I have it setup where if you click the thumbnail, you go live... if you click a little video icon, it plays the last recording ... super slick.

![image](https://user-images.githubusercontent.com/31927547/216510400-6c4033a1-1247-4243-a211-5baffd30e1bb.png)

(I started out with Ring cameras, then evolved to RTSP IP cams in Blue Iris.  My camera page shows a blended view of both systems)

**Comment by tsightler** [comment]
Thanks, if you could test the dev branch one more time please, that would be great.  I've changed the code to attempt to detect the presence of a nightlight in the device data vs just relying on model.  Hopefully I didn't screw that up.  If it works, I'll push a 5.1.2 quickly so not too many people will get the broken builds.  Fortunately, it would only impact the subset of people that have Chime Pro 1st generation, but as this addon has >5000 users now, that's likely to still be a lot of people!

**Comment by Scope666** [comment]
Ok, stand by ... switching to dev now...

**EDIT:** Looks like you got it that time!  

Besides installing the RTSPtoWebRTC add-on, what else do I need to do to start using that?

Thanks again!!!

**Comment by tsightler** [comment]
Basically you install the go2rtc addon and then configure RTSPtoWebRTC integration to point to it, that's it for the most part, although you may need to forward ports if you want access outside of a local network.

https://github.com/AlexxIT/go2rtc#go2rtc-home-assistant-add-on

This setup provides live stream startup times of around 2 seconds on average (I've seen as low as 1.7 seconds), with latency typically between .5-1.0 seconds, by using the native WebRTC viewing in the browser.  AlexxIT has done an amazing job making it transparent and super easy to setup.

Note that I prefer the use of the RTSPtoWebRTC integration vs using the WebRTC card because I actually like the functionality of the Picture Glance cards as I have mine setup very similar to yours.  The only signfiicant difference is I swapped the live and event streams.

**Comment by tsightler** [comment]
Since this should be fixed and I've already pushed out v5.1.2 I'm going to go ahead and close this.  Thanks for your help, especially for the thorough bug report and quick testing of fixes, it is greatly appreciated!

**Comment by Scope666** [comment]
I saw this in the logs, so thought go2rtc was cooked in:

```
2023-02-03T04:56:38.703Z ring-rtsp Creating go2rtc configuration and starting go2rtc process...
2023-02-03T04:56:38.720Z ring-rtsp Successfully wrote go2rtc configuration file: /data/go2rtc.yaml
2023-02-03T04:56:38.731Z ring-rtsp The go2rtc process was started successfully
2023-02-03T04:56:38.782Z ring-rtsp [go2rtc] INF go2rtc version 1.1.1 linux/amd64
2023-02-03T04:56:38.782Z ring-rtsp [go2rtc] INF [rtsp] listen addr=:8554
2023-02-03T04:56:38.782Z ring-rtsp [go2rtc] INF [webrtc] listen addr=:8555
```

I see he has a Docker version, I'll give it a shot.

**Comment by tsightler** [comment]
go2rtc is baked in, and, but right now the baked in go2rtc is configured only as an on=demand rtsp servier, basically a drop in replacement for rtsp-simple-server which was used by prior version.  In the future I might allow it to be configured for WebRTC so it could be used directly.

But indeed, without being an addon it does ramp up the complexity to configure it because you have to manually setup all the RTSP streams in go2rtc while the addon normally does this by gaining access to the HA /config directory which is an option for an HA addon.  However, you can manually run go2rtc either on your HA host, or as a Docker container, it just requires more configuration.

The main reason I switch to go2rtc internally is it has some features that I hope to implement in a future version of ring-mqtt that I hope will make Ring cameras at least marginally useful with tools like Frigate, but that's the future.  For now, the goal was simply to replace rtsp-simple-server and make sure it was transparent.

**Comment by Scope666** [comment]
I installed the Docker version, and installed the RTSPtoWebRTC integration.  I added one of the streams as shown in the INFO --> ATTRIBUTES --> STREAM SOURCE dialog like this:

![image](https://user-images.githubusercontent.com/31927547/216518733-94b2072c-2698-4798-b91c-d3ced1741126.png)


Not sure if HA just auto uses it or if I have to do something else.   (not sure how to tell if it's working)

EDIT:  I see go2rtc seems to be picking up the stream names by itself from ring-mqtt

**Comment by Scope666** [comment]
btw, live stream start time is WAY faster now.  I'd say it's gone from almost 10 seconds down to 2 or less....  bravo!!!!

**Comment by tsightler** [comment]
Most of that is because of WebRTC and go2rtc, not really anything I did.  In the end the RTSP stream itself was always pretty fast at starting up, usually 2-3 seconds at most, but then HLS streaming in HA adds 3-5 seconds of buffering + whatever the interval between key frames (about 2 seconds for Ring cameras from what I can tell.

But I'm pretty happy with the current stream startup code, I don't think I could reduce it much more.  One of the big issues is that RTSP generally has to startup within 5 seconds or the client will time out the connection (this doesn't include buffer time).  With the old code I was seeing a number of cases from users where the stream startup time was taking 5-6 seconds, just longer than the 5 second timeout.

Now, at my home under near perfect conditions (wired camera connected to 1GbE fiber internet) the startup time is commonly 2 seconds and, a few weeks ago, I happened to be in Eastern Europe for a work trip and decided to test the live streams while I was there by running ring-mqtt on my laptop which was, using my 4G roaming phone connection as a hotspot, so ~160ms latency to Ring servers in the US, and only about 15Mpbs total where I was staying, yet the stream startup time was still consistently ~3.5-4 seconds and I never had a single stream fail to start due to missing the 5 second window.

**Comment by Scope666** [comment]
I went 100% ALL-IN today, and completely removed the stock Ring Integration.  I added your event selector to the camera cards, this way you can just change it there and step back through motion events.  I'm using the Person X (transcoded) to get the timestamps, super useful!!!

![image](https://user-images.githubusercontent.com/31927547/216659279-aad6d918-4bfe-473f-8298-89ef74ce469e.png)
