### ISSUE TITLE
Negotiate Codecs Failed

### ISSUE THREAD

**Issue by homeautoma** [tsightler/ring-mqtt#543]
Hi there, having problems with configuring a live stream or any form of camera stream either through the switch or setting up a Generic IP Camera.
I am using **Home Assistant OS on a Pi 4**. I am also using **EMQX** as a MQTT server, the same issue also happens on the official Mosquitto version also.

The logs show the following:

`2023-02-08T14:13:25.291Z ring-mqtt [Camera] Received set live stream state ON`

`2023-02-08T14:13:25.293Z ring-mqtt [Camera] Starting a keepalive stream for camera`

`2023-02-08T14:13:25.317Z ring-mqtt [Camera] The keepalive stream has started`

`2023-02-08T14:13:25.325Z ring-rtsp [go2rtc] DBG [rtsp] new consumer stream=xxxxxxxxxxxx_live`

`2023-02-08T14:13:25.326Z ring-rtsp [go2rtc] DBG [streams] probe producer url=exec:/app/ring-mqtt/scripts/start-stream.sh xxxxxxxxxxxx live ring/xxxxxxxxxxxx/camera/xxxxxxxxxxxx {output}`

`2023-02-08T14:13:25.327Z ring-rtsp [go2rtc] DBG [exec] run url="exec:/app/ring-mqtt/scripts/start-stream.sh xxxxxxxxxxxx live ring/xxxxxxxxxxxx/camera/xxxxxxxxxxxx rtsp://localhost:8554/xxxxxxxxxxxx"`

`2023-02-08T14:13:25.354Z ring-rtsp [Camera] Sending command to activate live stream ON-DEMAND`

`2023-02-08T14:13:25.367Z ring-mqtt [Camera] Received set live stream state ON-DEMAND rtsp://localhost:8554/xxxxxxxxxxxx`

`2023-02-08T14:13:25.368Z ring-mqtt [Camera] ring/xxxxxxxxxxxx/camera/xxxxxxxxxxxx/stream/state ON`

`2023-02-08T14:13:25.369Z ring-attr [Camera] ring/xxxxxxxxxxxx/camera/xxxxxxxxxxxx/stream/attributes {"status":"activating"}`

`2023-02-08T14:13:25.371Z ring-mqtt [Camera] Initializing a live stream session for Ring cloud`

`2023-02-08T14:13:25.522Z ring-rtsp [Camera] State indicates live stream is activating`

`2023-02-08T14:13:25.891Z ring-mqtt [Camera] Live stream session successfully initialized, starting worker`

`2023-02-08T14:13:25.896Z ring-wrtc [Camera] Live stream WebRTC worker received start command`

`2023-02-08T14:13:26.001Z ring-wrtc [Camera] Live stream transcoding process is starting`

`2023-02-08T14:13:26.145Z ring-wrtc [Camera] Websocket signalling for Ring cloud connected successfully`

`2023-02-08T14:13:26.359Z ring-mqtt ERROR - Uncaught Exception`

`2023-02-08T14:13:26.359Z ring-mqtt Error: negotiate codecs failed.
`

`2023-02-08T14:13:27.362Z ring-mqtt The ring-mqtt process is shutting down...
`

`2023-02-08T14:13:27.364Z ring-mqtt Setting all devices offline...
`

`2023-02-08T14:13:27.366Z ring-rtsp exit OK
`

`2023-02-08T14:13:27.380Z ring-mqtt [Camera] The keepalive stream has stopped
`

The system then reboots and operates its usual snapshot mode at defined intervals.
I have emailed a clearer version of the logs, but hopefully this also illustrates the issue. 

Many Thanks!

**Comment by tsightler** [comment]
Hi, so that's an interesting one, not one I have not seen previously.  One thing I notice really strange is the keepalive stream is trying to start, are you manually doing that?  Can you send me the full logs please, not just the last section?  You can send them via email if you prefer.

**Comment by homeautoma** [comment]
Hi there! All emailed. In this instance I have manually clicked the live stream switch under the MQTT device, but the same occurs when inserting the HTTP:// and RSTP information when adding a Generic IP Camera.

**Comment by tsightler** [comment]
Thanks for opening this issue and providing logs, this is a very interesting problem, I have sent you some feedback directly via email and we can determine how to proceed.

**Comment by tsightler** [comment]
So it seems this problem is related to the fact that Ring is rolling out support for HEVC/H.265 video codec format for some devices and cameras.  There are quite a few issues in the Ring forums around device compatibility with this which makes sense, as there are still tons of gaps in coverage of H.265 in end-user devices.

In 5.1.3, instead of crash, this codec mismatch will be logged, and the recommendation made to switch the camera to legacy video mode for that camera as documented on the [Ring support page](https://support.ring.com/hc/en-us/articles/4417503172116-Legacy-Video-Mode-). 

I'll have to think carefully about how to deal with this going forward.  IMO, Ring is a little premature in rolling this out, especially in making it a default that people have to disable, but I could potentially just pass through whatever stream Ring sends out.  I'm afraid that will lead to more support issues due to browser and device compatibility that people will struggle to understand.  This is less of an issue when viewing in the Ring web console because the API used there lets the browser create the intial offer, so Ring can answer as appropriate, but for the API used in ring-client-api, Ring creates the initial offer and it only includes either H.264 or H.265 based on the setting of Legacy Video Mode.  It's a real pain.

**Comment by tsightler** [comment]
Released 5.1.3 which traps the error and logs a message about Legacy Video Mode.
