### ISSUE TITLE
v5.1.2 loads CPU and memory until node process runs out of memory and is terminated (1GB system)

### ISSUE THREAD

**Issue by redloro** [tsightler/ring-mqtt#546]
### Describe the Bug

CPU and memory pegged until node process runs out of memory and is terminated

### Steps to Reproduce

Upgrade from v.5.0.5 to v5.1.2 and start the service

### Expected Behavior

Should not consume all CPU and memory and crash

### Log Output

```shell
Unfortunately I do not have any log outputs... just the output from the console when the node service crashes when it runs out of memory
```

### Config File

```shell
mqtt_url: mqtt://auto_username:auto_password@auto_hostname
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: ""
enable_cameras: true
enable_modes: false
enable_panic: true
branch: addon
debug: ring-*
location_ids:
  - xxxxxxxxxxxxxxxxxx
enable_volume: true
snapshot_mode: all
mqtt_host: <auto_detect>
mqtt_port: <auto_detect>
mqtt_user: <auto_detect>
mqtt_password: <auto_detect>
ring_token: ""
```

### Install Type

Addon

### Version

v.5.1.2

### Operating System

Home Assistant OS

### Architecture

aarch64

### Machine Details

Raspberry Pi 3B+

**Comment by redloro** [comment]
Note that I downgraded back to v5.0.5 and it works perfectly.

**Comment by tsightler** [comment]
I don't know how many cameras and total devices you have, but I see you only have a RPi3b so I assume only 1GB RAM, that's probably not going to be enough going forward if you have more than a 3-4 cameras.  Without logs it's really impossible to have any idea what the problem is so, since you didn't provide any, I'll close this.  Feel free to re-open if you can provide logs.

**Comment by redloro** [comment]
I've got a bunch of cameras and devices but everything has worked great up until v5.1.2... here's a log from a crash... [addon_03cabcc9_ring_mqtt-crash.log](https://github.com/tsightler/ring-mqtt/files/10703507/addon_03cabcc9_ring_mqtt-crash.log)

look at line 305 where it says...
```
Feb 09 15:39:09 homeassistant kernel: Out of memory: Killed process 68623 (node) total-vm:10113076kB, anon-rss:107012kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:528kB oom_score_adj:200
```
this is the node process running ring-mqtt.

I was running `top` and could see the process take over and then die after a few minutes and it just keeps on going.  I've got more log files and can reproduce as needed.  Just let me know if you need anything or will not fix.

Thanks!

**Comment by tsightler** [comment]
I don't really know if there is anything to fix.  It's expected that 5.1.0 and later will use more memory than prior versions for cases where there are more cameras that cores.  Prior versions used a worker thread pool based on number of cores-1 for the streaming engine, while 5.1.0 and later create a worker thread per camera.  Thus, if you have 5 cameras (that's all I see in the log) you'll have 2 extra worker threads.  Now these threads are only about 20-30MB/each, so I wouldn't expect moving from 3 to 5 would make a difference, but you said you have "a bunch of cameras of devices" so you may have more than show in this log.

That would also explain why the CPU might run away, the worker threads are initialized on startup as the cameras are discovered, so all those threads firing off will create a spike of CPU and memory usage during startup, although it should settle down.  Combine that with the additional load from asynchronous loading due to the move to ESM, and the extra VM overhead for Node 18, and something that worked before might not work now.

That being said, I don't really understand from the log why your OOM killer is kicking in, it's only showing 107MB resident set for the Node process, which is nothing really.  You might consider increasing the swap size and see if you can get past initialization.  I have 8 cameras, and I lowered my dev system to 1GB of RAM, and everything still loaded up just fine.  Node process is using about 350MB, which is about what I would expect and about 120MB more than prior versions, but that system only has 2 cores, so previously it would have had 1 worker thread vs 8 worker threads now.

**Comment by tsightler** [comment]
I lowered the memory on my HA dev system to 1GB and did some testing.  The ring-mqtt process was able to start up and things worked, but it was on the edge.  This is a dev system with no other addons except go2rtc and no automations or anything, just base HA and the handful of things I need for development and testing.

My dev system is x86 so the RAM usage for ARM processes is usually about 5-10% higher so I removed 128GB.  The process still started, but swap was 100% used and there were random failures and lots of stalling.

Unfortunately, that's just the nature of things, memory usage constantly goes up.  1GB is basically considered the bare minimum usable for HA with perhaps a few small addons, ring-mqtt is, unfortunately, not a small addon, its memory usage is fairly large.  This is not really due to ring-mqtt itself, but mostly due dependencies so I don't have much direct control over the memory usage.  Between the new worker thread implementation, and additional dependencies, I think we've just tipped your system over the edge.

The Home Assistant forum is littered with threads of people having various issues with 1GB systems.  You could maybe use some of the hacks people there have, such as increasing the swap file (by default HAOS allocates 25% of RAM size to swap).  If you doubled that it might give it enough headroom to start up.  It would probably also still work if you disable camera support.

You can of course keep using 5.0.5, but, realistically, I don't think ring-mqtt with camera support enabled is going to run reliably on a system with just 1GB.  I'll put a note in the FAQ about this.

**Comment by redloro** [comment]
Hey thanks for your tip about the swap size... increased the swap to 2GB and it got up and running no problem! Tested started, stopping and rebooting and it's working fine now.  Thanks for the help and for supporting a wonderful addon!

**Comment by tsightler** [comment]
That's good to know and helps confirm the analysis.  I still suspect there might be some side effects from running on such a low memory state, but maybe it will work fine, a lot of the load is just right there at the start when it is initializing the worker threads.
