### ISSUE TITLE
Add-on Setup

### ISSUE THREAD

**Issue by Steeleio** [tsightler/ring-mqtt#56]
First, let me say what an awesome job you have done with your Ring Integrations. I am running Hass.io 105.5 and can't for the life of me get it to connect to the mosquitto broker. The broker logs show socket error on client and the add-on shows "Unable to connect to MQTT broker. Connection refused: Not authorized" I am guessing this is something I forgot to input or have missed on the setup. Any help you can provide would be much appreciated!

**Comment by sktaylortrash** [comment]
Not authorized sounds a lot like your username and password for the MQTT broker are wrong in the config file

**Comment by Steeleio** [comment]
I used the default (blank).

**Comment by tsightler** [comment]
Questions about the addon  should go against the addon specific Github page as this issue is not related to the ring-mqtt script.

Regardless, "blank" is unlikely to work unless you've configured the Mosquitto addon to allow anonymous connections.  The mosquitto addon documents this, but with recent versions it requires more than just setting "anonymous: true" because it's considered unsafe, so they make you set an ACL as well.

By default the mosquitto addon alloww connections from Home Assistant users.  You can use the same username/password that you use to login to your Home Assistant UI, however, I suggest creating a service account just for this plugin.  Go to "Configuration...Users" and add a user (they can be a regular user, not adminstrator).  Then in the ring-mqtt configuration use this username/password as the mqtt_user/mqtt_pass settings.

The fact that the Mosquitto addon uses Home Assistant users by default is documented in the ring-mqtt-hassio-addon (in the section on mqtt_user/mqtt_pass config options), but I'm open to suggestions to making it more clear.

**Comment by Steeleio** [comment]
I do have an account that I only use for HA. I'll give your suggestions a try and thank you for your help.

**Comment by tsightler** [comment]
Closing this for now since there's nothing specific to this code.  Please feel free to post an issue on the Home Assistant forum if you need additional help with setup or open an issue on the Github page for the addon if you're experiencing problems.
