### ISSUE TITLE
Question? Request snapshot on demand?

### ISSUE THREAD

**Issue by Stefan300381** [tsightler/ring-mqtt#567]
Hi,

I've read the documentation about how snapshots work (like interval, or just motion based snapshots) and then I came across this statement:

>> the primary difference is in capability to take snapshots. While "high-power" devices can take a snapshot at any time and will generally respond to a snapshot request in a few milliseconds...

This makes we wonder, can I  request ring-mqtt to generate a snapshot on-demand using my high powered doorbell?
Ideally I'd like to request / generate e.g. 5-10 snapshots, each per second (e.g. after a Ding or Motion has been detected).
As you can imagine, I'm trying to compensate the lack of a ring protection plan ;-)

Thanks in advance

Stefan

**Comment by tsightler** [comment]
Not with ring-mqtt you can't!  Abuse of the Ring API by making snapshots that often would almost certainly end up with your requests being constantly throttled, and, if there were many users doing this, Ring would likely eventually be forced to take action to block, or at least make it much more difficult, for projects like this to even exist, while, until now, they've mostly just tolerated them.

That's why I have resisted calls to even add on-demand snapshots to ring-mqtt, because compensating for lack of a ring protection plan seems to be the common use case cited for that feature, but this project doesn't exist to make it easier to use Ring without a protection plan, actually, it's designed mostly to enhance the usefulness of Ring devices, but mostly for people that see enough value in the Ring ecosystem.  There are plenty of no fee options for cameras out there these days.

Even if I were to implement on-demand snapshots, it would be internally throttled in ring-mqtt to no more than one call every 10 seconds.

In the future, please consider using the discussion groups vs opening issues, for simple questions like this.
