### ISSUE TITLE
Bug: Issue when upgrading go2rtc to 1.3.1

### ISSUE THREAD

**Issue by broyuken** [tsightler/ring-mqtt#602]
### Describe the Bug

Ring-Mqtt streaming stops working after upgrading go2rtc to 1.3.1

### Steps to Reproduce

Upgrade go2rtc to 1.3.1, try to open a ring stream

### Expected Behavior

stream works

### Log Output

```shell
This bug has already been reported in the go2rtc repo here. This ticket is just for informational purposes if people come here with the same issue. 

https://github.com/AlexxIT/go2rtc/issues/319
```

### Config File

```shell
N/A
```

### Install Type

Addon

### Version

N/A

### Operating System

N/A

### Architecture

x86_64

### Machine Details

Intel NUC

**Comment by broyuken** [comment]
This issue has already been reported to AlexxIT here 

https://github.com/AlexxIT/go2rtc/issues/319

**Comment by tsightler** [comment]
Closing since, as far as I can tell, this bug has nothing to do with ring-mqtt itself, so no need to be tracked here.  Thanks.

Downgrading go2rtc to v1.2 should work fine.  I know you said you did this and it didn't help you, but I've tested it on 4 different instances, and it worked perfectly in all cases after downgrading.  Make sure you restart everything after reverting the go2rtc addon.

Also, you should note that Ring live streaming has been down pretty much all day on April 5th (and still is) so that could be the reason it still doesn't work after downgrading:

https://status.ring.com/

As usual, Ring's status page is a fantasy, it's been intermittently down (mostly down) for quite a bit longer than they acknowledge on the status page.

**Comment by broyuken** [comment]
Ah that could be the issue too, I didn't think to check ring itself as the app was still working for me. And I agree that this ticket can be closed, I just wanted to put something out there in case people come here with the same issue they can see that its known by you and not an issue with ring-mqtt

**Comment by tsightler** [comment]
Sure, it makes sense.  I could theoretically just leave it here open, but then it will just annoy me when I visit since there's not really anything I can do about it.  :-)

I'm surprised streaming is still working for you in the app.  Live streaming has basically been non-functional for me since around 10AM this morning.  It was about 2 hours after that when Ring posted their first "There might be a problem" status with BS statements like "it only impacts Ring.com and 3rd parties" only to follow up 2 hours later with "it impacts a small number of iOS and Andriod devices".  I personally haven't been able to stream on anything for >5 hours. 

Ring has so many outages they just try to sweep under the rug, most are indeed short and I can forgive that to an extent (I still think it's dishonest to claim 100% uptime if you actually had more than six different 15 minute outages in the span of 3 months), but it's been tolerable, but I'm really starting to consider dumping these things even after all the time and money I've invested.

**Comment by broyuken** [comment]
I agree, I'm looking into moving to reolink or something similar thats all local. I only use ring because I use their alarm as well and have professional monitoring on it. But I may have had it with the cameras.

**Comment by tsightler** [comment]
I'm exactly the same, and really, and I've been pretty happy with the alarm, but there are definitely better options for the cameras these days.  But, as I have 8 of them, replacing them is a little bit of a pain, not to mention the investment.  However, the oldest ones are nearing 5 years old, so I've at least managed to get some good use out of them.  Perhaps I'll just start phasing them out.
