### ISSUE TITLE
Amazon Ring - Sensors found but with no values

### ISSUE THREAD

**Issue by spanzetta** [tsightler/ring-mqtt#615]
Hi
I did setup this addon, apparently with no errors... but the result is that my Ring sensors are all empty..
In the Log I see "no device found" at the end (see below)
What's wrong?
Thanks

![image](https://user-images.githubusercontent.com/49818743/233581218-b9bf1f6c-2232-49cd-8438-2ff6824b0c4b.png)

![image](https://user-images.githubusercontent.com/49818743/233580774-27a5018d-d69f-431f-b70b-f6bdf84c97cf.png)

**Comment by spanzetta** [comment]
Solved!!!
I was missing this particular
"Ring Intercom (**must set "enable_cameras" config option to "true"**"
Once enabled.. tack.. it works!!
Closed

**Comment by tsightler** [comment]
I'm trying to figure out a way to make intercoms work without this flag because I agree it's not very intuitive that intercom support would require camera support to be enabled.  The actual problem is that the option itself is somewhat misnamed at this point, the "enable_cameras" option actually enables all devices that require polling for updates.  In the early days it was only cameras that required polling, but now there are cameras, chimes, and intercoms, which all require polling.

I guess I could just enable polling all the time, it's not very heavy (only one poll every 20 seconds) and wouldn't really have any negative impact if users only had Ring devices that use the socket API instead (alarm and smart lighting), but it just feels wrong to enable polling when there are no polled devices.

The cleanest option is probably to connect, get the list of devices, and only enable polling if some devices that require polling were actually found.  It's on my backlog of improvements that I hope to implement one day.
