### ISSUE TITLE
Location keeps disconnecting - component restarts

### ISSUE THREAD

**Issue by eingram23** [tsightler/ring-mqtt#63]
On regular intervals (every 4 hours), I will get a message in my ring addon container log (using HASSIO) about the location being disconnected and reconnected:

2020-03-05T16:30:26.517Z ring-mqtt Location ca5d6eed-d9cd-4b5b-a9f1-6c6416756284 is disconnected

2020-03-05T16:30:28.286Z ring-mqtt Location ca5d6eed-d9cd-4b5b-a9f1-6c6416756284 is connected

Right after, it seems the component restarts as it will cycle through the discovery for every component and I will receive notifications (I have Node Red setup to notify when a door/window is open/closed) for each, resulting in a notification flood every time this happens.

**Comment by tsightler** [comment]
Thanks for the report, are you running the latest 3.1.0 version that was published just a couple of days ago as it already includes a fix that was intended to address this issue.  Basically it shouldn't trigger the republish unless the disconnect last longer than 60 seconds.

The republish code isn't really the script restarting it's just that after any disconnect/reconnect the script intentionally resends all state because the state of objects could have changed while the location was disconnected.  The reason it does this mulitple times is mainly because sometimes Home Assistant isn't ready to accept this data during startup or service restarts so the hackish fix was to just send discovery information 10 times every 30 seconds.

This is indeed troublesome for Node Red and I plan to add an option to disable discovery in the future.  However, doesn't Node Red have the option to store state so you can compare updates to previous state?

**Comment by eingram23** [comment]
I'll update to 3.1.0...currently on 3.0.0 Strange thing is...in my HASSIO/Supervisor Add-On Store, I have your repository added...but instead of showing an upgrade for 3.0.0 to 3.1.0, 3.1.0 is showing up as a separate component.  I assume I have to uninstall and then install 3.1.0.  

As for Node-Red, I think you can do that with folders, but it's beyond my knowledge level right now.

**Comment by tsightler** [comment]
3.1.0 should definitely help with your issue.  I'm not sure why the connection disconnects every four hours, I don't see that on my own install, but it could be some default lifetime on the websocket or something (the websocket connection itself is handled by the API, not my code, I just monitor it's status).  The new code simply waits 60 seconds if the websocket disconnects before tagging devices offline and starting the republish cycle.

I had another use report the issue with this Hassio addon store, I'm not sure why it is showing two different versions instead of an upgrade, maybe because I changed the name of the plugin slightly to be more consistent.  I'll have to research it next week.

I'll look to add the auto-discovery disable feature in the next version, it's pretty easy, just hasn't been high priority since most users are using it only with Home Assistant and it doesn't seem to cause HA any specific issue.

**Comment by sktaylortrash** [comment]
@KungFuJoe23  check out the [RBE (Report By Exception) node](https://flows.nodered.org/node/node-red-node-rbe) It only does something if the payload it receives is different than the last one it received. So you can just dump it on your flow right after the subscribing node. 
I use it because of lots of projects. That implement Home Assistant autodiscovery. Including my own, do the multiple send thing to accommodate startup delays and HA just generally not enjoying receiving tonnes of discovery messages at once.

**Comment by eingram23** [comment]
Thank you...3.1.0 appears to have fixed the issue!

**Comment by eingram23** [comment]
@sktaylortrash Thanks for the info...I will definitely look that up.

**Comment by tsightler** [comment]
Since the core problem reported here is the disconnect and 3.1.0 works around this, I'm going to go ahead and close this issue now but will keep in mind implementing the ability to control/disable the discovery behavior in a future version.
