### ISSUE TITLE
Ring Intercom - Could not publish attributes due to no health data

### ISSUE THREAD

**Issue by spanzetta** [tsightler/ring-mqtt#632]
### Describe the Bug

Starting from few days (don't know exaxtly when) some entities (battery, wireless and info) are not shown anymore (they are unavailable)..  while the other 2 (lock and ding) are available . It was working fine until few days ago

### Steps to Reproduce

Even after re-autenticate.. the problem remains

### Expected Behavior

See all entities available as it was before

### Log Output

```shell
2023-05-17T06:46:57.879Z ring-mqtt [Ingresso] ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/lock/state LOCKED
2023-05-17T06:46:58.326Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T06:47:23.903Z ring-disc Republishing existing device id: 343ea4b124bb
2023-05-17T06:47:23.992Z ring-disc HASS config topic: homeassistant/sensor/7bd72106-32fd-4e25-9e7a-841bb89a3392/343ea4b124bb_battery/config
2023-05-17T06:47:24.418Z ring-disc {
  name: 'Ingresso Battery',
  unique_id: '343ea4b124bb_battery',
  state_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/info/state',
  device_class: 'battery',
  unit_of_measurement: '%',
  state_class: 'measurement',
  value_template: '{{ value_json["batteryLevel"] | default("") }}',
  json_attributes_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/battery/attributes',
  availability_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  device: {
    ids: [ '343ea4b124bb' ],
    name: 'Ingresso',
    mf: 'Ring',
    mdl: 'Intercom'
  }
}
2023-05-17T06:47:24.510Z ring-disc HASS config topic: homeassistant/lock/7bd72106-32fd-4e25-9e7a-841bb89a3392/343ea4b124bb_lock/config
2023-05-17T06:47:24.512Z ring-disc {
  name: 'Ingresso Lock',
  unique_id: '343ea4b124bb_lock',
  state_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/lock/state',
  command_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/lock/command',
  availability_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  device: {
    ids: [ '343ea4b124bb' ],
    name: 'Ingresso',
    mf: 'Ring',
    mdl: 'Intercom'
  }
}
2023-05-17T06:47:24.514Z ring-disc HASS config topic: homeassistant/binary_sensor/7bd72106-32fd-4e25-9e7a-841bb89a3392/343ea4b124bb_ding/config
2023-05-17T06:47:24.516Z ring-disc {
  name: 'Ingresso Ding',
  unique_id: '343ea4b124bb_ding',
  state_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/ding/state',
  json_attributes_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/ding/attributes',
  icon: 'mdi:doorbell',
  availability_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  device: {
    ids: [ '343ea4b124bb' ],
    name: 'Ingresso',
    mf: 'Ring',
    mdl: 'Intercom'
  }
}
2023-05-17T06:47:24.518Z ring-disc HASS config topic: homeassistant/sensor/7bd72106-32fd-4e25-9e7a-841bb89a3392/343ea4b124bb_info/config
2023-05-17T06:47:24.519Z ring-disc {
  name: 'Ingresso Info',
  unique_id: '343ea4b124bb_info',
  state_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/info/state',
  device_class: 'timestamp',
  value_template: '{{ value_json["lastUpdate"] | default("") }}',
  json_attributes_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/info/state',
  icon: 'mdi:information-outline',
  availability_topic: 'ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  device: {
    ids: [ '343ea4b124bb' ],
    name: 'Ingresso',
    mf: 'Ring',
    mdl: 'Intercom'
  }
}
2023-05-17T06:47:28.526Z ring-mqtt [Ingresso] ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/ding/state OFF
2023-05-17T06:47:28.667Z ring-mqtt [Ingresso] ring/7bd72106-32fd-4e25-9e7a-841bb89a3392/intercom/343ea4b124bb/lock/state LOCKED
2023-05-17T06:47:32.335Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T06:48:10.659Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T06:53:10.484Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T06:58:10.797Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:03:10.775Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:08:11.394Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:13:10.935Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:18:10.886Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:23:13.052Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:28:11.114Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:33:10.738Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:38:10.906Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:43:10.933Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:44:58.399Z ring-mqtt Received updated refresh token
2023-05-17T07:44:58.403Z ring-mqtt Saving updated refresh token to state file
2023-05-17T07:44:59.530Z ring-mqtt Successfully saved updated state file: /data/ring-state.json
2023-05-17T07:48:11.021Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:53:10.805Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T07:58:11.020Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T08:03:11.735Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T08:08:11.194Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T08:13:10.837Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
2023-05-17T08:18:11.125Z ring-mqtt [Ingresso] Could not publish attributes due to no health data
```

### Screenshots

![image](https://github.com/tsightler/ring-mqtt/assets/49818743/fae72707-2282-4e55-be5a-34d77eb8a74e)

### Config File

```shell
mqtt_url: mqtt://mosquitto:xxxxxxxxx@core-mosquitto:1883
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: ""
enable_cameras: true
enable_modes: false
enable_panic: false
branch: addon
debug: ring-*
location_ids:
  - 7bd72106-32fd-4e25-9e7a-xxxxxxxxxxxxxxxxx
```

### Install Type

Addon

### Version

v5.2.2

### Operating System

Home Assistan OS

### Architecture

Arm v8

### Machine Details

Pi3A+

**Comment by lesgrebe** [comment]
+1 look here: https://github.com/tsightler/ring-mqtt/issues/633

**Comment by tsightler** [comment]
Thanks for the information all.  Unfortunately, as I do not own a Ring intercom device, I'm unable to troubleshoot issues related to it unless someone is willing to share their device with me.  It's very likely that Ring is changing API behavior for the Intercom device since it seemed it was mostly just bolted on to the old doorbell camera API to rush it out the door quickly, but it will likely require deep investigation.

Are all of you definitely using the primary account for ring-mqtt, or are you setting up separate accounts?

Out of curiosity, can one of you share a screenshot of the "Device Health" button in the Ring app for the intercom device?  It's that specific API call which ring-mqtt uses so I'm wondering if it's showing correctly in the Ring app.

**Comment by lesgrebe** [comment]
Hi,

first of all, thanks for your efforts!

What do you mean with primary account? In Home Assistant I´m using an seperate account which is called mqtt - see screenshot below:
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/c4360996-79ee-4025-9499-24fc15b8a06a)

Here are the screenshots from the ring app "device health". Unfortunately it is in german but the signals should be available like before. As you mentioned above maybe something in the api has changed. This is what I think because it worked well the last months and this behavior is almost simultaneously on both users (@lesgrebe  and @spanzetta ).

![image](https://github.com/tsightler/ring-mqtt/assets/37287548/4bd42b3b-928b-4970-9f42-0ce15f7dbc81)
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/1a09c70a-72ef-4caf-939b-2542f790f11a)

How can I share my device with you? Do you mean I´ve to send the hardware to you?

Regards
Michi

**Comment by lesgrebe** [comment]
Hello again,

I don´t know why but for some reasons the entites for _battery_ and _info_ SOMETIMES work again only for _wireless_ the state is ALWAYS unavailable...

![image](https://github.com/tsightler/ring-mqtt/assets/37287548/65740a02-8136-45a6-9aa5-7dfd0541eb36)

Logs:
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/6ef9dfb4-6928-4536-aa28-5ca92e71edd2)

**Comment by tsightler** [comment]
By primary account I mean the main Ring owner account, nothing to do with HA.  In other words, the account used to authenticate to Ring in ring-mqtt.

By sharing I mean in the Ring app where you can grant access to your devices with other users by entering their email address, which will allow my Ring account to "see" any devices you choose to share.

I think we should just wait and see if it clears up in a few days/weeks, since users are just suddenly reporting this, and the logs show that the API call just randomly worked a single time (well, mostly).  My guess is it could just be a temporary Ring API issue. 

They wouldn't necessarily feel this is important to report on their status page since they generally only update health data every few hours anyway and most users would never notice since the app just always caches the last state.  Ring basically never reports anything on their status page unless it's a major outage impacting heavily used functionality.

**Comment by lesgrebe** [comment]
Okay, let us wait.

And yes, i'm using my main account for the ring app and also for the mqtt authentification (I just have one account).

I can share my account (ONLY with you) for further actions. Just let me know.

Regards

**Comment by tsightler** [comment]
Actually, could you try the dev branch (just change branch config option from "addon" to "dev" and restart the addon)?  I've added a small amount of debug to see if we can tell what the response is from the health query.

Basically the way it works in the current code, it request the health data from the health endpoint for the device.  If the query fails it will print an error "Failed to retrieve health data for Intercom" and also should show the HTTP response error.  That's not happening, so it indicates that the API is returning "something".

The code then attempts to parse the response, looking for the "device_health" property.  If that fails, you end up with the "Could not publish attributes due to no health data" message that you are seeing.  In the dev branched I've added an extra step that, if it receives a response, but can't parse that response, it will output the response to the log.  Might be interesting to see.

**Comment by lesgrebe** [comment]
Okay I´ve changed it:
Before:
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/7f5f2b79-be24-486f-a8ea-b94c7db6e33c)

Now:
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/2ba2d79c-0ca3-4204-aa44-f9b4239f8a97)

Restart Addon:
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/521df96d-cefc-452d-9ad1-4e80c7c300fa)

![image](https://github.com/tsightler/ring-mqtt/assets/37287548/66c69d41-69ad-4632-a635-0fd1878b75a8)

LogFile:
[03cabcc9_ring_mqtt_2023-05-17T17-05-35.636Z.log](https://github.com/tsightler/ring-mqtt/files/11500843/03cabcc9_ring_mqtt_2023-05-17T17-05-35.636Z.log)

**Comment by tsightler** [comment]
Sorry, I messed up, if you could restart and give it one more try hopefully it will output the actual JSON and not just [object Object].

**Comment by lesgrebe** [comment]
Restart the addon or the system (Home Assistant)?

**Comment by tsightler** [comment]
Addon, just so it picks up the latest dev changes.

**Comment by lesgrebe** [comment]
Done and no problem ;)

Restart again and now you have the JSON in the LOG

[03cabcc9_ring_mqtt_2023-05-17T17-14-25.553Z.log](https://github.com/tsightler/ring-mqtt/files/11500897/03cabcc9_ring_mqtt_2023-05-17T17-14-25.553Z.log)

![image](https://github.com/tsightler/ring-mqtt/assets/37287548/618a95cc-81c6-4d41-b238-4d4bd1f4de3f)

**Comment by lesgrebe** [comment]
Seems like there is no information from the API Call, I think a problem on RING or something hast changed on RING API?!?

**Comment by tsightler** [comment]
It's possible that it's changed, but the device health API call is unchanged in the 5 years I've been working with the Ring API, and is used across all "polled" devices (cameras/doorbells/chimes and, most recently, intercoms) so I'd be a little surprised.  The fact that is returns data, but that data is totally useless, makes me think it more a system error vs a change, perhaps regional or device specific.

I won't have any time to look at this in the next 10 days or so anyway, so let's see what happens in that time.

**Comment by lesgrebe** [comment]
Agree, let's see what happens. Let me know if you need anything for troubleshooting!! Thank you!

**Comment by snigehere** [comment]
I am having a similar issue with some cameras which I have opened a discussion item about - the issue started a few days ago - https://github.com/tsightler/ring-mqtt/discussions/635

The log is reporting "Invalid state message" ... but it does seem intermittent ....

**Comment by tsightler** [comment]
@snigehere The issue you are reporting seems to be very different from the one here.  Your issue aligns with https://github.com/tsightler/ring-mqtt/issues/634 but the user closed the issue when I asked for full logs.

**Comment by lesgrebe** [comment]
It seems that there is (was) a problem on RING side beacause at the moment it works for me now (see logs and entites). Didn´t changed or restarted anything just waited a few hours. Lets have a look for how long its gonna do his job ;) - for now it works at least since 2023-05-17T22:56:24.155Z. As you can see no _"Could not publish attributes due to no health data"_ message in the logs.

LOG:
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/1f825d7b-f559-4003-81e2-9f7ceb19c9ae)

ENTITIES:
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/be44da91-1002-417c-ba6c-bc4263eba6a8)

RING-APP (Device health):
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/e27e83c7-be07-43ba-a145-5a9ee8df6db7)
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/a6fc1d48-cda1-42c8-8672-5ca1bd69e1fa)

**Comment by spanzetta** [comment]
Guys, now all entities are again working.... without doing anything..

Maybe it was a temporary problem with Ring API that they now solved (I see no other explanation).

For me the issue can be closed
