### ISSUE TITLE
Add-on install Failed

### ISSUE THREAD

**Issue by bjladner** [tsightler/ring-mqtt#72]
I have been using the ring-mqtt docker version for some time now with no problems.  I just recently switched from docker home-assistant (core) to the more official home-assistant (old hassio) on a VM.  I have everything working except for ring-mqtt.  I added the add-on repository for https://github.com/tsightler/ring-mqtt-hassio-addon and also https://github.com/tsightler/ring-mqtt-hassio-addon-dev and both are giving me the same problem.  When I click install, it fails with the only feedback:

>> Failed to install addon, Unknown Error, see logs

I checked the home-assitant logs and only saw this:

>> 2020-05-16 03:38:00 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook cd2681ae024947e41f98ef8b0650c546b0bb864368c5528d0f3fd0a2da1f73b7

I can't tell if this has anything to do with installing ring-mqqt-hassio-addon but I assume so since that is all I was doing.  Are there other logs I should check?  
Thanks for all your work on this project and thanks in advance for your help.

**Comment by tsightler** [comment]
You need to look at the Supervisor log, Supervisor -> System -> System Log.  You should see something like this:

```
20-05-16 13:35:20 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/01c01af7_ring_mqtt_dev
20-05-16 13:35:20 INFO (SyncWorker_1) [supervisor.docker.addon] Start build 01c01af7/amd64-addon-ring_mqtt_dev:3.1.0-beta2
20-05-16 13:36:06 INFO (SyncWorker_1) [supervisor.docker.addon] Build 01c01af7/amd64-addon-ring_mqtt_dev:3.1.0-beta2 done
20-05-16 13:36:06 INFO (MainThread) [supervisor.addons] Add-on '01c01af7_ring_mqtt_dev' successfully installed
20-05-16 13:36:21 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on 01c01af7/amd64-addon-ring_mqtt_dev with version 3.1.0-beta2
```
Well the above is obviously from a successful install, but the install process generally starts with logging the "Create Home Assistant add-on data folder" step so any errors should be after this entry.

The most common issues are lack of space to pull the repo, failure to pull the docker base image for your platform (HA images use Alpine linux which has an unreliable mirror system, IMO), and I've also seen some very unpredictable behavior with users running the 64-bit HassIO, build, which just seems to be an endless cause of problems.  Of course, there could be other issues, but failing to install the add-on is almost certainly not an issue with the add-on itself.

Also, you probably don't want to use the dev repo, that repo exist solely to make it easier for me to test the dev branch of ring-mqtt which is in constant flux and regularly broken.  I should probably note that in the readme for it.

**Comment by bjladner** [comment]
Thanks for your reply.  My log showed:

```
20-05-16 14:32:19 INFO (SyncWorker_5) [supervisor.docker.addon] Start build a98c085d/amd64-addon-ring_mqtt:3.1.0
20-05-16 14:32:27 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build a98c085d/amd64-addon-ring_mqtt:3.1.0: The command '/bin/ash -o pipefail -c npm install' returned a non-zero code: 1
```
I do have plenty of space on disk too.  Unless you want me to debug it more, I may just move back to the stand-alone docker for ring-mqtt only and just set up the mqtt broker for that.  It would have been nice to have all this on one VM, but I have another VM with docker.  
Thanks again and let me know if you need any more information

**Comment by tsightler** [comment]
Unfortunately that error is not very useful, I mean, sure, it says that "npm install" failed, but it doesn't say why it failed.  This is a very standard command which installs the required node modules during the Docker image build process and is common to tons of add-ons.  Typically when I've seen it fail it's been due to issues reaching the npm repository.

I've had a few people where it failed one day and then worked the next or they had to change their DNS servers to get it to work (perhaps to get a different mirror or something).  I don't really have any control over this as npm is just the node package manager, if it doesn't work I can't do anything about it.

Based on that, I'm going to close this as it's obviously not anything wrong with the addon itself, for some reason the Docker build process is failing in your environment running a simple, standard command.  Note that the non-Hassio Docker build also runs the same "npm install" command so if it works fine it definitely points to a build issue on the Hassio install.  Do you happen to be using the 64-bit Hassio instead of the recommended 32-bit version?  Just curious as I've had tons of similar weird issues reported with it.

**Comment by bjladner** [comment]
It is 64 bit.  I just used the original docker on another machine and pointed it at my mqtt broker on HA instead of debugging the addon install.  All other addons are working though.  Thanks for your help and all your work on this.  I love the ring-mqtt component.
