### ISSUE TITLE
Auto Restart When Ring Alarm Determined To Be Unavailable

### ISSUE THREAD

**Issue by jun3280net** [tsightler/ring-mqtt#73]
Hi there!  Thank you so much for making this integration.  This is a god send, as my wife and I are terrible with arming the Ring security system.  Being able to leverage the automation capability of Home Assistant will make this process much easier.  That said, I've noticed when I restart Home Assistant (I use Home Assistant Supervised with Ring HASS.IO addon), Ring will register as "unavailable".  I simply restart the addon - and all is well.  I was hoping you could build in the functionality for the addon to restart on it's own (attempt 2 or 3 times) so it is in sync with Home Assistant.

Thanks and keep up the fantastic work.

**Comment by sktaylortrash** [comment]
If you setup the part in the instructions called [Optional Home Assistant Configuration](https://github.com/tsightler/ring-mqtt#optional-home-assistant-configurationl)  It will do what you are looking for.

**Comment by tsightler** [comment]
If you are seeing this issue with HASS.IO could you please post the logs from the addon when it is in this state to the issues on the addon page.  Several others have reported this issue with the addon but I cannot reproduce the problem and so far nobody has posted any logs that I have requested.  I believe the issue is maybe related to the addon starting before the network is up, but, without logs I have no way to determine any possible cause.

https://github.com/tsightler/ring-mqtt-hassio-addon/issues/11

Since the issue is with the addon I'm going to close this issue here.  Please feel free to pursue the issue on the addon repo.
