### ISSUE TITLE
No Docker Hub image for v5.6.3

### ISSUE THREAD

**Issue by leccelecce** [tsightler/ring-mqtt#738]
There doesn't seem to be a Docker Hub image for the latest 5.6.3 release: https://hub.docker.com/r/tsightler/ring-mqtt/tags?

**Comment by tsightler** [comment]
Yes, i don't always push the Docker images or update the addon right away.  It's always possible to test the latest cose from Github with the branch feature.

**Comment by leccelecce** [comment]
Just to check, are you suggesting to checkout the branch tag locally and build the Dockerfile locally? Are any other steps required?

Would you be amenable to a PR for a Github Action to publish automatically based on this?

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub

**Comment by tsightler** [comment]
No, I'm suggesting to simply use the [branch selection feature](https://github.com/tsightler/ring-mqtt/wiki/Installation-(Docker)#branch-selection) to pull down the latest ring-mqtt version from Github on demand in the existing container.  This feature is primarily focused at making it easy to test the dev branch, but it works just as well for pulling in the latest version.

I appreciate the offer of a PR but the build process is already fully automated, just not through Github Actions.  I just don't always publish the images immediately after a release because it impacts so many more users (this project now has ~10,000 users).  In this case I knew I would be out of town so I decided to hold back to docker and addon updates until I get back since the current version is stable.  Advanced users that want to test the very latest can use the branch option or build their own image, I'll publish updated docker images and addons versions when I'm ready.
