### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by hisham211** [tsightler/ring-mqtt#74]
I didn't know where else I can contact you. So, I figured opening an issue might work. I just wanted to say thank you for making this add-on for HA. This was a game changer for me. I had my Ring Home Alarm first and started looking for an automation platform that would support it. It was hard to find one that supported anything other than the Ring cameras, until I came across your add-on.

I've worked in IT (infrastructure) for 20+ years now and I know how hard it is to build, maintain and support an effort like this one in your spare time. If you don't hear it enough, Thank you! Your work really makes a difference to all of us Ring Alarm owners.

Keep up the good work!

**Comment by tsightler** [comment]
Thank you for the kind words.  I never really expected this project to have much of a following, I mainly did it to try to learn Javascript/Node at least a little.  It's been interesting to see how popular it has become and also disappointing in some ways because many users, sadly, are not quite as nice as you are.  I'm glad people find it useful.
