### ISSUE TITLE
New camera models (ring-api project) are not showing up

### ISSUE THREAD

**Issue by moofur** [tsightler/ring-mqtt#752]
### Describe the Bug

New camera models that have been added (~2 weeks ago) are not translating to the ring-mqtt data

### Steps to Reproduce

Set up ring-mqtt with either a Video Doorbell 4 or a Spotlight Cam Plus, note that Home Assistant shows them as "Unknown Model" when other devices show correct model information.

### Expected Behavior

Device models with correct model info in the ring-api project show correct model information in ring-mqtt

### Log Output

```shell
Logs sent separately via encrypted email.
```

### Screenshots

![image](https://github.com/tsightler/ring-mqtt/assets/22972834/05385a1b-6d8b-4a58-8eb7-562f4586aef2)
![image](https://github.com/tsightler/ring-mqtt/assets/22972834/37835b2b-3904-429d-85da-ce3906316dd4)

### Config File

```shell
{
    "mqtt_url": "mqtt://username:password@ip_address:port",
    "mqtt_options": "",
    "livestream_user": "username",
    "livestream_pass": "password",
    "disarm_code": "",
    "enable_cameras": true,
    "enable_modes": false,
    "enable_panic": true,
    "hass_topic": "homeassistant/status",
    "ring_topic": "ring",
    "location_ids": [
        ""
    ]
}
```
```


### Install Type

Docker

### Version

image version 5.6.3

### Operating System

Home Assistant OS

### Architecture

arm64

### Machine Details

Raspberry Pi

**Comment by moofur** [comment]
It's probably important to note:
The two devices I'm specifically referring to are the Video Doorbell 4 (`doorbell_oyster`) and Spotlight Cam Plus (`cocoa_spotlight`). I know those are now in the ring-api project's `ring-types.ts` definition file because I submitted those modifications in a PR a couple weeks ago and the PR has been merged in.
https://github.com/dgreif/ring/pull/1334

**Comment by moofur** [comment]
That being said, I just noticed that dgreif appears to be using release tags on that project. If you're using tagged releases of that project in ring-mqtt, that might explain why the updates aren't showing up in ring-mqtt yet.

**Comment by tsightler** [comment]
This is not a bug, showing "Unknown Model" causes no functional issue so it's perfectly fine and expected.  Sorry if it bothers you for some reason, but it's just a model.  In many ways I regret ever listing the specific models, maybe I will just remove that and generically show "Ring Doorbell" or "Ring Camera" in the future as, believe it or not, I don't live my life stalking Ring product releases.

For now though, new models will eventually be picked up when updates are pushed for new ring-mqtt/ring-client-api are published as there has not yet been a release of ring-client-api or ring-mqtt since your PR was merged.
