### ISSUE TITLE
Bug: Error is logged in Home Assistant "Could not fetch changelog"

### ISSUE THREAD

**Issue by JOHLC** [tsightler/ring-mqtt#842]
### Describe the Bug

Error is logged in Home Assistant "Could not fetch changelog"

### Steps to Reproduce

Reboot with RingMQTT installed 

### Expected Behavior

No errors in logs

### Log Output

```shell
Log details (ERROR)
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:612
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 9:35:18 PM (2 occurrences)
Last logged: 9:35:33 PM

Client error on /addons/03cabcc9_ring_mqtt/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/03cabcc9_ring_mqtt/changelog')


Log details (WARNING)
Logger: homeassistant.components.hassio.data
Source: components/hassio/data.py:497
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 9:35:18 PM (2 occurrences)
Last logged: 9:35:33 PM

Could not fetch changelog for 03cabcc9_ring_mqtt:
```

### Screenshots

![Screenshot 2024-05-28 214420](https://github.com/tsightler/ring-mqtt/assets/63735432/0d35cc35-a8be-47a3-ad12-41840cea7654)

### Config File

```shell
enable_cameras: true
snapshot_mode: disabled
livestream_user: "!secret ring_lsu"
livestream_pass: "!secret ring_lsp"
enable_modes: true
enable_panic: true
beam_duration: 0
disarm_code: "!secret ring_code"
mqtt_host: <auto_detect>
mqtt_port: <auto_detect>
mqtt_user: <auto_detect>
mqtt_password: <auto_detect>
branch: main
debug: ring-*
ring_token: ""
location_ids:
  - 1
  - 2
```

### Install Type

Home Assistant addon

### Version

4.8.5

### Operating System

Home Assistant OS (Latest Core and OS)

### Architecture

x64

### Machine Details

VM on VMWare ESXi (16 Cores 16 GB RAM assigned to VM)

**Comment by tsightler** [comment]
> **Version**
> 4.8.5

Current version is 5.6.4, while 4.x versions of ring-mqtt have been obsolete/unsupported for over 2 years, there is no longer even a simple upgrade path so you will have to uninstall v4.8.5 and install v5.6.4 from scratch.

**Comment by JOHLC** [comment]
Wow, I can't believe I missed that. Sorry for assuming that since it showed no update, that it was up to date! Thanks for your time and response.

**Comment by tsightler** [comment]
It's quite strange that it does not show an update, as 4.8.5 was not even the last version of the 4.x branch.  Not only that, but of the >4000 installations that report statistics via Home Assistant analytics, only 8 are still on 4.8.5, while >3500 are on the latest 5.6.4 version and another 457 are on the previous 5.6.3 build, so that 3981.  When a new version is pushed it usually takes <72 hours to hit >50% of users on the latest version due to auto-update.

**Comment by tsightler** [comment]
Also, just for reference, uninstalling the old addon and re-installing the new one should be quite painless overall, especially since it looks like you are using mostly defaults.  Just plugin stuff like your livestream user/password and disarm code back into the config, re-authenticate, and things should be basically the same.  There's some additional notes still at:

https://github.com/tsightler/ring-mqtt/wiki/Upgrading-to-v5.x

**Comment by JOHLC** [comment]
> It's quite strange that it does not show an update, as 4.8.5 was not even the last version of the 4.x branch. Not only that, but of the >4000 installations that report statistics via Home Assistant analytics, only 8 are still on 4.8.5, while >3500 are on the latest 5.6.4 version and another 457 are on the previous 5.6.3 build, so that 3981. When a new version is pushed it usually takes <72 hours to hit >50% of users on the latest version due to auto-update.

I found that for some reason I had removed the repo from the custom repo list. That is likely why I didn't show any update.
Also, I did find that article and the upgrade was painless, just like you said. 

Thanks again
