### ISSUE TITLE
[not an issue] Trigger siren remotely?

### ISSUE THREAD

**Issue by talshum** [tsightler/ring-mqtt#9]
I'm trying to think how we can trigger the alarm remotely. Let's say I'm not home and noticed something on the outside. How can I trigger the siren to scare off the intruder?

The only way I think of is to broadcast a mqtt with one of the contact sensors opened. Then the alarm will think someone opened the door and trigger it. Thoughts?

**Comment by tsightler** [comment]
I'm not sure what you mean by "broadcast a mqtt with one of the contact sensors opened".  There is no method that I've seen to be able to trigger the alarm via the API, and I suspect it is intentionally designed this way.

I can see only two ways to do this:

1) It should be possible to trigger a "Test Siren" event since this is possible within the Ring app already.  This would require research into the API to learn how the app does this, but it's probably some simple JSON command.  However, this wouldn't trigger an actual alarm event, and it only works if the alarm is disabled, the latter of which is a pretty big down side, IMO, although I guess you could build an automation to disarm alarm, trigger test siren even, then re-arm, but that's UGLY!

2)  Use some external, mechanical/electronic means that can be used to trigger the contact or motion sensor.  For example, you could pretty easily rig up a RPi to trigger a simple solenoid via the GPIO pins and have it move the magnet away from the contact sensor to trigger the alarm.  This has the advantage of triggering an actual alarm.

Personally, I just use my Ring cameras for this since they have a siren function built in and I have one at every entrance.  I'm planning to add support for sounding the siren on ring cameras in a future version, and possibly flip lights on/off for ring floodlight/spotlight cams.

**Comment by talshum** [comment]
Got it. Thanks so much for the reply. I think I’ll purchase zwave siren and will connect it directly to hass.io


________________________________

**Comment by tsightler** [comment]
That's probably the easiest option for sure.
