### ISSUE TITLE
need help "device-/topic-name" (ring-mqtt + FHEM + "MQTT2_SERVER"-Broker)

### ISSUE THREAD

**Issue by SmilyHM** [tsightler/ring-mqtt#97]
--> scroll down for my bad-english ;-)

Hallo zusammen,

ich brauche eure Hilfe. Mein FHEM-MQTT-Broker legt beim ersten Connect eines Gerätes ein neues FHEM-Device an - den Namen holt es sich (gehe ich zumindest stark von aus) aus dem Topic.

Jedes Mal, wenn ich den ring-mqtt-Service stoppe+starte oder restarte erhalte wird immer ein neues FHEM-Device angelegt, da sich das Topic ändert:

mqttjs_**082bc927**:homeassistant/binary_sensor/...
mqttjs_**b0e8b7fc**:homeassistant/binary_sensor/...
mqttjs_**d6da5183**:homeassistant/binary_sensor/...

Was kann bzw. muss ich denn machen, damit ich immer das gleiche Topic erhalte?

Danke euch und viele Grüße
Sascha

Hi everybody,

I need your help. The FHEM-"MQTT2_SERVER" will define a FHEM-device on it's first connection to the broker (name from topic, i guess).

My problem is: On every stop+start/restart of the service I get a new defined device:

mqttjs_**082bc927**:homeassistant/binary_sensor/...
mqttjs_**b0e8b7fc**:homeassistant/binary_sensor/...
mqttjs_**d6da5183**:homeassistant/binary_sensor/...

what do I have to do to get always the same topic??

Thanks and best regards
Sascha

**Comment by tsightler** [comment]
I'm afraid this question should be directed to the FHEM community and is not really related to anything here.  The information you are highlighting is not something that is coming from the ring-mqtt script, the ring-mqtt script creates topics starting with homeassistant/ and ring/ while the mqttjs_<random_number> is some type of ID generated by FHEM.  You will notice that ring-mqtt generates 100% consistent topics each time using location/device IDs.

Just taking a quick glance at the FHEM docs (I had never even heard of it) it appears that is has some ability to create regex rules to ignore topics or map the id to specific topic levels.  Also, I double you need to care about the topics that start with homeassistant/ at all as those are just used to publish discovery messages to home assistant.  Unless FHEM supports home assistant style MQTT discovery these would be totally useless.  The actual devices are all published in the topic starting with ring/.

Regardless, the issue you are posting about is specific to FHEM and nothing to do with ring-mqtt and I'm not going to be able to help you with that.

**Comment by SmilyHM** [comment]
Hi and thank you for your very quick reply and the gread information! :-)

I thought, it should be a ring-mqtt- or mqttjs-problem, because this "strange thing" never happens to any other of my mqtt-devices in my setup (shelly, raspberry pi, esp8266/esp32/ip-cam).

But of course I'll have a look (and post the question) at the fhem-forum now and also have a look at the regex/ignor-rules - thanks for this hint!

And again --> thank you! :-)

Best regards!
Sascha

**Comment by tsightler** [comment]
OK, good point if you are not seeing this from other tools.  After hearing that it got me thinking that perhaps its not being generated by this code directly, but maybe somehow indirectly.

Some quick digging and it became obvious that what you are seeing is the default "clientId" generated by MQTT.js if it's not defined explicitly during the connection.  I'm not setting a specific clientID on my side because it wasn't required for the scripts normal use case and, according to the MQTT.js documantation, this will cause MQTT.js to generate one randomly using the following formula:

> clientId: 'mqttjs_' + Math.random().toString(16).substr(2, 8)

That looks exactly like what you are seeing.  While I would not necessarily consider this a bug since it's not a problem for the scripts normal use case, it still might be worth me setting a static clientId in the future if it can be helpful for use cases like yours.  This is really easy to change and test.  Look for the initMqtt function in the ring-mqtt.js file:
```
function initMqtt() {
    const mqtt = mqttApi.connect({
        host:CONFIG.host,
        port:CONFIG.port,
        username: CONFIG.mqtt_user,
        password: CONFIG.mqtt_pass
    });
    return mqtt
}
```

And add a line to define the clientId like this:
```
function initMqtt() {
    const mqtt = mqttApi.connect({
        host:CONFIG.host,
        port:CONFIG.port,
        clientId: 'ring-mqtt',
        username: CONFIG.mqtt_user,
        password: CONFIG.mqtt_pass
    });
    return mqtt
}
```
Let me know if that solves the problem for you'll and I'll consider setting it in the future.

**Comment by tsightler** [comment]
BTW, just to add some clarity as to why I don't use a static clientId today, when you connect to the MQTT broker every connected client requires a unique clientId.  If a client with the same clientId connects the the same MQTT broker, this existing client is kicked out and the new client "takes over" the connection.

At first this may not sound so bad but what happens if there is more than a single instance of ring-mqtt running?  This can happen, for example, if a user wants to monitor multiple Ring accounts via MQTT.  The script only supports a single Ring account at one time, but you can run as many instances of ring-mqtt as you want using different accounts.  This is fully supported with ring-mqtt today and I know there are mulitple users taking advantage of this capability.  If I statically set the clientId this would not work.

I guess I could generate a clientId for each user on first run and store it in the state file like I'm now doing for refresh tokens.  Perhaps I'll consider this in the future.  Or perhaps just a method to manually configure a clientId in the config.  I never realized there would be any client that would care about the clientId vs just monitoring the topic/message values as it appears FHEM is doing.
